// Module included in the following module:
//
// proc-oauth-authorization-broker-config.adoc

[id='con-oauth-authorization-keycloak-authorization-services_{context}']
= Managing policies and permissions in Keycloak Authorization Services

== Kafka authorization model for resources

The link:https://kafka.apache.org/documentation/#security_authz_primitives[Kafka authorization model] defines resource types, and the permissions available for each type.
When an action is performed by a Kafka client on a broker, the broker uses a configured authorizer to check permissions, depending on the action performed and the resource type.

Kafka has five resource types for controlling access: `Topic`, `Group`, `Cluster`, `TransactionalId`, `DelegationToken`.

Each resource type has different permissions:

Topic:

* `Create`
* `Write`
* `Read`
* `Delete`
* `Describe`
* `DescribeConfigs`
* `Alter`
* `AlterConfigs`

Group:

* `Read`
* `Describe`
* `Delete`

Cluster:

*  `Create`
*  `Describe`
*  `Alter`
*  `DescribeConfigs`
*  `AlterConfigs`
*  `IdempotentWrite`
*  `ClusterAction`

TransactionalId:

*  `Describe`
*  `Write`

DelegationToken:

* `Describe`

== Keycloak Authorization Services model for managing permissions

Keycloak Authorization Services use four concepts to define and grant permissions: _resources_, _authorization scopes_, _policies_, and _permissions_.

Resources:: Resources are a set of resource definitions that are used to match permitted actions.
For example, a resource can be an individual topic, or it can be a set of all topics with names that start with the same prefix.
The resource definition has a set of available `authorization scopes` associated with it. These represent a set of all actions that can be permitted.
Often, only a subset of these actions is actually permitted.

Authorization scopes:: Authorization scopes is simply a set of all available actions on all the different resource types. When defining a new resource,  scopes are added from the set of all scopes.

Policies:: Policies are rules that use criteria to match a list of accounts. Policies can match service accounts based on client id, or user accounts based on username, group, or roles.

Permissions:: Permissions grant a subset of authorization scopes on a specific resource definition to a set of users.

== Mapping Keycloak Authorization Services to Kafka Model

Use Keycloak Authorization Services rules on the OAuth client that represents the Kafka Broker to grant Kafka permissions to users or service accounts. Typically, the OAuth client has `kafka` as its client id.

The OAuth 2.0 client definition must have the _Authorization Enabled_ option activated.

All permissions exist within the scope of this OAuth 2.0 client, which means that if you have different Kafka clusters configured with different OAuth 2.0 client IDs they would each have a separate set of permissions even though they are part of the same realm.

When the Kafka client use the _SASL OAUTHBEARER_ mechanism, the Keycloak authorizer (`KeycloakRBACAuthorizer`) retrieves the list of grants for the current session from the Keycloak server using the access token of the current session.
This list of grants is the result of evaluating the Keycloak Authorization Services policies and permissions.

.Introducing authorization scopes

Typically, an initial configuration involves uploading the authorization scopes to create a list of all the possible actions that can be performed on all the Kafka resource types.
This step is performed only once, before defining any permissions. Alternatively, you can add authorization scopes manually.

The authorization scopes should contain all the possible Kafka permissions regardless of the resource type:

* `Create`
* `Write`
* `Read`
* `Delete`
* `Describe`
* `Alter`
* `DescribeConfig`
* `AlterConfig`
* `ClusterAction`
* `IdempotentWrite`

.Defining resource patterns for permission checks

The resources use pattern names for pattern matching against the targeted resources when performing permission checks.

The general pattern is as follows: `RESOURCE_TYPE:NAME_PATTERN`

The resource types mirror the Kafka authorization model.
The pattern allows for the two matching options: exact matching (when the pattern does not end with `\*`), and prefix matching (when the pattern ends with `*`).

.Example patterns for resources
    Topic:my-topic
    Topic:orders-*
    Group:orders-*
    Cluster:*

In addition, the general pattern can be prefixed by `kafka-cluster:CLUSTER_NAME` followed by a comma, where the cluster name refers to the `metadata.name` in the Kafka custom resource.

.Example patterns for resources with cluster prefix
    kafka-cluster:my-cluster,Topic:*
    kafka-cluster:*,Group:b_*

When the `kafka-cluster` prefix is not present it is assumed to be `kafka-cluster:*`.

When defining a resource, you can associate a list of possible authorization scopes relevant to the resource.
Set whatever actions make sense for the targeted resource type.

While you may add any authorization scope to any resource, only the scopes supported by the resource type are considered for access control.

.Policies

Policies are used to target permissions to one or more accounts.
Targeting can refer to:
* Specific user or service accounts
* Realm roles or client roles
* User groups
* JS rule to match a client IP address

A policy is given a unique name, and can be reused to target multiple permissions to multiple resources.

.Defining permissions based on scopes, resources and policies 

Use fine-grained permissions to pull together the policies, resources, and authorization scopes that grant access to users.


The name of the each permission should should clearly define what permissions it grants to which users.

For more information on how to configure permissions through Keycloak Authorization Services, see xref:con-oauth-authorization-keycloak-example_str[the authorization example].


== Permissions required by operations

.Creating a topic

To create a topic the `Create` permission is required for the specific topic or `Cluster:kafka-cluster`.
To display the details of the created topic the `Describe` permission is required for the specific topic.

.Producing to the topic

To produce to the topic the user needs `Describe` and `Write` permissions on the topic.
If topic has not yet been created, and autocreation is enabled, the permissions to create the topic are required.

.Consuming from the topic

To consume from the topic the user needs `Describe` and `Read` permissions on the topic.
Consuming from the topic normally relies on storing the consumer offsets in a consumer group.
That requires additional `Describe` and `Read` permissions on the consumer group.

Two `resources` are needed for matching. For example:

    Topic:my-topic
    Group:my-group-*

.Producing to the topic using an idempotent producer

Besides needing the permissions for ordinary producing to the topic, an additional `IdempotentWrite` permission is required on the `Cluster` resource.

Two `resources` are needed for matching. For example:

    Topic:my-topic
    Cluster:kafka-cluster

.Listing topics

When listing topics, only the topics on which a user has `Describe` permission are returned.

.Displaying topic details

The `DescribeConfigs` permission is required on the topic to be able to retrieve information on partitions, replicas, and so on.

.Listing consumer groups

When listing consumer groups, only the groups on which the user has `Describe` permissions are returned.
Alternatively, if the user has `Describe` permission on the `Cluster:kafka-cluster`, all the consumer groups are returned.

.Getting the Kafka broker configuration

To be able to use `kafka-configs.sh` to get the broker configuration, `Describe` permission is required on the `Cluster:kafka-cluster`.

.Describing consumer groups

To be able to `kafka-consumer-groups.sh` to get detailed information about all consumer groups, `Describe` permission is required on the `Cluster:kafka-cluster`.

TODO: more cases + add CLI example to each
