// Module included in the following assemblies:
//
// assembly-oauth-authentication.adoc

[id='con-oauth-authentication-flow-{context}']
= OAuth 2.0 authentication mechanisms

Strimzi supports the SASL_OAUTHBEARER and SASL_PLAIN mechanisms for OAuth 2.0 authentication. 
Both mechanisms allow Kafka clients to establish authenticated sessions with Kafka brokers. 
The authentication flow between clients, the authorization server, and Kafka brokers is different for each mechanism.

Configure clients to use SASL_OAUTHBEARER for authentication with Kafka brokers whenever possible. 
This mechanism provides a higher level of security because client credentials are _never_ shared with Kafka brokers. 
Consider using SASL_PLAIN only with Kafka clients that do not support SASL_OAUTHBEARER. 

.SASL_OAUTHBEARER overview

Support for SASL_OAUTHBEARER is built in to many Kafka clients. 
However, the developer must often write custom callbacks that provide access tokens for authentication, as needed.
Strimzi provides these callbacks for standard Java Kafka clients (clients that use the Kafka producer and consumer APIs). 
Therefore, developers do not need to provide custom callbacks in their application code. 

With SASL_OAUTHBEARER, the client initiates a session with the Kafka broker for credentials exchange, where credentials take the form of a bearer token provided by the Strimzi OAuth callback code. 
Using the callbacks, you can configure token provision in one of three ways:

* Client ID and Secret (by using the OAuth 2.0 client credentials mechanism)

* A long-lived access token, obtained manually at configuration time

* A long-lived refresh token, obtained manually at configuration time

SASL_OAUTHBEARER is automatically enabled in the `oauth` listener configuration for the Kafka broker. 
You can set the `enableOauthBearer` property to `true`, though this is not required.

[source,yaml,subs="attributes+"]
----
  # ...
  authentication:
    type: oauth
    # ...
    enableOauthBearer: true
----

.SASL_PLAIN overview

SASL_PLAIN, also referred to as _OAuth 2.0 over PLAIN_, is a simple authentication mechanism supported by all Kafka client tools (including developer tools such as kafkacat). 
Client credentials are handled centrally, behind an authorization server that complies with OAuth 2.0 and OpenID Connect (OIDC).

When used with the provided callbacks, SASL_PLAIN allows Kafka clients to authenticate with Kafka brokers using either of the following methods:

* Client ID and Secret (by using the OAuth 2.0 client credentials mechanism)

* A long-lived access token, obtained manually at configuration time

The client must enable SASL_PLAIN and set the `username` and `password`. 
If the client prefixes the `password` with `$accessToken:` followed by the value of the access token (access token ???), the authorization server will interpret the password as the access token. 
Otherwise, the authorization server will interpret the `username` as the client ID and the `password` as the client secret.

If the `password` is set as the access token, the `username` must be set to the same principal name that the Kafka broker obtains from the access token. 
The process depends on how you configure username extraction (using `userNameClaim`, `fallbackUserNameClaim`, `fallbackUsernamePrefix`, and `userInfoEndpointUri`), and also your authorization server (in particular, how it maps client IDs to account names).

To use SASL_PLAIN, you must enable it in the `oauth` listener configuration for the Kafka broker.

In the following example, SASL_PLAIN is enabled in addition to SASL_OAUTHBEARER, which is enabled by default. 
If you want to use SASL_PLAIN only, you can disable SASL_OAUTHBEARER by setting `enableOauthBearer` to `false`.

[source,yaml,subs="+quotes,attributes+"]
----
  # ...
  authentication:
    type: oauth
    # ...
    enablePlain: true
    tokenEndpointUri: https://_OAUTH-SERVER-ADDRESS_/auth/realms/external/protocol/openid-connect/token
----

.Additional resources

* xref:proc-oauth-authentication-broker-config-{context}[]
