// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration-kafka.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='assembly-configuring-kafka-broker-listeners-{context}']
= Kafka broker listeners

You can configure the listeners enabled in Kafka brokers.
The following types of listeners are supported:

* Plain listener on port 9092 (without TLS encryption)
* TLS listener on port 9093 (with TLS encryption)
* External listener on port 9094 for access from outside of Kubernetes

For more information on listener configuration, see xref:type-KafkaListeners-reference[`KafkaListeners` schema reference].

.Configuring listeners to secure access to Kafka brokers
You can configure listeners for secure connection using authentication.
For more information on securing access to Kafka brokers, see xref:assembly-securing-kafka-str[Managing access to Kafka].

.Configuring external listeners for client access outside Kubernetes
You can configure external listeners for client access outside a Kubernetes environment using a specified connection mechanism, such as a loadbalancer.
For more information on the configuration options for connecting an external client, see xref:assembly-configuring-external-listeners-str[Configuring external listeners].

.Listener certificates
You can provide your own server certificates, called _Kafka listener certificates_, for TLS listeners or external listeners which have TLS encryption enabled.
For more information, see xref:kafka-listener-certificates-str[].
