// This assembly is included in the following assemblies:
//
// master.adoc

[id='assembly-upgrade-resources-{context}']
= {ProductName} resource upgrades
For this release of {ProductName}, resources that use the API version `{KafkaApiVersionPrev}` must be updated to use `{KafkaApiVersion}`.

The `{KafkaApiVersionPrev}` API version is deprecated.

This section describes the upgrade steps for the resources.

IMPORTANT: The upgrade of resources _must_ be performed after xref:assembly-upgrade-{context}[upgrading the Cluster Operator], so the Cluster Operator can understand the resources.

.What if the resource upgrade does not take effect?
If the upgrade does not take effect, a warning is given in the logs on reconciliation to indicate that the resource cannot be updated until the `apiVersion` is updated.

To trigger the update, make a cosmetic change to the custom resource, such as adding an annotation.

Example annotation:

[source,shell,subs="+quotes,attributes"]
----
metadata:
  # ...
  annotations:
    upgrade: "Upgraded to {KafkaApiVersion}"
----

include::../modules/proc-upgrading-kafka-resources.adoc[leveloffset=+1]
include::../modules/proc-upgrading-kafka-connect-resources.adoc[leveloffset=+1]
include::../modules/proc-upgrading-kafka-connect-s2i-resources.adoc[leveloffset=+1]
include::../modules/proc-upgrading-kafka-mirror-maker-resources.adoc[leveloffset=+1]
include::../modules/proc-upgrading-kafka-topic-resources.adoc[leveloffset=+1]
include::../modules/proc-upgrading-kafka-user-resources.adoc[leveloffset=+1]
