// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration.adoc

//attribute for use in snip-inline-logging.adoc
:kind: KafkaMirrorMaker

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.
:parent-context-deployment-configuration-kafka-mirror-maker: {context}

[id='assembly-deployment-configuration-kafka-mirror-maker-{context}']
= Kafka MirrorMaker configuration

:context: deployment-configuration-kafka-mirror-maker

This chapter describes how to configure a Kafka MirrorMaker deployment in your {ProductName} cluster to replicate data between Kafka clusters.

You can use {ProductName} with MirrorMaker or xref:assembly-mirrormaker-str[MirrorMaker 2.0].
MirrorMaker 2.0 is the latest version, and offers a more efficient way to mirror data between Kafka clusters.

If you are using MirrorMaker, you configure the `KafkaMirrorMaker` resource.

The following procedure shows how the resource is configured:

* xref:configuring-kafka-mirror-maker-{context}[Configuring Kafka MirrorMaker]

Supported properties are also described in more detail for your reference:

* xref:con-configuring-mirror-maker-{context}[Kafka MirrorMaker configuration properties]

The full schema of the `KafkaMirrorMaker` resource is described in the xref:type-KafkaMirrorMaker-reference[KafkaMirrorMaker schema reference].

NOTE: Labels applied to a `KafkaMirrorMaker` resource are also applied to the Kubernetes resources comprising Kafka MirrorMaker.
This provides a convenient mechanism for resources to be labeled as required.

include::../modules/proc-configuring-mirror-maker.adoc[leveloffset=+1]

include::../modules/con-configuring-mirror-maker.adoc[leveloffset=+1]

include::../modules/ref-list-of-kafka-mirror-maker-resources.adoc[leveloffset=+1]

// Restore the context to what it was before this assembly.
:context: {parent-context-deployment-configuration-kafka-mirror-maker}
