// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration-kafka-connect.adoc
// assembly-deployment-configuration-kafka-connect-s2i.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='assembly-kafka-connect-external-configuration-{context}']

= Using external configuration and secrets

Connectors are created, reconfigured, and deleted using the Kafka Connect HTTP REST interface, or by using `KafkaConnectors`. For more information on these methods, see link:{BookURLDeploying}#con-creating-managing-connectors-str[Creating and managing connectors^] in the _Deploying Strimzi_ guide.
The connector configuration is passed to Kafka Connect as part of an HTTP request and stored within Kafka itself.

ConfigMaps and Secrets are standard Kubernetes resources used for storing configurations and confidential data.
Whichever method you use to manage connectors, you can use ConfigMaps and Secrets to configure certain elements of a connector.
You can then reference the configuration values in HTTP REST commands (this keeps the configuration separate and more secure, if needed).
This method applies especially to confidential data, such as usernames, passwords, or certificates.

include::../modules/con-kafka-connect-external-configuration.adoc[leveloffset=+1]

include::../modules/proc-kafka-connect-mounting-secrets-as-environment-variables.adoc[leveloffset=+1]

include::../modules/proc-kafka-connect-mounting-volumes.adoc[leveloffset=+1]
