// This assembly is included in the following assemblies:
//
// master.adoc

[id='assembly-metrics-setup-{context}']
= Introducing Metrics

This section describes how to monitor {ProductName} Kafka, ZooKeeper, Kafka Connect, and Kafka Mirror Maker2 clusters using Prometheus to provide monitoring data for example Grafana dashboards.

In order to run the example Grafana dashboards, you must:

. xref:assembly-metrics-kafka-{context}[Add metrics configuration to your Kafka cluster resource]
. xref:assembly-metrics-prometheus-{context}[Deploy Prometheus and Prometheus Alertmanager]
. xref:assembly-metrics-grafana-{context}[Deploy Grafana]

NOTE: The resources referenced in this section are intended as a starting point for setting up monitoring, but they are provided as examples only.
If you require further support on configuring and running Prometheus or Grafana in production, try reaching out to their respective communities.

.Kafka Exporter
When you have Prometheus and Grafana enabled, you can also use Kafka Exporter to provide additional monitoring related to consumer lag.
For more information, see xref:assembly-kafka-exporter-{context}[].

.Operators
Prometheus and Grafana can be also used to monitor the operators.
The example Grafana dashboard for operators provides:

* Information about the operator such as the number of reconciliations or number of Custom Resources they are processing
* JVM metrics from the operators

.Additional resources
* For more information about Prometheus, see the link:https://prometheus.io/docs/introduction/overview/[Prometheus documentation].
* For more information about Grafana, see the link:https://grafana.com/docs/guides/getting_started/[Grafana documentation].
* link:http://kafka.apache.org/documentation/#monitoring[Apache Kafka Monitoring] describes JMX metrics exposed by Apache Kafka.
* link:https://zookeeper.apache.org/doc/current/zookeeperJMX.html[ZooKeeper JMX] describes JMX metrics exposed by Apache ZooKeeper.

include::../modules/ref-metrics-config-files.adoc[leveloffset=+1]

include::assembly-metrics-kafka.adoc[leveloffset=+1]

include::assembly-metrics-prometheus.adoc[leveloffset=+1]

include::assembly-metrics-prometheus-alertmanager.adoc[leveloffset=+1]

include::assembly-metrics-grafana.adoc[leveloffset=+1]

include::../modules/con-metrics-kafka-mini-kube-shift.adoc[leveloffset=+1]
