// This assembly is included in the following assemblies:
//
// getting-started.adoc

[id='assembly-getting-started-strimzi-admin-{context}']
= Strimzi Administrators

{ProductName} includes several custom resources.
By default, permission to view, create, edit, and delete these resources is limited to Kubernetes cluster administrators.
{ProductName} provides two cluster roles which you can use to assign these rights also to other users:

* `strimzi-view` allows users to view and list {ProductName} resources.
* `strimzi-admin` allows users to also create, edit or delete {ProductName} resources.

When you install these roles, they will automatically aggregate (add) these rights to the default Kubernetes cluster roles.
`strimzi-view` aggregates to the `view` role, and `strimzi-admin` aggregates to the `edit` and `admin` roles.
Because of the aggregation, you might not need to assign these roles to users who already have similar rights.

include::../modules/proc-designating-strimzi-administrators.adoc[leveloffset=+1]

