// This assembly is included in the following assemblies:
//
// assembly-config.adoc

[id='assembly-storage-{context}']
= Configuring Kafka storage

[role="_abstract"]
Strimzi supports the following Kafka storage types: 

Ephemeral storage:: Ephemeral storage is temporary and only persists while a pod is running. 
When a pod is deleted, the data is lost, though data can be recovered in a highly available environment. 
Due to its transient nature, ephemeral storage is only recommended for development and testing environments.

Persistent storage:: Persistent storage retains data across pod restarts and system disruptions, making it ideal for production environments. 

JBOD storage:: JBOD storage allows you to configure your Kafka cluster to utilize multiple disks or volumes.
Volumes can be ephemeral or persistent. 
 
Tiered storage:: Tiered storage is an early access feature for Kafka, providing more flexibility for data management by leveraging the parallel use of storage types with different characteristics.
For example, tiered storage might include the following:
+
* Higher performance and higher cost block storage
* Lower performance and lower cost object storage

NOTE: The storage type cannot be changed after a Kafka cluster is deployed, though you can create and migrate to node pools with new storage specifications.

include::../../modules/configuring/con-considerations-for-data-storage.adoc[leveloffset=+1]

//KRaft storage
include::../../modules/configuring/con-config-storage-kraft.adoc[leveloffset=+1]
include::../../modules/configuring/proc-managing-storage-node-pools.adoc[leveloffset=+2]
include::../../modules/configuring/proc-managing-storage-affinity-node-pools.adoc[leveloffset=+2]
//ZooKeeper storage
include::../../modules/configuring/con-config-storage-zookeeper.adoc[leveloffset=+1]
//tiered storage
include::../../modules/configuring/ref-storage-tiered.adoc[leveloffset=+1]