// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration.adoc

[id='external-logging_{context}']
= External logging

When setting the logging levels for a resource, you can specify them _inline_ directly in the `spec.logging` property of the resource YAML:

[source,shell,subs="+quotes,attributes"]
----
spec:
  # ...
  logging:
    type: inline
    loggers:
      kafka.root.logger.level: "INFO"
----

Or you can specify _external_ logging:

[source,shell,subs="+quotes,attributes"]
----
spec:
  # ...
  logging:
    type: external
    valueFrom:
      configMapKeyRef:
        name: _customConfigMap_
        key: _keyInConfigMap_
----

With external logging, logging properties are defined in a ConfigMap.
The name of the ConfigMap is referenced in the `spec.logging.valueFrom.configMapKeyRef.name` property.
The `spec.logging.valueFrom.configMapKeyRef.name` and `spec.logging.valueFrom.configMapKeyRef.key` properties are mandatory.
Default logging is used if the `name` or `key` is not set.

The advantages of using a ConfigMap are that the logging properties are maintained in one place and are accessible to more than one resource.

include::../../modules/configuring/proc-creating-configmap.adoc[leveloffset=+1]
