// This assembly is included in the following assemblies:
//
// assembly-config-kafka.adoc

[id='assembly-jmxtrans-{context}']
= Retrieving JMX metrics with JmxTrans

link:https://github.com/jmxtrans/jmxtrans[JmxTrans^] is a tool for retrieving JMX metrics data from Java processes and pushing that data, in various formats, to remote sinks inside or outside the cluster.
JmxTrans can communicate with a secure JMX port.

Strimzi supports using JmxTrans to read JMX metrics from Kafka brokers.

JmxTrans reads JMX metrics data from secure or insecure Kafka brokers and pushes the data to remote sinks in various data formats.
For example, JmxTrans can obtain JMX metrics about the request rate of each Kafka broker's network and then push the data to a Logstash database outside the Kubernetes cluster.

include::../../modules/configuring/proc-jmxtrans-deployment.adoc[leveloffset=+1]

== Additional resources

For more information about JmxTrans, see the link:https://github.com/jmxtrans/jmxtrans[JmxTrans github^].
