// This assembly is included in the following assemblies:
//
// assembly-config.adoc

[id='assembly-kafka-entity-operator-{context}']

= Configuring Strimzi operators

[role="_abstract"]
The Entity Operator is responsible for managing Kafka-related entities in a running Kafka cluster. It comprises the following operators:

* Topic Operator to manage Kafka topics
* User Operator to manage Kafka users

By configuring the `Kafka` resource, the Cluster Operator can deploy the Entity Operator, including one or both operators. 
Once deployed, the operators are automatically configured to handle the topics and users of the Kafka cluster. 

It's important to note that each operator can only monitor a single namespace.
For more information, see xref:con-operators-namespaces-str[].

include::../../modules/configuring/ref-kafka-entity-operator.adoc[leveloffset=+1]
//topic operator config
include::../../modules/configuring/con-configuring-topic-operator.adoc[leveloffset=+1]
//user operator config
include::../../modules/configuring/con-configuring-user-operator.adoc[leveloffset=+1]
