// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration.adoc

[id='assembly-config-kafka-{context}']
= Kafka cluster configuration

[role="_abstract"]
Configure a Kafka deployment using the `Kafka` resource.
A Kafka cluster is deployed with a ZooKeeper cluster, so configuration options are also available for ZooKeeper within the `Kafka` resource.
The Entity Operator comprises the Topic Operator and User Operator.
You can also configure `entityOperator` properties in the `Kafka` resource to include the Topic Operator and User Operator in the deployment. 

xref:type-Kafka-reference[] describes the full schema of the `Kafka` resource.

For more information about Apache Kafka, see the {kafkaDoc}.

.Listener configuration
You configure listeners for connecting clients to Kafka brokers.
For more information on configuring listeners, see xref:type-GenericKafkaListener-reference[].

.Managing TLS certificates
When deploying Kafka, the Cluster Operator automatically sets up and renews TLS certificates to enable encryption and authentication within your cluster.
If required, you can manually renew the cluster and clients CA certificates before their renewal period starts.
You can also replace the keys used by the cluster and clients CA certificates.
For more information, see xref:proc-renewing-ca-certs-manually-{context}[Renewing CA certificates manually] and xref:proc-replacing-private-keys-{context}[Replacing private keys].

//procedure to configure Kafka
include::../../modules/configuring/proc-config-kafka.adoc[leveloffset=+1]
//entity operator config
include::assembly-kafka-entity-operator.adoc[leveloffset=+1]
//storage considerations
include::assembly-storage.adoc[leveloffset=+1]
//scaling Kafka clusters
include::assembly-scaling-clusters.adoc[leveloffset=+1]
//incorporating jmxtrans metrics
ifdef::Metrics[]
include::assembly-jmxtrans.adoc[leveloffset=+1]
endif::Metrics[]
//windows (time) for maintenance
include::assembly-maintenance-time-windows.adoc[leveloffset=+1]
//connecting to ZooKeeper from terminal
include::../../modules/configuring/proc-connecting-to-zookeeper.adoc[leveloffset=+1]
//steps to delete kafka, zookeeper nodes
include::../../modules/configuring/proc-manual-delete-pod-pvc-kafka.adoc[leveloffset=+1]
include::../../modules/configuring/proc-manual-delete-pod-pvc-zookeeper.adoc[leveloffset=+1]
//Kafka cluster resources created
include::../../modules/configuring/ref-list-of-kafka-cluster-resources.adoc[leveloffset=+1]
