// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration.adoc

[id='assembly-kafka-connect-{context}']
= Kafka Connect cluster configuration

[role="_abstract"]
Configure a Kafka Connect deployment using the `KafkaConnect` resource.
Kafka Connect is an integration toolkit for streaming data between Kafka brokers and other systems using connector plugins.
Kafka Connect provides a framework for integrating Kafka with an external data source or target, such as a database, for import or export of data using connectors.
Connectors are plugins that provide the connection configuration needed.

For a deeper understanding of the Kafka Connect cluster configuration options, refer to the link:{BookURLConfiguring}[Strimzi Custom Resource API Reference^].

For more information on deploying connector plugins, see xref:using-kafka-connect-with-plug-ins-str[Adding connectors^].

//procedure to configure Kafka Connect
include::../../modules/configuring/proc-config-kafka-connect.adoc[leveloffset=+1]
//If authorization is enabled, configure the Kafka Connect user for read/write access rights
include::../../modules/configuring/proc-config-kafka-connect-user-authorization.adoc[leveloffset=+1]
//Resources created for Kafka Connect
include::../../modules/configuring/ref-config-list-of-kafka-connect-resources.adoc[leveloffset=+1]
