// This assembly is included in the following assemblies:
//
// configuring/configuring.adoc

[id='assembly-deployment-configuration-{context}']

= Configuring a Strimzi deployment

[role="_abstract"]
Configure your Strimzi deployment using custom resources.
Strimzi provides link:{BookURLDeploying}#deploy-examples-{context}[example configuration files^], which can serve as a starting point when building your own Kafka component configuration for deployment.

NOTE: Labels applied to a custom resource are also applied to the Kubernetes resources making up its cluster.
This provides a convenient mechanism for resources to be labeled as required.

.Monitoring a Strimzi deployment
You can use Prometheus and Grafana to monitor your Strimzi deployment.
For more information, see link:{BookURLDeploying}#assembly-metrics-str[Introducing metrics to Kafka^].

include::assembly-config-kafka.adoc[leveloffset=+1]

include::assembly-config-kafka-connect.adoc[leveloffset=+1]

include::assembly-config-mirrormaker2.adoc[leveloffset=+1]

include::assembly-config-mirrormaker.adoc[leveloffset=+1]

include::assembly-config-kafka-bridge.adoc[leveloffset=+1]

include::assembly-customizing-kubernetes-resources.adoc[leveloffset=+1]

include::assembly-scheduling.adoc[leveloffset=+1]

include::assembly-logging-configuration.adoc[leveloffset=+1]
