// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration.adoc

[id='assembly-deployment-configuration-kafka-mirror-maker-{context}']
= Kafka MirrorMaker cluster configuration

This chapter describes how to configure a Kafka MirrorMaker deployment in your Strimzi cluster to replicate data between Kafka clusters.

You can use Strimzi with MirrorMaker or xref:assembly-mirrormaker-str[MirrorMaker 2.0].
MirrorMaker 2.0 is the latest version, and offers a more efficient way to mirror data between Kafka clusters.

If you are using MirrorMaker, you configure the `KafkaMirrorMaker` resource.

The following procedure shows how the resource is configured:

* xref:configuring-kafka-mirror-maker-{context}[Configuring Kafka MirrorMaker]

The full schema of the `KafkaMirrorMaker` resource is described in the xref:type-KafkaMirrorMaker-reference[KafkaMirrorMaker schema reference].

include::../../modules/configuring/proc-config-mirrormaker.adoc[leveloffset=+1]

include::../../modules/configuring/ref-list-of-mirrormaker-resources.adoc[leveloffset=+1]
