// This assembly is included in the following assemblies:
//
// assembly-upgrade.adoc

[id='con-upgrade-paths-{context}']
= Strimzi upgrade paths

[role="_abstract"]
Two upgrade paths are available for Strimzi.

Incremental upgrade::
An incremental upgrade involves upgrading Strimzi from the previous minor version to version {ProductVersion}.

Multi-version upgrade::
A multi-version upgrade involves upgrading an older version of Strimzi to version {ProductVersion} within a single upgrade, skipping one or more intermediate versions. 
Upgrading from any earlier Strimzi version to the latest version is possible. 

[id='con-upgrade-paths-kafka-versions-{context}']
== Support for Kafka versions when upgrading

When upgrading Strimzi, it is important to ensure compatibility with the Kafka version being used.

Multi-version upgrades are possible even if the supported Kafka versions differ between the old and new versions. 
However, if you attempt to upgrade to a new Strimzi version that does not support the current Kafka version, xref:con-upgrade-cluster-operator-unsupported-kafka-str[an error indicating that the Kafka version is not supported is generated]. 
In this case, you must upgrade the Kafka version as part of the Strimzi upgrade by changing the `spec.kafka.version` in the `Kafka` custom resource to the supported version for the new Strimzi version.

ifdef::Section[]
[NOTE]
====
You can review supported Kafka versions in the link:https://strimzi.io/downloads/[Supported versions^] table.

* The *Operators* column lists all released Strimzi versions (the Strimzi version is often called the "Operator version").
* The *Kafka versions* column lists the supported Kafka versions for each Strimzi version.
====
endif::Section[]

== Upgrading from a Strimzi version earlier than 0.39

Strimzi {ProductVersion} supports upgrades only for KRaft-based Apache Kafka clusters managed by Strimzi 0.39 and newer.
When upgrading from older Strimzi versions, please make sure to first upgrade to a Strimzi version from 0.39 to 0.45 and migrate to KRaft before upgrading to Strimzi {ProductVersion}.
