// Module included in the following assemblies:
//
// assembly-upgrade-resources.adoc

[id='proc-upgrade-cruise-control-api-version-{context}']
= Upgrading Cruise Control to support {ApiVersion}

.Prerequisites

* A Cluster Operator supporting the `{ApiVersion}` API version is up and running.

.Procedure
Execute the following steps for each `Kafka.spec.cruiseControl` configuration in your Kafka cluster.

. Update the `Kafka` resource in an editor.
+
[source,shell,subs="+quotes,attributes"]
----
kubectl edit kafka _my-cluster_
----

. If `type: external` logging is configured in `.spec.cruiseControl.logging`:
+
Replace the `name` of the ConfigMap containing the logging configuration:
+
[source,yaml,subs="attributes+"]
----
logging:
  type: external
  name: my-config-map
----
+
With the `valueFrom.configMapKeyRef` field and specify both the ConfigMap `name` and the `key` under which the logging is stored:
+
[source,yaml,subs="attributes+"]
----
logging:
  type: external
  valueFrom:
    configMapKeyRef:
      name: my-config-map
      key: log4j2.properties
----

. If the `.spec.cruiseControl.metrics` field is used to enable metrics:

.. Create a new ConfigMap that stores the YAML configuration for the JMX Prometheus exporter under a key. 
The YAML must match what is currently in the `.spec.cruiseControl.metrics` field.
+
[source,yaml,subs="attributes+"]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-metrics
  labels:
    app: strimzi
data:
  cruise-control-metrics-config.yml: |
      <YAML>
----

.. Create a new `.spec.cruiseControl.metricsConfig` field pointing to the ConfigMap and key:
+
[source,yaml,subs="attributes+"]
----
metricsConfig:
  type: jmxPrometheusExporter
  valueFrom:
    configMapKeyRef:
      name: kafka-metrics
      key: cruise-control-metrics-config.yml
----

.. Delete the old `.spec.cruiseControl.metrics` field.

. Save the file, exit the editor and wait for the updated resource to be reconciled.