// Module included in the following assemblies:
//
// assembly-upgrade-resources.adoc

[id='proc-upgrade-entity-operator-{context}']
= Upgrading the Entity Operator

.Prerequisites

* A Cluster Operator supporting the `{ApiVersion}` API version is up and running.

.Procedure

. Update the `Kafka` resource in an editor.
+
[source,shell,subs="+quotes,attributes"]
----
kubectl edit kafka _my-cluster_
----

. If `.spec.entityOperator` is used:

.. Move `affinity` from `.spec.entityOperator.affinity` to `.spec.entityOperator.template.pod.affinity`.

.. Move `tolerations` from `.spec.entityOperator.tolerations` to `.spec.entityOperator.template.pod.tolerations`.

. If `type: external` logging is configured in `.spec.entityOperator.userOperator.logging` or `.spec.entityOperator.topicOperator.logging`:
+
Replace the `name` of the ConfigMap containing the logging configuration:
+
[source,yaml,subs="attributes+"]
----
logging:
  type: external
  name: my-config-map
----
+
With the `valueFrom.configMapKeyRef` field and specify both the ConfigMap `name` and the `key` under which the logging is stored:
+
[source,yaml,subs="attributes+"]
----
logging:
  type: external
  valueFrom:
    configMapKeyRef:
      name: my-config-map
      key: log4j2.properties
----

. Save the file, exit the editor and wait for the updated resource to be reconciled.