name: "Install yq tool"
description: "Install yq tool by our script"

inputs:
  architecture:
    description: "Architecture of the yq tool"
    required: false
    default: "amd64"

runs:
  using: "composite"
  steps:
    - name: Install kubectl
      shell: bash
      run: ".azure/scripts/install_yq.sh"
      env:
        ARCH: ${{ inputs.architecture }}
