// This assembly is included in the following assemblies:
//
// master.adoc

[id='cruise-control-concepts-{context}']
= Cruise Control for cluster rebalancing

You can deploy {CruiseControlProject} to your {ProductName} cluster and access its _cluster rebalancing_ feature through custom resources.

Cruise Control is an open source system for automating Kafka operations, including monitoring cluster workload, rebalancing a cluster based on predefined constraints, and detecting and fixing anomalies, among others. 
It consists of four main components--the Load Monitor, the Analyzer, the Anomaly Detector, and the Executor--and a REST API for all interactions.
{ProductName} utilizes the REST API to support the cluster rebalancing features of Cruise Control.
Other features, such as anomaly detection, Slack notifications, and changing the topic replication factor, are not supported.

NOTE: Example YAML files for Cruise Control are provided in `examples/cruise-control/`.

include::../../modules/cruise-control/con-cruise-control-overview.adoc[leveloffset=+1]

include::../../modules/cruise-control/con-optimization-goals.adoc[leveloffset=+1]

include::../../modules/cruise-control/con-optimization-proposals.adoc[leveloffset=+1]

include::../../modules/cruise-control/proc-deploying-cruise-control.adoc[leveloffset=+1]

include::../../modules/cruise-control/ref-cruise-control-configuration.adoc[leveloffset=+1]

include::../../modules/cruise-control/proc-generating-optimization-proposals.adoc[leveloffset=+1]

include::../../modules/cruise-control/proc-approving-optimization-proposal.adoc[leveloffset=+1]

include::../../modules/cruise-control/proc-stopping-cluster-rebalance.adoc[leveloffset=+1]

include::../../modules/cruise-control/proc-fixing-problems-with-kafkarebalance.adoc[leveloffset=+1]
