# Makefile.maven contains the shared tasks for building Java applications. This file is
# included into the Makefile files which contain some Java sources which should be build
# (E.g. cluster-controller etc.).

java_build:
	echo "Building JAR file ..."
	mvn -q ${MVN_ARGS} install

java_clean:
	echo "Cleaning Maven build ..."
	mvn clean
