// Module included in the following assemblies:
//
// assembly-evaluation.adoc

[id='proc-install-product-{context}']
= Installing Strimzi

Using the xref:proc-product-downloads-{context}[download files], install Strimzi with the Custom Resource Definitions (CRDs) and RBAC configuration required for deployment.

In this task you create namespaces in the cluster for your deployment.
Use namespaces to separate functions.

.Prerequisites

* Installation requires a Kubernetes account with privileges to install Custom Resource Definitions and Role Bindings.
The default install of Minikube has these privileges.

.Procedure

. Navigate to the directory where you extracted the Strimzi ZIP file.
+
[source, shell, subs=+quotes ]
----
cd strimzi-_<version>_
----

. Create a new `kafka` namespace for the Strimzi Kafka Cluster Operator.
+
[source, shell, subs=+quotes ]
----
kubectl create ns kafka
----

. Modify the installation files to reference the `kafka` namespace where you will install the Strimzi Kafka Cluster Operator.
+
NOTE: By default, the files work in the `myproject` namespace.
+
* On Linux, use:
+

[source, shell, subs=+quotes]
----
sed -i 's/namespace: .\*/namespace: kafka/' install/cluster-operator/*RoleBinding*.yaml
----
+
* On Mac, use:
+
[source, shell, subs=+quotes]
----
sed -i '' 's/namespace: .\*/namespace: kafka/' install/cluster-operator/*RoleBinding*.yaml
----
+
* On Windows, open each file in `install/cluster-operator` directory that has `RoleBinding` in the name and find the key `namespace`.
Replace the value `myproject` with `kafka`.

. Create a new `my-kafka-project` namespace where you will deploy your Kafka cluster.
+
[source, shell, subs=+quotes ]
----
kubectl create ns my-kafka-project
----

. Edit the `install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml` file and set the `STRIMZI_NAMESPACE` environment variable to the namespace `my-kafka-project`.
Change the environment variable configuration from this:
+
[source, yaml, subs=+quotes ]
----
# ...
env:
- name: STRIMZI_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
# ...
----
+
To this:
+
[source, yaml, subs=+quotes ]
----
# ...
env:
- name: STRIMZI_NAMESPACE
  value: my-kafka-project
# ...
----

. Give permission to the Cluster Operator to watch the `my-kafka-project` namespace.
+
--
[source, shell, subs=+quotes]
----
kubectl create -f install/cluster-operator/020-RoleBinding-strimzi-cluster-operator.yaml -n my-kafka-project
----
[source, shell, subs=+quotes]
----
kubectl create -f install/cluster-operator/023-RoleBinding-strimzi-cluster-operator.yaml -n my-kafka-project
----
[source, shell, subs=+quotes]
----
kubectl create -f install/cluster-operator/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml -n my-kafka-project
----
--
+
The commands create role bindings that grant permission for the Cluster Operator to access the Kafka cluster.

. Deploy the CRDs, role-based access control (RBAC) resources to manage the CRDs and the deployment to run the Cluster Operator.
+
[source, shell, subs=+quotes ]
----
kubectl create -f install/cluster-operator/ -n kafka
----

. Follow the deployment of the Cluster Operator until it is marked as `Ready`.
+
[source, shell, subs=+quotes ]
----
kubectl get pods -n kafka --watch
----
+
You can also follow the Operator's logs:
+
[source, shell, subs=+quotes ]
----
kubectl logs deployment/strimzi-cluster-operator -n kafka -f
----