// Module included in the following assemblies:
//
// metrics/assembly-metrics.adoc

[id='proc-kafka-exporter-monitoring-{context}']
= Presenting Kafka Exporter metrics in Grafana

[role="_abstract"]
If you are using Prometheus and Grafana to monitor built-in Kafka metrics,
you can configure Prometheus to also scrape the Kafka Exporter endpoint.
You can then present Kafka Exporter metrics in Grafana.

Strimzi provides xref:ref-metrics-dashboards-{context}[example Grafana dashboard configuration files for Kafka Exporter].
The following Kafka Exporter dashboard is provided as a JSON file:

* `strimzi-kafka-exporter.json`

This procedure uses the example dashboard to present metrics data in Grafana.

.Prerequisites
* xref:assembly-metrics-prometheus-{context}[Prometheus and Prometheus Alertmanager are deployed]
* xref:proc-metrics-grafana-dashboard-{context}[Grafana is deployed and connected with Prometheus]

.Procedure

. Edit the `KafkaExporter` properties for the `Kafka` resource.
+
The properties you can configure are shown in this example configuration:
+
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
metadata:
  name: my-cluster
spec:
  # ...
  kafkaExporter:
    image: my-registry.io/my-org/my-exporter-cluster:latest <1>
    groupRegex: ".*" <2>
    topicRegex: ".*" <3>
    resources: <4>
      requests:
        cpu: 200m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi
    logging: debug <5>
    enableSaramaLogging: true <6>
    template: <7>
      pod:
        metadata:
          labels:
            label1: value1
        imagePullSecrets:
          - name: my-docker-credentials
        securityContext:
          runAsUser: 1000001
          fsGroup: 0
        terminationGracePeriodSeconds: 120
    readinessProbe: <8>
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe: <9>
      initialDelaySeconds: 15
      timeoutSeconds: 5
# ...
----
<1> ADVANCED OPTION: Container image configuration, which is link:{BookURLUsing}#con-common-configuration-images-reference[recommended only in special situations].
<2> A regular expression to specify the consumer groups to include in the metrics.
<3> A regular expression to specify the topics to include in the metrics.
<4> link:{BookURLUsing}#con-common-configuration-resources-reference[CPU and memory resources to reserve].
<5> Logging configuration, to log messages with a given severity (debug, info, warn, error, fatal) or above.
<6> Boolean to enable Sarama logging, a Go client library used by Kafka Exporter.
<7> link:{BookURLUsing}#assembly-customizing-kubernetes-resources-str[Customization of deployment templates and pods].
<8> link:{BookURLUsing}#con-common-configuration-healthchecks-reference[Healthcheck readiness probes].
<9> link:{BookURLUsing}#con-common-configuration-healthchecks-reference[Healthcheck liveness probes].

. Create or update the resource.
+
[source,shell,subs="+quotes"]
----
kubectl apply -f _<kafka_config_file>_
----

. Upload the Kafka Exporter dashboard file (`strimzi-kafka-exporter.json`) to Grafana.
+
For more information on uploading dashboards, see xref:proc-metrics-grafana-dashboard-{context}[Enabling the example Grafana dashboards].
+
When the Prometheus server has been collecting Kafka Exporter metrics for some time, the dashboard is populated.
+
Use the Grafana charts to analyze lag and to check if actions to reduce lag are having an impact on an affected consumer group.
If, for example, Kafka brokers are adjusted to reduce lag, the dashboard will show the  _Lag by consumer group_ chart going down and the _Messages consumed per minute_ chart going up.

[role="_additional-resources"]
.Additional resources

* link:{BookURLUsing}#type-KafkaExporterTemplate-reference[`KafkaExporterTemplate` schema reference].
