// Module included in the following assemblies:
//
// assembly-setting-up-tracing-kafka-clients.adoc

[id='proc-configuring-jaeger-tracer-kafka-clients-{context}']
= Initializing a Jaeger tracer for Kafka clients

[role="_abstract"]
Configure and initialize a Jaeger tracer using a set of xref:ref-tracing-environment-variables-{context}[tracing environment variables].

You can initialize a tracer for OpenTracing oir OpenTelemetry.

.Procedure

In each client application add the dependencies for the tracer.

. Add the Maven dependencies to the `pom.xml` file for the client application.
+
.Dependencies for Jaeger tracing with OpenTracing
[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>io.jaegertracing</groupId>
    <artifactId>jaeger-client</artifactId>
    <version>{JaegerClientVersion}</version>
</dependency>
----
+
.Dependencies for Jaeger tracing with OpenTelemetry
[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>io.opentelemetry</groupId>
    <artifactId>opentelemetry-sdk-extension-autoconfigure</artifactId>
    <version>{OpenTelemetryVersion}</version>
</dependency>
<dependency>
    <groupId>io.opentelemetry</groupId>
    <artifactId>opentelemetry-exporter-jaeger</artifactId>
    <version>{OpenTelemetryVersionStable}</version>
</dependency>
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-netty-shaded</artifactId>
    <version>{OpenTelemetryGrpcVersion}</version>
</dependency>
----

. Define the configuration of the tracer using the xref:ref-tracing-environment-variables-{context}[tracing environment variables].

. Create the tracer from the environment variables that you defined in step two.
+
.Creating a tracer for OpenTelemetry
[source,java,subs=attributes+]
----
OpenTelemetry ot = GlobalOpenTelemetry.get()
----
+
.Creating a tracer for OpenTracing
[source,java,subs=attributes+]
----
Tracer tracer = Configuration.fromEnv().getTracer();
----
+
NOTE: For alternative ways to initialize a Jaeger tracer, see the https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-core[core tracing functionality for custom instrumentation^].

. Register the tracer as a global tracer:
+
[source,java,subs=attributes+]
----
GlobalTracer.register(tracer);
----

A Jaeger tracer is now initialized for the client application to use.
