// Module included in the following assemblies:
//
// assembly-distributed tracing.adoc

[id='ref-tracing-environment-variables-{context}']
= Environment variables for tracing

[role="_abstract"]
Use environment variables when you are enabling tracing for Kafka components or initializing a tracer for Kafka clients.

Tracing environment variables are subject to change. 
For the latest information, see the {OpenTelemetryDocs} and {OpenTracingDocs}.

The following tables describe the key environment variables for setting up a tracer. 

.OpenTelemetry environment variables
[cols="2m,1,2",options="header"]
|===

|Property
|Required
|Description

|OTEL_SERVICE_NAME
|Yes
|The name of the Jaeger tracing service for OpenTelemetry.

|OTEL_EXPORTER_JAEGER_ENDPOINT
|Yes
|The exporter used for tracing.

|OTEL_TRACES_EXPORTER
|Yes
|The exporter used for tracing.
Set to `otlp` by default. If using Jaeger tracing, you need to set this environment variable as `jaeger`.
If you are using another tracing implementation, xref:proc-enabling-tracing-type-{context}[specify the exporter used].


|===

WARNING: the OpenTelemetry specification doesn't define any https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md[SDK environment variables^] for enabling TLS on the Jaeger exporter used by default on the Kafka components.
It means that you cannot enable TLS encryption on the gRPC port of your Jaeger backend, otherwise the exporter will not be able to connect.
If you are using the Jaeger operator to deploy the Jaeger instance, set the `collector.grpc.tls.enabled: false` property under the `spec.allInOne.options` in the `Jaeger` custom resource.

NOTE: when using the `otlp` exporter, it is possible to use specific https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md[OTLP environment variables^] to enable TLS.
This way, you can enable TLS on the Jaeger backend OTLP endpoint.

.OpenTracing environment variables
[cols="2m,1,2",options="header"]
|===

|Property
|Required
|Description

m|JAEGER_SERVICE_NAME
|Yes
|The name of the Jaeger tracer service.

m|JAEGER_AGENT_HOST
|No
|The hostname for communicating with the `jaeger-agent` through the User Datagram Protocol (UDP).

m|JAEGER_AGENT_PORT
|No
|The port used for communicating with the `jaeger-agent` through UDP.

|===