:_mod-docs-content-type: PROCEDURE

// Module included in the following assemblies:
//
// assembly-using-cert-manager.adoc

[id='proc-using-cert-manager-{context}']
= (Early Access) Configuring your Kafka cluster to use cert-manager

[role="_abstract"]
Perform the steps in this procedure to enable cert-manager to issue certificates on either a new or existing cluster.

.Prerequisites

* cert-manager is installed in the cluster with a ready `Issuer` or `ClusterIssuer` configured with a Secret that contains a certificate and key pair for the CA. The Secret must have `tls.crt` and `tls.key` keys. The value of `tls.crt` is the CA certificate that you provide to the Cluster Operator in the following step under the `ca.crt` key.

.Procedure

. Create a `Secret` containing the CA certificate that the Cluster Operator should trust.
+
[source,shell,subs="+quotes"]
----
kubectl create secret generic _<ca_cert_secret_name>_ \
  --from-file=ca.crt=_<path_to_ca_cert_pem>_ \
  -n _<namespace>_
----
+
Replace _<ca_cert_secret_name>_ with a name of your choice, _<path_to_ca_cert_pem>_ with the path to the CA certificate PEM file, and _<namespace>_ with the namespace of the Kafka cluster.
+
TIP: To automate provisioning and renewal of this Secret, you can use https://cert-manager.io/docs/trust/trust-manager/[trust-manager] to copy the `ca.crt` from the issuer's Secret into a separate Secret for the Cluster Operator.

NOTE: The `ca.crt` file in the Secret must contain either a single CA certificate or a CA certificate chain that can be used to trust certificates issued by cert-manager.
A cert-manager `SelfSigned` issuer type cannot be used directly because it does not provide a CA certificate.

. Create or update the `Kafka` resource, setting `type: cert-manager` on `clusterCa`, `clientsCa`, or both.
Set `generateCertificateAuthority: false` and provide the `certManager.issuerRef` and `certManager.caCertRef` configuration.
+
.Example `Kafka` resource using cert-manager for both Cluster CA and Clients CA
[source,yaml,subs="attributes+"]
----
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: my-cluster
spec:
  clusterCa:
    generateCertificateAuthority: false <1>
    type: cert-manager <2>
    certManager:
      issuerRef:
        name: my-cluster-issuer <3>
        kind: ClusterIssuer <4>
        group: cert-manager.io <5>
      caCertRef:
        secretName: _<cluster_ca_cert_secret_name>_ <6>
        certificate: ca.crt <7>
  clientsCa:
    generateCertificateAuthority: false
    type: cert-manager
    certManager:
      issuerRef:
        name: my-cluster-issuer
        kind: ClusterIssuer
        group: cert-manager.io
      caCertRef:
        secretName: _<clients_ca_cert_secret_name>_
        certificate: ca.crt
  kafka:
    # ...
  # ...
----
<1> Required. Must be `false` when `type` is `cert-manager`.
<2> Enables cert-manager certificate issuance for this CA role.
<3> Name of the cert-manager `Issuer` or `ClusterIssuer` to use.
<4> Kind of the issuer. Must be `Issuer` or `ClusterIssuer`.
<5> API group of the issuer. Defaults to `cert-manager.io`.
<6> Name of the `Secret` containing the CA certificate.
<7> Key within the `Secret` that holds the CA certificate PEM data.

. Apply the `Kafka` resource.
+
[source,shell,subs="+quotes"]
kubectl apply -f _<kafka_resource_file>_ -n _<namespace>_

. Verify that cert-manager `Certificate` resources have been created for each Kafka component.
+
[source,shell,subs="+quotes"]
kubectl get certificates -n _<namespace>_

When performing this procedure on an existing cluster, the Cluster Operator detects the change and initiates a 2 phased rolling restart (one to establish trust and another one to use new certificates) of all components to switch to the new CA type.

[role="_additional-resources"]
.Additional resources

* xref:con-renewing-certificates-cert-manager-{context}[]
