// Module included in the following assemblies:
//
// assembly-security.adoc

[id='proc-installing-certs-per-listener-{context}']
= Configuring your own Kafka listener certificates

You can provide and configure your own Kafka listener certificates and public keys.
These server certificates can be signed by an external Certificate Authority (CA), such as your company's internal CA or a public CA, rather than the internal cluster CA or clients CA.
Configuring Kafka listener certificates is supported for two types of listeners:

* TLS listeners for inter-cluster communication

* External listeners (including `route`, `loadbalancer`, `ingress`, and `nodeport` types), which have TLS encryption enabled, for communication between Kafka clients and Kafka brokers

.Prerequisites

* A Kubernetes cluster.
* The Cluster Operator is running.
* Public key of the external CA.  
* Your own X.509 certificate in PEM format signed by the external CA.

.Procedure

. Create a `Secret` containing your public key and certificate:
+
[source,shell,subs="+quotes"]
----
kubectl create secret generic _my-secret_ --from-file=_my-listener-key.key_ --from-file=_my-listener-certificate.crt_
----
Installinge file, and public key file in the `configuration.brokerCertChainAndKey` property.
+
.Example configuration for a `loadbalancer` external listener with TLS authentication
[source,yaml,subs="attributes+"]
----
# ...
listeners:
  plain: {}
  external:
    type: loadbalancer
    configuration:
      brokerCertChainAndKey:
        secretName: my-secret
        certificate: my-listener-certificate.crt
        key: my-listener-key.key
    tls: true
    authentication:
      type: tls
# ...
----
+
.Example configuration for a TLS listener
[source,yaml,subs="attributes+"]
----
# ...
listeners:
  plain: {}
  tls:
    configuration:
      brokerCertChainAndKey:
        secretName: my-secret
        certificate: my-listener-certificate.pem
        key: my-listener-key.key
    authentication:
      type: tls
# ...
----

. Apply the new configuration to create or update the resource:
+
[source,shell,subs="+quotes"]
----
kubectl apply -f _kafka.yaml_
----
+
The Cluster Operator starts a rolling update of the Kafka cluster, which updates the configuration of the listener.
+
NOTE: A rolling update is also started if you update a certificate in a `Secret` that is used by a TLS or external listener.

.Additional resources

* xref:installing-your-own-ca-certificates-{context}[] 
