// Module included in the following assemblies:
//
// assembly-security.adoc

[id='proc-installing-certs-per-listener-{context}']
= Configuring your own Kafka listener certificates

You can provide and configure your own Kafka listener certificates and CA public keys for two types of listeners:

* TLS listeners for inter-cluster communication

* External listeners (`route`, `loadbalancer`, `ingress`, and `nodeport` types) which have TLS encryption enabled, for communication between Kafka clients and Kafka brokers

Your client applications should use the CA public key as a trusted certificate in order to verify the identity of the Kafka broker.

.Prerequisites

* A Kubernetes cluster.
* The Cluster Operator is running.
* For each listener, a compatible server certificate signed by an external CA.
** Provide an X.509 certificate in PEM format.
** Use a SAN certificate that specifies the hostnames of the Kafka brokers. For more information, see xref:ref-formats-kafka-listener-certificates-{context}[].
** You can provide a certificate that includes the whole CA chain in the certificate file.

.Procedure

. Create a `Secret` containing your public key and server certificate:
+
[source,shell,subs="+quotes"]
----
kubectl create secret generic _my-secret_ --from-file=_my-listener-key.key_ --from-file=_my-listener-certificate.crt_
----

. Edit the `Kafka` resource for your cluster. Configure the listener to use your `Secret`, certificate file, and public key file in the `configuration.brokerCertChainAndKey` property.
+
.Example configuration for a `loadbalancer` external listener with TLS encryption enabled
[source,yaml,subs="attributes+"]
----
# ...
listeners:
  plain: {}
  external:
    type: loadbalancer
    configuration:
      brokerCertChainAndKey:
        secretName: my-secret
        certificate: my-listener-certificate.crt
        key: my-listener-key.key
    tls: true
    authentication:
      type: tls
# ...
----
+
.Example configuration for a TLS listener
[source,yaml,subs="attributes+"]
----
# ...
listeners:
  plain: {}
  tls:
    configuration:
      brokerCertChainAndKey:
        secretName: my-secret
        certificate: my-listener-certificate.pem
        key: my-listener-key.key
    authentication:
      type: tls
# ...
----

. Apply the new configuration to create or update the resource:
+
[source,shell,subs="+quotes"]
----
kubectl apply -f _kafka.yaml_
----
+
The Cluster Operator starts a rolling update of the Kafka cluster, which updates the configuration of the listeners.
+
NOTE: A rolling update is also started if you update a Kafka listener certificate in a `Secret` that is already used by a TLS or external listener.

.Additional resources

* xref:kafka-listener-certificates-{context}[] 

* xref:type-KafkaListeners-reference[]

* xref:ref-formats-kafka-listener-certificates-{context}[]