// Module included in the following assemblies:
//
// assembly-security.adoc

[id='proc-replacing-your-own-private-keys-{context}']
= Replacing private keys used by your own CA certificates

This procedure describes how to renew CA certificates and keys you installed yourself, instead of using the certificates generated by the Cluster Operator.

If you are using your own certificates, the Cluster Operator will not renew them automatically.
Therefore, it is important that you follow this procedure during the renewal period of the certificate in order to replace CA certificates that will soon expire.

The procedure describes the renewal of CA certificates in PEM format.

.Prerequisites

* The Cluster Operator is running.
* xref:installing-your-own-ca-certificates-{context}[Your own CA certificates and private keys are installed].
* You have new cluster or clients X.509 certificates and keys in PEM format.

.Procedure

Before going through the following steps, make sure that the CN (Common Name) of the new CA certificate is different from the current one.
For example, when the Cluster Operator renews certificates automatically it adds a _v<version_number>_ suffix to identify a version.
Do the same with your own CA certificate by adding a different suffix on each renewal.
By using a different key to generate a new CA certificate, retain the current CA certificate stored in the `Secret`.

. Pause the reconciliation of the `Kafka` custom resource.
+
.. Annotate the custom resource in Kubernetes, setting the `pause-reconciliation` annotation to `true`:
+
[source,shell,subs="+quotes"]
----
kubectl annotate Kafka _NAME-OF-CUSTOM-RESOURCE_ strimzi.io/pause-reconciliation="true"
----
+
For example, for the a `Kafka` custom resource named `my-cluster`:
+
[source,shell,subs="+quotes"]
----
kubectl annotate Kafka my-cluster strimzi.io/pause-reconciliation="true"
----
.. Check that the status conditions of the custom resource show a change to `ReconciliationPaused`:
+
[source,shell,subs="+quotes"]
----
kubectl describe Kafka _NAME-OF-CUSTOM-RESOURCE_
----
+
The `type` condition changes to `ReconciliationPaused` at the `lastTransitionTime`.
+

. Update the corresponding `Secret` retaining the current CA certificate, adding the new CA certificate and updating the generation.
+
.. Edit the existing `Secret`:
+
[source,shell,subs="+quotes"]
kubectl edit secret _CA-CERTIFICATE-SECRET_
+
_CA-CERTIFICATE-SECRET_ is the name of the `Secret`, which is `_KAFKA-CLUSTER-NAME_-cluster-ca-cert` for the cluster CA certificate and `_KAFKA-CLUSTER-NAME_-clients-ca-cert` for the clients CA certificate.
+
Following an example of the `Secret` related to the cluster CA certificate for a Kafka cluster named `my-cluster`.
+
[source,yaml,subs=attributes+]
----
apiVersion: v1
kind: Secret
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0F... <1>
metadata:
  annotations:
    strimzi.io/ca-cert-generation: "0" <2>
  labels:
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
  name: my-cluster-cluster-ca-cert
  #...
type: Opaque
----
<1> Current CA certificate base64 encoded
<2> Current CA certificate generation

.. Retain the current CA certificate.
+
Rename the current `ca.crt` field in the `data` section as `ca-__DATE__.crt`, where _DATE_ is the certificate expiry date in the format _YEAR-MONTH-DAYTHOUR-MINUTE-SECONDZ_.
For example `ca-2022-01-26T17-32-00Z.crt`.
Leave the value for the field as it is to retain the current CA certificate.

.. Encode your new CA certificate into base64.
+
[source,shell,subs="+quotes"]
cat _PATH-TO-NEW-CERTIFICATE_ | base64

.. Update the CA certificate.
+
Create a new `ca.crt` field in the `data` section of the `Secret` and copy the new CA certificate base64 encoded got from the previous step
+
.. Increase the CA certificate generation.
+
Updated the `strimzi.io/ca-cert-generation` annotation with a higher incremental value.
For example, change `strimzi.io/ca-cert-generation=0` to `strimzi.io/ca-cert-generation=1`.

When Strimzi generates certificates, the certificate generation annotation is automatically incremented by the Cluster Operator.
For manual renewal of your own CA certificates, set the annotation with a higher incremental value.
The annotation needs a value higher than the ones from the current Secret so the Cluster Operator can roll the pods and update the certificates.
The `strimzi.io/ca-cert-generation` has to be incremented on each CA certificate renewal.
+

.. Save changes and exit.
+
Following the previous example of the `Secret` related to the cluster CA certificate for a Kafka cluster named `my-cluster` with the new CA certificate, and the bumped generation.
+
[source,yaml,subs=attributes+]
----
apiVersion: v1
kind: Secret
data:
  ca.crt: GCa6LS3RTHeKFiFDGBOUDYFAZ0F... <1>
  ca-2022-01-26T17-32-00Z.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0F... <2>
metadata:
  annotations:
    strimzi.io/ca-cert-generation: "1" <3>
  labels:
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
  name: my-cluster-cluster-ca-cert
  #...
type: Opaque
----
<1> The new CA certificate base64 encoded
<2> The old CA certificate base64 encoded
<3> The new CA certificate generation
+
Save the changes to the `Secret` and exit.

. Update the corresponding `Secret` with the new CA key and generation.
+
.. Edit the existing `Secret`:
+
[source,shell,subs="+quotes"]
kubectl edit secret _CA-KEY-SECRET_
+
_CA-KEY-SECRET_ is the name of CA key, which is `_KAFKA-CLUSTER-NAME_-cluster-ca` for the cluster CA key and `_KAFKA-CLUSTER-NAME_-clients-ca` for the clients CA key.
+
Following an example of the `Secret` related to the cluster key CA for a Kafka cluster named `my-cluster`.
+
[source,yaml,subs=attributes+]
----
apiVersion: v1
kind: Secret
data:
  ca.key: SA1cKF1GFDzOIiPOIUQBHDNFGDFS... <1>
metadata:
  annotations:
    strimzi.io/ca-key-generation: "0" <2>
  labels:
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
  name: my-cluster-cluster-ca
  #...
type: Opaque
----
<1> Current CA key base64 encoded
<2> Current CA key generation

.. Encode the new CA key used to sign the new CA certificate into base64.
+
[source,shell,subs="+quotes"]
cat _PATH-TO-NEW-KEY_ | base64

.. Update the CA key.
+
Copy the new CA key base64 encoded got from the first step into the `ca.key` field of the `data` section in the `Secret`.
+
.. Increase the CA key generation.
+
Updated the `strimzi.io/ca-key-generation` annotation with a higher incremental value.
For example, change `strimzi.io/ca-key-generation=0` to `strimzi.io/ca-key-generation=1`.

When Strimzi generates certificates, the key generation annotation is automatically incremented by the Cluster Operator.
For manual renewal of your own CA certificates together with a new CA key, set the annotation with a higher incremental value.
The annotation needs a value higher than the ones from the current Secret so the Cluster Operator can roll the pods and update the certificates and keys.
The `strimzi.io/ca-key-generation` has to be incremented on each CA certificate renewal.
+

. Save changes and exit.
+
Following the previous example of the `Secret` related to the cluster CA key for a Kafka cluster named `my-cluster` with the new CA key, and the bumped generation.
+
[source,yaml,subs=attributes+]
----
apiVersion: v1
kind: Secret
data:
  ca.key: AB0cKF1GFDzOIiPOIUQWERZJQ0F... <1>
metadata:
  annotations:
    strimzi.io/ca-key-generation: "1" <2>
  labels:
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
  name: my-cluster-cluster-ca
  #...
type: Opaque
----
<1> The new CA key base64 encoded
<2> The new CA key generation
+
Save the changes to the `Secret` and exit.

. Resuming from pause
+
To resume the `Kafka` custom resource reconciliation, you can set the `pause-reconciliation` annotation to `false`.
+
[source,shell,subs="+quotes"]
----
kubectl annotate Kafka _NAME-OF-CUSTOM-RESOURCE_ strimzi.io/pause-reconciliation="false"
----
+
You can also do the same by removing the `pause-reconciliation` annotation.
+
[source,shell,subs="+quotes"]
----
kubectl annotate Kafka _NAME-OF-CUSTOM-RESOURCE_ strimzi.io/pause-reconciliation-
----

At the next reconciliation the Cluster Operator will start rolling ZooKeeper, Kafka and the other components to trust the new CA certificate.
When the previous rolling is complete, the Cluster Operator will start a new one for generating new server certificates signed by the new CA key.

If maintenance time windows are configured, the Cluster Operator will roll the pods at the first reconciliation within the next maintenance time window.