// Module included in the following assemblies:
//
// assembly-security.adoc

[id='configuring-internal-clients-to-trust-cluster-ca-{context}']
= Configuring internal clients to trust the cluster CA

This procedure describes how to configure a Kafka client that resides inside the Kubernetes cluster — connecting to the `tls` listener on port 9093 — to trust the cluster CA certificate.

The easiest way to achieve this for an internal client is to use a volume mount to access the `Secrets` containing the necessary certificates and keys.

Follow the steps to configure trust certificates signed by the cluster CA for Java-based Kafka Producer, Consumer, and Streams APIs.

Choose the steps according to the certificate format for the cluster CA: PKCS#12 (`.p12`) or PEM (`.crt`).

.Prerequisites

* The Cluster Operator is running.
* A `Kafka` resource within the Kubernetes cluster.
* A Kafka client application inside the Kubernetes cluster which will connect using TLS and needs to trust the cluster CA certificate.

.Using PKCS #12 format (.p12)

. Mount the cluster Secret as a volume when defining the client pod.
+
For example:
+
[source,shell,subs="+quotes,attributes"]
----
kind: Pod
apiVersion: {API_Version}
metadata:
  name: client-pod
spec:
  containers:
  - name: client-name
    image: client-name
    volumeMounts:
    - name: secret-volume
      mountPath: /data/p12
  volumes:
  - name: secret-config
    secret:
      secretName: my-cluster-cluster-cert
----

. Configure the Kafka client with the following properties:
+
* Security protocol option:
** `security.protocol: SSL` when using TLS for encryption (with or without TLS authentication)
** `security.protocol: SASL_SSL` when using SCRAM-SHA authentication over TLS.
* `ssl.truststore.location`: the truststore location where the certificates were imported.
* `ssl.truststore.password`: the password for accessing the truststore. This property can be omitted if it is not needed by the truststore.

.Using PEM format (.crt)

. Mount the cluster Secret as a volume when defining the client pod.
+
For example:
+
[source,shell,subs="+quotes,attributes"]
----
kind: Pod
apiVersion: {API_Version}
metadata:
  name: client-pod
spec:
  containers:
  - name: client-name
    image: client-name
    volumeMounts:
    - name: secret-volume
      mountPath: /data/crt
  volumes:
  - name: secret-config
    secret:
      secretName: my-cluster-cluster-cert
----

. Import the CA certificate into the JVM’s truststore using the following `keytool` command:
+
[source,shell]
keytool -keystore client.truststore.jks -alias CARoot -import -file ca.crt

. Configure the Kafka client with the following properties:
+
* Security protocol option:
** `security.protocol: SSL` when using TLS for encryption (with or without TLS authentication)
** `security.protocol: SASL_SSL` when using SCRAM-SHA authentication over TLS.
* `ssl.truststore.location`: the truststore location where the certificates were imported.
* `ssl.truststore.password`: the password for accessing the truststore. This property can be omitted if it is not needed by the truststore.
