// Module included in the following assemblies:
//
// assembly-security.adoc

[id='renewing-your-own-ca-certificates-{context}']
= Renewing your own CA certificates

This procedure describes how to renew CA certificates you installed yourself, instead of using the certificates generated by the Cluster Operator.
Follow this procedure when you are not changing the corresponding CA keys.

If you are using your own certificates, the Cluster Operator will not renew them automatically.
Therefore, it is important that you follow this procedure during the renewal period of the certificate in order to replace CA certificates that will soon expire.

The procedure describes the renewal of CA certificates in PEM format.

.Prerequisites

* The Cluster Operator is running.
* xref:installing-your-own-ca-certificates-{context}[Your own CA certificates and private keys are installed].
* You have new cluster or clients X.509 certificates in PEM format.

.Procedure

. Update the corresponding `Secret` with the new CA certificate and generation.
+
.. Edit the existing `Secret`:
+
[source,shell,subs="+quotes"]
kubectl edit secret _CA-CERTIFICATE-SECRET_
+
_CA-CERTIFICATE-SECRET_ is the name of the `Secret`, which is `_KAFKA-CLUSTER-NAME_-cluster-ca-cert` for the cluster CA certificate and `_KAFKA-CLUSTER-NAME_-clients-ca-cert` for the clients CA certificate.
+
Following an example of the `Secret` related to the cluster CA certificate for a Kafka cluster named `my-cluster`.
+
[source,yaml,subs=attributes+]
----
apiVersion: v1
kind: Secret
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0F... <1>
metadata:
  annotations:
    strimzi.io/ca-cert-generation: "0" <2>
  labels:
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
  name: my-cluster-cluster-ca-cert
  #...
type: Opaque
----
<1> Current CA certificate base64 encoded
<2> Current CA certificate generation

.. Encode your new CA certificate into base64.
+
[source,shell,subs="+quotes"]
cat _PATH-TO-NEW-CERTIFICATE_ | base64

.. Update the CA certificate.
+
Copy the new CA certificate base64 encoded got from the previous step into the `ca.crt` field of the `data` section in the `Secret`.
+
.. Increase the CA certificate generation.
+
Update the `strimzi.io/ca-cert-generation` annotation with a higher incremental value.
For example, change `strimzi.io/ca-cert-generation=0` to `strimzi.io/ca-cert-generation=1`.
+

. Save changes and exit.
+
Following the previous example of the `Secret` related to the cluster CA certificate for a Kafka cluster named `my-cluster` with the new CA certificate, and the bumped generation.
+
[source,yaml,subs=attributes+]
----
apiVersion: v1
kind: Secret
data:
  ca.crt: GCa6LS3RTHeKFiFDGBOUDYFAZ0F... <1>
metadata:
  annotations:
    strimzi.io/ca-cert-generation: "1" <2>
  labels:
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
  name: my-cluster-cluster-ca-cert
  #...
type: Opaque
----
<1> The new CA certificate base64 encoded
<2> The new CA certificate generation
+
Save the changes to the `Secret` and exit.

When Strimzi generates certificates, the certificate generation annotation is automatically incremented by the Cluster Operator.
For manual renewal of your own CA certificates, set the annotations with a higher incremental value.
The annotations need a value higher than the ones from the current Secret so the Cluster Operator can roll the pods and update the certificates.
The `strimzi.io/ca-cert-generation` has to be incremented on each CA certificate renewal.

At the next reconciliation the Cluster Operator will start rolling ZooKeeper, Kafka and the other components to trust the new CA certificate.

If maintenance time windows are configured, the Cluster Operator will roll the pods at the first reconciliation within the next maintenance time window.