// Module included in the following assemblies:
//
// assembly-using-the-topic-operator.adoc

[id='con-changing-topic-operator-mode-{context}']
= (Preview) Switching between Topic Operator modes

[role="_abstract"]
You can switch between topic management modes when upgrading or downgrading Strimzi, or when using the same version of Strimzi, as long as the mode is supported for that version. 

* To switch from the default bidirectional mode to unidirectional mode, xref:ref-operator-unidirectional-topic-operator-feature-gate-str[enable the `UnidirectionalTopicOperator` feature gate]. 
* To switch from unidirectional mode to bidirectional mode, check whether finalizers are being used to control topic deletion. If `KafkaTopic` resources are using finalizers, ensure that you do one of the following  before making the switch:
** xref:con-removing-topic-finalizers-{context}[Remove all finalizers from topics].
** Disable the finalizers by setting the `STRIMZI_USE_FINALIZERS` environment variable to `false` in the Topic Operator `env` configuration.
+
.Disabling the topic finalizers
[source,shell,subs=+quotes]
----
# ...
env:
  - name: STRIMZI_USE_FINALIZERS
    value: "false"
----
+
Use the same configuration for a Topic Operator running in a Strimzi-managed cluster or as a standalone deployment.  

The Topic Operator does not use finalizers in bidirectional mode.
If they are retained after making the switch from unidirectional mode, you won't be able to delete `KafkaTopic` and related resources. 