// Module included in the following assemblies:
//
// assembly-using-the-topic-operator.adoc

[id='con-changing-topic-operator-mode-{context}']
= Switching between Topic Operator modes

[role="_abstract"]
You can switch between topic management modes when upgrading or downgrading Strimzi, or when using the same version of Strimzi, as long as the mode is supported for that version. 

* To switch from the default unidirectional mode to bidirectional mode you have to:
** Disable the use of finalizers.
+
.Disabling the topic finalizers
[source,shell,subs=+quotes]
----
# ...
env:
  - name: STRIMZI_USE_FINALIZERS
    value: "false"
----
+
** xref:ref-operator-unidirectional-topic-operator-feature-gate-str[Disable the `UnidirectionalTopicOperator` feature gate].

Use the same configuration for a Topic Operator running in a Strimzi-managed cluster or as a standalone deployment.  

The Topic Operator does not use finalizers in bidirectional mode.
If they are retained after making the switch from unidirectional mode, you won't be able to delete `KafkaTopic` and related resources.
