// This assembly is included in the following assemblies:
//
// metrics/assembly_metrics-kafka.adoc

[id='con-metrics-kafka-options-{context}']

= Prometheus metrics configuration

Strimzi provides xref:ref-metrics-config-files-{context}[example configuration files for Grafana].

Grafana dashboards are dependent on Prometheus JMX Exporter relabeling rules, which are defined for:

* Kafka and ZooKeeper as a `Kafka` resource configuration in the example `kafka-metrics.yaml` file
* Kafka Connect as `KafkaConnect` and `KafkaConnectS2I` resources in the example `kafka-connect-metrics.yaml` file

A label is a name-value pair. Relabeling is the process of writing a label dynamically. For example, the value of a label may be derived from the name of a Kafka server and client ID.

NOTE: We show metrics configuration using `kafka-metrics.yaml` in this section, but the process is the same when configuring Kafka Connect using the `kafka-connect-metrics.yaml` file.

.Additional resources

For more information on the use of relabeling, see {PrometheusConfig} in the Prometheus documentation.
