
// This assembly is included in the following assemblies:
//
// metrics/assembly_metrics-prometheus-setup.adoc

[id='ref-metrics-config-files-{context}']

= Example Metrics files

You can find the example metrics configuration files in the `examples/metrics` directory.

[source]
--
metrics
├── grafana-install
│   ├── grafana.yaml <1>
├── grafana-dashboards <2>
│   ├── strimzi-kafka-connect.json
│   ├── strimzi-kafka.json
│   ├── strimzi-zookeeper.json
│   ├── strimzi-kafka-mirror-maker-2.json
│   ├── strimzi-operators.json
│   ├── strimzi-kafka-bridge.json
│   ├── strimzi-cruise-control.json
│   └── strimzi-kafka-exporter.json <3>
├── kafka-connect-metrics.yaml <4>
├── kafka-metrics.yaml <5>
├── kafka-mirror-maker-2-metrics.yaml <6>
├── kafka-bridge-metrics.yaml <7>
├── kafka-cruise-control-metrics.yaml <8>
├── prometheus-additional-properties
│   └── prometheus-additional.yaml <9>
├── prometheus-alertmanager-config
│   └── alert-manager-config.yaml <10>
└── prometheus-install
    ├── alert-manager.yaml <11>
    ├── prometheus-rules.yaml <12>
    ├── prometheus.yaml <13>
    ├── strimzi-pod-monitor.yaml <14>
--
<1> Installation file for the Grafana image
<2> Grafana dashboards
<3> Grafana dashboard specific to xref:assembly-kafka-exporter-{context}[Kafka Exporter]
<4> Metrics configuration that defines Prometheus JMX Exporter relabeling rules for Kafka Connect
<5> Metrics configuration that defines Prometheus JMX Exporter relabeling rules for Kafka and ZooKeeper
<6> Metrics configuration that defines Prometheus JMX Exporter relabeling rules for Kafka Mirror Maker 2.0
<7> Kafka Bridge resource with metrics enabled
<8> Metrics configuration that defines Prometheus JMX Exporter relabeling rules for Cruise Control
<9> Configuration to add roles for service monitoring
<10> Hook definitions for sending notifications through Alertmanager
<11> Resources for deploying and configuring Alertmanager
<12> Alerting rules examples for use with Prometheus Alertmanager (deployed with Prometheus)
<13> Installation file for the Prometheus image
<14> Prometheus job definitions to scrape metrics data from pods
