
// This assembly is included in the following assemblies:
//
// metrics/assembly_metrics-prometheus-setup.adoc

[id='ref-metrics-config-files-{context}']

= Example Metrics files

You can find the example metrics configuration files in the `examples/metrics` directory.

[source]
--
metrics
├── grafana-install
│   ├── grafana.yaml <1>
├── grafana-dashboards <2>
│   ├── strimzi-kafka-connect.json
│   ├── strimzi-kafka.json
│   ├── strimzi-zookeeper.json
│   ├── strimzi-kafka-mirror-maker-2.json
│   ├── strimzi-operators.json
│   └── strimzi-kafka-exporter.json <3>
├── kafka-connect-metrics.yaml <4>
├── kafka-metrics.yaml <5>
├── prometheus-additional-properties
│   └── prometheus-additional.yaml <6>
├── prometheus-alertmanager-config
│   └── alert-manager-config.yaml <7>
└── prometheus-install
    ├── alert-manager.yaml <8>
    ├── prometheus-rules.yaml <9>
    ├── prometheus.yaml <10>
    ├── strimzi-pod-monitor.yaml <11>
    └── strimzi-service-monitor.yaml <12>
--
<1> Installation file for the Grafana image
<2> Grafana dashboards
<3> Grafana dashboard specific to xref:assembly-kafka-exporter-{context}[Kafka Exporter]
<4> Metrics configuration that defines Prometheus JMX Exporter relabeling rules for Kafka Connect
<5> Metrics configuration that defines Prometheus JMX Exporter relabeling rules for Kafka and ZooKeeper
<6> Configuration to add roles for service monitoring
<7> Hook definitions for sending notifications through Alertmanager
<8> Resources for deploying and configuring Alertmanager
<9> Alerting rules examples for use with Prometheus Alertmanager (deployed with Prometheus)
<10> Installation file for the Prometheus image
<11> Prometheus job definitions to scrape metrics data from pods
<12> Prometheus job definitions to scrape metrics data from services
