// Module included in the following assemblies:
//
// assembly-kafka-connect.adoc

[id='con-creating-managing-connectors-{context}']

= Creating and managing connectors

Once you have created a container image for your connector plug-in, you need to create a connector instance in your Kafka Connect cluster. You can then configure, monitor, and manage a running connector instance. For example, you can:

* Check the status of a connector instance
* Increase or decrease the number of tasks
* Restart failed tasks
* Pause a connector instance
* Delete a connector instance

{ProductName} provides two different APIs for creating and managing connectors:

* `KafkaConnector` resources (referred to as `KafkaConnectors`)
* Kafka Connect REST API

NOTE: Currently, `KafkaConnectors` do not support restarting failed tasks or pausing and resuming connectors. You need to use the Kafka Connect REST API to perform those tasks.

.`KafkaConnector` resources

`KafkaConnectors` allow you to create and manage connector instances for Kafka Connect in a Kubernetes-native way, so an HTTP client such as cURL is not required.
Like other Kafka resources, you declare a connector’s desired state in a `KafkaConnector` YAML file that is deployed to your Kubernetes cluster to create the connector instance. 

You manage a running connector instance by updating its corresponding `KafkaConnector`, and then applying the updates (for example, using `kubectl apply`). You remove a connector by deleting its corresponding `KafkaConnector`.

To ensure compatibility with earlier versions of {ProductName}, `KafkaConnectors` are disabled by default. To enable them for a Kafka Connect cluster, you must configure the `KafkaConnect` custom resource to use `KafkaConnectors` for the creation and management of connectors. For instructions, see xref:proc-enabling-kafkaconnectors-deployment-configuration-kafka-connect[].

When `KafkaConnectors` are enabled, the Cluster Operator begins to watch for them. Like other Kafka resources, the Cluster Operator updates the configurations of running connector instances to match the configurations defined in their `KafkaConnectors`.

.Availability of the Kafka Connect REST API

The Kafka Connect REST API is available on port 8083 as the `<connect-cluster-name>-connect-api` service.

If `KafkaConnectors` are enabled, manual changes made directly using the Kafka Connect REST API are reverted by the Cluster Operator. 
