// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration-kafka-bridge.adoc

[id='con-kafka-bridge-logging-{context}']
= Kafka Bridge loggers

Kafka Bridge has its own configurable loggers:

* `log4j.logger.io.strimzi.kafka.bridge`
* `log4j.logger.http.openapi.operation.__<operation-id>__`

The `log4j.logger.http.openapi.operation.__<operation-id>__` logger is for each OpenAPI operation, where `_<operation-id>_` is the identifier of a specific operation.

Here are the operations defined by the OpenAPI specification:

* `createConsumer`
* `deleteConsumer`
* `subscribe`
* `unsubscribe`
* `poll`
* `assign`
* `commit`
* `send`
* `sendToPartition`
* `seekToBeginning`
* `seekToEnd`
* `seek`
* `healthy`
* `ready`
* `openapi`

Kafka Bridge uses the Apache `log4j` logger implementation.

Use the `logging` property to configure loggers and logger levels.

You can set the log levels by specifying the logger and level directly (inline) or use a custom (external) ConfigMap.
If a ConfigMap is used, you set `logging.name` property to the name of the ConfigMap containing the external logging configuration. Inside the ConfigMap, the logging configuration is described using `log4j.properties`.

Here we see examples of `inline` and `external` logging.

.Inline logging
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: {KafkaApiVersion}
kind: KafkaBridge
spec:
  # ...
  logging:
    type: inline
    loggers:
      log4j.logger.io.strimzi.kafka.bridge: "INFO"
  # ...
----

.External logging
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: {KafkaApiVersion}
kind: KafkaBridge
spec:
  # ...
  logging:
    type: external
    name: customConfigMap
  # ...
----

.Additional resources

* Garbage collector (GC) logging can also be enabled (or disabled). For more information about GC logging, see xref:ref-jvm-options-deployment-configuration-kafka[]
* For more information about log levels, see {ApacheLoggers}.
