// Module included in the following assemblies:
//
// getting-started.adoc

[id='downloads-{context}']
= Installing Strimzi and deploying components

ifdef::Downloading[]
To install Strimzi, download the release artefacts from {ReleaseDownload}.
endif::Downloading[]

ifndef::Downloading[]
To install Strimzi, download and extract the `amq-streams-x.y.z-ocp-install-examples.zip` file from the {ZipDownload}.
endif::Downloading[]

The folder contains several YAML files to help you deploy the components of Strimzi to Kubernetes, perform common operations, and configure your Kafka cluster. The YAML files are referenced throughout this documentation.

ifdef::Downloading[]
Additionally, a Helm Chart is provided for deploying the Cluster Operator using link:https://helm.sh/[Helm^]. The container images are available through the {DockerRepository}.
endif::Downloading[]

The remainder of this chapter provides an overview of each component and instructions for deploying the components to Kubernetes using the YAML files provided.

NOTE: Although container images for Strimzi are available in the {DockerRepository}, we recommend that you use the YAML files provided instead.
