// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration-kafka-mirror-maker.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='con-kafka-mirror-maker-bootstrap-servers-{context}']

= Bootstrap servers

Use the `consumer.bootstrapServers` and `producer.bootstrapServers` properties to configure lists of bootstrap servers for the consumer and producer.

Kafka MirrorMaker always works together with two Kafka clusters (source and target).
The source and the target Kafka clusters are specified in the form of two lists of comma-separated list of `_<hostname>_:‍_<port>_` pairs.
Each comma-separated list contains one or more Kafka brokers or a `Service` pointing to Kafka brokers specified as a `<hostname>:<port>` pairs.

The bootstrap server lists can refer to Kafka clusters that do not need to be deployed in the same Kubernetes cluster.
They can even refer to a Kafka cluster not deployed by {ProductName}, or deployed by {ProductName} but on a different Kubernetes cluster accessible outside.

If on the same Kubernetes cluster, each list must ideally contain the Kafka cluster bootstrap service which is named `_<cluster-name>_-kafka-bootstrap` and a port of 9092 for plain traffic or 9093 for encrypted traffic.
If deployed by {ProductName} but on different Kubernetes clusters, the list content depends on the approach used for exposing the clusters (routes, nodeports or loadbalancers).

When using Kafka MirrorMaker with a Kafka cluster not managed by {ProductName}, you can specify the bootstrap servers list according to the configuration of the given cluster.
