// This assembly is included in the following assemblies:
//
// assembly-kafka-connect-external-configuration.adoc

[id='con-kafka-connect-external-configuration-{context}']

= Storing connector configurations externally

You can mount ConfigMaps or Secrets into a Kafka Connect pod as volumes or environment variables.
Volumes and environment variables are configured in the `externalConfiguration` property in `KafkaConnect.spec` and `KafkaConnectS2I.spec`.

== External configuration as environment variables

The `env` property is used to specify one or more environment variables.
These variables can contain a value from either a ConfigMap or a Secret.

NOTE: The names of user-defined environment variables cannot start with `KAFKA_` or `STRIMZI_`.

To mount a value from a Secret to an environment variable, use the `valueFrom` property and the `secretKeyRef` as shown in the following example.

.Example of an environment variable set to a value from a Secret
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaApiVersion}
kind: KafkaConnect
metadata:
  name: my-connect
spec:
  # ...
  externalConfiguration:
    env:
      - name: MY_ENVIRONMENT_VARIABLE
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: my-key
----

A common use case for mounting Secrets to environment variables is when your connector needs to communicate with Amazon AWS and needs to read the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables with credentials.

To mount a value from a ConfigMap to an environment variable, use `configMapKeyRef` in the `valueFrom` property as shown in the following example.

.Example of an environment variable set to a value from a ConfigMap
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaApiVersion}
kind: KafkaConnect
metadata:
  name: my-connect
spec:
  # ...
  externalConfiguration:
    env:
      - name: MY_ENVIRONMENT_VARIABLE
        valueFrom:
          configMapKeyRef:
            name: my-config-map
            key: my-key
----

== External configuration as volumes

You can also mount ConfigMaps or Secrets to a Kafka Connect pod as volumes.
Using volumes instead of environment variables is useful in the following scenarios:

* Mounting truststores or keystores with TLS certificates
* Mounting a properties file that is used to configure Kafka Connect connectors

In the `volumes` property of the `externalConfiguration` resource, list the ConfigMaps or Secrets that will be mounted as volumes.
Each volume must specify a name in the `name` property and a reference to ConfigMap or Secret.

.Example of volumes with external configuration
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaApiVersion}
kind: KafkaConnect
metadata:
  name: my-connect
spec:
  # ...
  externalConfiguration:
    volumes:
      - name: connector1
        configMap:
          name: connector1-configuration
      - name: connector1-certificates
        secret:
          secretName: connector1-certificates
----

The volumes will be mounted inside the Kafka Connect containers in the path `/opt/kafka/external-configuration/_<volume-name>_`.
For example, the files from a volume named `connector1` would appear in the directory `/opt/kafka/external-configuration/connector1`.

The `FileConfigProvider` has to be used to read the values from the mounted properties files in connector configurations.