// This assembly is included in the following assemblies:
//
// assembly-customizing-deployments.adoc

[id='con-customizing-pod-disruption-budgets-{context}']
= Customizing Pod Disruption Budgets

{ProductName} creates a pod disruption budget for every new `StatefulSet` or `Deployment`.
By default, these pod disruption budgets only allow a single pod to be unavailable at a given time by setting the `maxUnavailable` value in the `PodDisruptionBudget.spec` resource to 1.
You can change the amount of unavailable pods allowed by changing the default value of `maxUnavailable` in the pod disruption budget template.
This template applies to each type of cluster (Kafka and ZooKeeper; Kafka Connect and Kafka Connect with S2I support; and Kafka MirrorMaker).

The following example shows customized `podDisruptionBudget` fields on a `template` property:

[source,yaml,subs=attributes+]
----
# ...
template:
    podDisruptionBudget:
        metadata:
            labels:
                key1: label1
                key2: label2
            annotations:
                key1: label1
                key2: label2
        maxUnavailable: 1
# ...
----

.Additional resources

* For more information, see xref:type-PodDisruptionBudgetTemplate-reference[].
* The {K8sPodDisruptionBudgets} chapter of the Kubernetes documentation.