// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration-kafka-connect.adoc

[id='con-kafka-connect-logging-{context}']
= Kafka Connect loggers

Kafka Connect has its own configurable loggers:

* `connect.root.logger.level`
* `log4j.logger.org.apache.zookeeper`
* `log4j.logger.org.I0Itec.zkclient`
* `log4j.logger.org.reflections`

Kafka Connect uses the Apache `log4j` logger implementation.

Use the `logging` property to configure loggers and logger levels.

You can set the log levels by specifying the logger and level directly (inline) or use a custom (external) ConfigMap.
If a ConfigMap is used, it must be placed under under the `log4j.properties` key.

Here we see examples of `inline` and `external` logging.

.Inline logging
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: {KafkaApiVersion}
kind: KafkaConnect
spec:
  # ...
  logging:
    type: inline
    loggers:
      connect.root.logger: "INFO"
  # ...
----

.External logging
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: {KafkaApiVersion}
kind: KafkaConnect
spec:
  # ...
  logging:
    type: external
    name: customConfigMap
  # ...
----

.Additional resources

* Garbage collector (GC) logging can also be enabled (or disabled). For more information on GC, see xref:ref-jvm-options-deployment-configuration-kafka[]
* For more information about log levels, see {ApacheLoggers}.
