// This assembly is included in the following assemblies:
//
// assembly-customizing-deployments.adoc

[id='con-customizing-external-services-{context}']
= Customizing external Services

When exposing Kafka to the outside of Kubernetes using load balancers or node prots, you can in addition to Labels and Annotations customize some more fields .
These fields are described in the following table and affect how the Service is created.

[table,stripes=none]
|===
|Field |Description

|`externalTrafficPolicy`
|Denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints.
`Cluster` may cause a second hop to another node and obscures the client source IP.
`Local` avoids a second hop for LoadBalancer and Nodeport type services and preserves the client source IP (when supported by the infrastructure).
When not specified, Kubernetes will use `Cluster` as default.

|`loadBalancerSourceRanges`
|A list of CIDR ranges (for example `10.0.0.0/8` or `130.211.204.1/32`) from which clients will be able to connect to load balancer type listeners.
If supported by the platform, this will restrict traffic through the load balancer to the specified CIDR ranges in this list.
This field is applicable only for load balancer type services and will be ignored if the cloud-provider does not support the feature.

For more info see link:https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/[Configure Your Cloud Provider's Firewalls].
|===

These fields are available on the `externalBootstrapService` and `perPodService` fields.
The following example shows these customized fields on a `template` property:

[source,yaml,subs=attributes+]
----
# ...
template:
  externalBootstrapService:
    externalTrafficPolicy: Local
    loadBalancerSourceRanges:
      - 10.0.0.0/8
      - 88.208.76.87/32
  perPodService:
    externalTrafficPolicy: Local
    loadBalancerSourceRanges:
      - 10.0.0.0/8
      - 88.208.76.87/32
# ...
----

.Additional resources

* For more information, see xref:type-ExternalServiceTemplate-reference[].
