// Module included in the following assemblies:
//
// assembly-configuring-kafka-listeners.adoc

[id='proc-accessing-kafka-using-loadbalancers-{context}']
= Accessing Kafka using loadbalancers

This procedure describes how to access a Strimzi Kafka cluster from an external client using loadbalancers.

To connect to a broker, you need a hostname (advertised address) for the loadbalancer _bootstrap address_,
as well as the certificate used for authentication.

The port used to connect is always 9094.

.Prerequisites

* A Kubernetes cluster
* A running Cluster Operator

.Procedure

. Configure a `Kafka` resource with an external listener enabled and configured to the `loadbalancer` type.
+
For example:
+
[source,yaml,subs=attributes+]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
spec:
  kafka:
    # ...
    listeners:
      external:
        type: loadbalancer
        authentication:
          type: tls
        # ...
    # ...
  zookeeper:
    # ...
----

. Create or update the resource.
+
[source,shell,subs=+quotes]
kubectl apply -f _KAFKA-CONFIG-FILE_
+
`loadbalancer` type services and loadbalancers are created for each Kafka broker, as well as an external _bootstrap service_.
The bootstrap service routes external traffic to the Kafka brokers.
DNS names and IP addresses used for connection are propagated to the `status` of each service.

. Retrieve the address of the bootstrap service to access the Kafka cluster.
+
[source,shell,subs=+quotes]
kubectl get service _KAFKA-CLUSTER-NAME_-kafka-external-bootstrap -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}{"\n"}'
+
You need the address of the loadbalancer bootstrap service (`_KAFKA-CLUSTER-NAME_-kafka-external-bootstrap`).
+
If a hostname is not found, use the loadbalancer IP address.
+
[source,shell,subs=+quotes]
kubectl get service _KAFKA-CLUSTER-NAME_-kafka-external-bootstrap -o=jsonpath='{.status.loadBalancer.ingress[0].ip}{"\n"}'
+
Use the loadbalancer service address and port 9094 (_LOADBALANCER-ADDRESS:9094_) in your Kafka client as the _bootstrap address_ to connect to the Kafka cluster.

. If TLS encryption is enabled, extract the public certificate of the broker certification authority.
+
[source,shell,subs=+quotes]
kubectl get secret _KAFKA-CLUSTER-NAME_-cluster-ca-cert -o jsonpath='{.data.ca\.crt}' | base64 -d > ca.crt
+
Use the extracted certificate in your Kafka client to configure TLS connection.
If you enabled any authentication, you will also need to configure SASL or TLS authentication.

.Additional resources
* For more information about the schema, see xref:type-KafkaListeners-reference[`KafkaListeners` schema reference].
