// Module included in the following assemblies:
//
// assembly-kafka-connect-authentication.adoc

[id='proc-configuring-kafka-connect-authentication-scram-sha-512-{context}']
= Configuring SCRAM-SHA-512 authentication in Kafka Connect

.Prerequisites

* A Kubernetes cluster
* A running Cluster Operator
* Username of the user which should be used for authentication
* If they exist, the name of the `Secret` with the password used for authentication and the key under which the password is stored in the `Secret`

.Procedure

. (Optional) If they do not already exist, prepare a file with the password used in authentication and create the `Secret`.
+
NOTE: Secrets created by the User Operator may be used.
+
This can be done using `kubectl create`:
[source,shell,subs=+quotes]
echo -n '_PASSWORD_' > _MY-PASSWORD.txt_
kubectl create secret generic _MY-SECRET_ --from-file=_MY-PASSWORD.txt_

. Edit the `authentication` property in the `KafkaConnect` or `KafkaConnectS2I` resource.
For example:
+
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: {KafkaApiVersion}
kind: KafkaConnect
metadata:
  name: my-connect
spec:
  # ...
  authentication:
    type: scram-sha-512
    username: _MY-USERNAME_
    passwordSecret:
      secretName: _MY-SECRET_
      password: _MY-PASSWORD.txt_
  # ...
----
+
. Create or update the resource.
+
On Kubernetes this can be done using `kubectl apply`:
[source,shell,subs=+quotes]
kubectl apply -f _your-file_
