// Module included in the following assemblies:
//
// assembly-kafka-bridge-quickstart.adoc

[id='proc-deploying-kafka-bridge-quickstart-{context}']
= Deploying the Kafka Bridge to your Kubernetes cluster

Strimzi includes a YAML example that specifies the configuration of the Strimzi Kafka Bridge. Make some minimal changes to this file and then deploy an instance of the Kafka Bridge to your Kubernetes cluster.

.Procedure

. Edit the `examples/bridge/kafka-bridge.yaml` file.
+
[source,yaml,subs=attributes+]
----
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaBridge
metadata:
  name: quickstart <1>
spec:
  replicas: 1
  bootstrapServers: <cluster-name>-kafka-bootstrap:9092 <2>
  http:
    port: 8080
----
<1> When the Kafka Bridge is deployed, `-bridge` is appended to the name of the deployment and other related resources. In this example, the Kafka Bridge deployment is named `quickstart-bridge` and the accompanying Kafka Bridge service is named `quickstart-bridge-service`.
+
<2> In the `bootstrapServers` property, enter the name of the Kafka cluster as the `<cluster-name>`.

. Deploy the Kafka Bridge to your Kubernetes cluster:
+
[source,shell,subs="attributes+"]
----
kubectl apply -f examples/bridge/kafka-bridge.yaml
----
+
A `quickstart-bridge` deployment, service, and other related resources are created in your Kubernetes cluster.

. Verify that the Kafka Bridge was successfully deployed:
+
[source,shell,subs="attributes+"]
----
kubectl get deployments
----
+
[source,shell,subs="attributes+"]
----
NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
quickstart-bridge                  1/1     1            1          34m
my-cluster-connect                 1/1     1            1          24h
my-cluster-entity-operator         1/1     1            1          24h
#...
----

.What to do next

After deploying the Kafka Bridge to your Kubernetes cluster, xref:proc-exposing-kafka-bridge-service-local-machine-{context}[expose the Kafka Bridge service to your local machine].

.Additional resources

* For more detailed information about configuring the Kafka Bridge, see xref:assembly-deployment-configuration-kafka-bridge-str[].
