// Module included in the following assemblies:
//
// assembly-kafka-connect-authentication.adoc

[id='proc-configuring-kafka-connect-authentication-scram-sha-512-{context}']
= Configuring SCRAM-SHA-512 authentication in Kafka Connect

You can configure Kafka Connect to connect to Kafka brokers using SASL-based authentication using the SCRAM-SHA-512 mechanism.

This procedure includes creating a Secret from a text file. The Secret will contain the password used for authentication in one of its fields. Secrets created by the User Operator can also be used.

.Prerequisites

* A Kubernetes cluster
* A running Cluster Operator
* Username of the user for authentication

.Procedure

. Create a text file that contains the password, in cleartext, to use for authentication:
+
[source,shell,subs="+quotes"]
----
echo -n _PASSWORD_ > _MY-CONNECT-PASSWORD_.txt
----

. Create the Secret from the file, setting your own field name (key) for the password:
+
[source,shell,subs="+quotes"]
----
kubectl create secret generic _MY-CONNECT-SECRET_ --from-file=_PASSWORD-FIELD-NAME_=./_MY-CONNECT-PASSWORD_.txt
----

. Edit the `authentication` property in the `KafkaConnect` or `KafkaConnectS2I` custom resource.
For example:
+
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: {KafkaApiVersion}
kind: KafkaConnect
metadata:
  name: my-connect
spec:
  # ...
  authentication:
    type: scram-sha-512
    username: _MY-CONNECT-USERNAME_
    passwordSecret:
      secretName: _MY-CONNECT-SECRET-NAME_
      password: _PASSWORD-FIELD-NAME_
  # ...
----
+
[WARNING]
====
Do NOT specify the actual password in the `passwordSecret.password` property.
====

. Create or update the resource:
+
[source,shell,subs=+quotes]
----
kubectl apply -f _YOUR-FILE_
----
