// Module included in the following assemblies:
//
// assembly-configuring-kafka-listeners.adoc

[id='proc-accessing-kafka-using-routes-{context}']
= Accessing Kafka using OpenShift routes

This procedure describes how to access a Strimzi Kafka cluster from an external client outside of OpenShift using routes.

To connect to a broker, you need a hostname for the route _bootstrap address_,
as well as the certificate used for TLS encryption.

For access using routes, the port is always 443.

.Prerequisites

* An OpenShift cluster
* A running Cluster Operator

.Procedure

. Configure a `Kafka` resource with an external listener set to the `route` type.
+
For example:
+
[source,yaml,subs=attributes+]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
spec:
  kafka:
    # ...
    listeners:
      external:
        type: route
        # ...
    # ...
  zookeeper:
    # ...
----

. Create or update the resource.
+
[source,shell,subs=+quotes]
kubectl apply -f _KAFKA-CONFIG-FILE_
+
`ClusterIP` type services are created for each Kafka broker, as well as an external _bootstrap service_.
The services route the traffic from the OpenShift Routes to the Kafka brokers.
An OpenShift `Route` resource is also created for each service to expose them using the HAProxy load balancer.
DNS addresses used for connection are propagated to the `status` of each service.
+
The cluster CA certificate to verify the identity of the kafka brokers is also created with the same name as the `Kafka` resource.

. Retrieve the address of the bootstrap service you can use to access the Kafka cluster from the status of the `Kafka` resource.
+
[source,shell,subs=+quotes]
kubectl get kafka _KAFKA-CLUSTER-NAME_ -o=jsonpath='{.status.listeners[?(@.type=="external")].bootstrapServers}{"\n"}'

. Extract the public certificate of the broker certification authority.
+
[source,shell,subs=+quotes]
kubectl get secret _KAFKA-CLUSTER-NAME_-cluster-ca-cert -o jsonpath='{.data.ca\.crt}' | base64 -d > ca.crt
+
Use the extracted certificate in your Kafka client to configure TLS connection.
If you enabled any authentication, you will also need to configure SASL or TLS authentication.
