// Module included in the following assemblies:
//
// assembly-using-the-user-operator.adoc

[id='ref-kafka-user-{context}']
= Kafka User resource

The `KafkaUser` resource is used to configure the authentication mechanism, authorization mechanism, and access rights for a user.

The full schema for `KafkaUser` is described in xref:type-KafkaUser-reference[`KafkaUser` schema reference].

== Authentication

Authentication is configured using the `authentication` property in `KafkaUser.spec`.
The authentication mechanism enabled for this user is specified using the `type` field.
Currently, the only supported authentication mechanisms are the TLS Client Authentication mechanism and the SCRAM-SHA-512 mechanism.

When no authentication mechanism is specified, User Operator will not create the user or its credentials.

.Additional resources

* xref:con-mutual-tls-authentication-{context}[Mutual TLS Authentication]
* xref:con-scram-sha-authentication-{context}[SCRAM-SHA Authentication]

=== TLS Client Authentication

To use TLS client authentication, set the `type` field to `tls`.

.An example of `KafkaUser` with enabled TLS client authentication
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaUserApiVersion}
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  # ...
----

When the user is created by the User Operator, it will create a new secret with the same name as the `KafkaUser` resource.
The secret will contain a public and private key which should be used for the TLS Client Authentication.
Bundled with them will be the public key of the client certification authority which was used to sign the user certificate.
All keys will be in X509 format.

.An example of the `Secret` with user credentials
[source,yaml,subs="attributes+"]
----
apiVersion: v1
kind: Secret
metadata:
  name: my-user
  labels:
    strimzi.io/kind: KafkaUser
    strimzi.io/cluster: my-cluster
type: Opaque
data:
  ca.crt: # Public key of the Clients CA
  user.crt: # Public key of the user
  user.key: # Private key of the user
----

=== SCRAM-SHA-512 Authentication

To use SCRAM-SHA-512 authentication mechanism, set the `type` field to `scram-sha-512`.

.An example of `KafkaUser` with enabled SCRAM-SHA-512 authentication
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaUserApiVersion}
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  # ...
----

When the user is created by the User Operator, the User Operator will create a new secret with the same name as the `KafkaUser` resource.
The secret contains the generated password in the `password` key, which is encoded with base64. In order to use the password it must be decoded.

.An example of the `Secret` with user credentials
[source,yaml,subs="attributes+"]
----
apiVersion: v1
kind: Secret
metadata:
  name: my-user
  labels:
    strimzi.io/kind: KafkaUser
    strimzi.io/cluster: my-cluster
type: Opaque
data:
  password: Z2VuZXJhdGVkcGFzc3dvcmQ= # Generated password
----

For decode the generated password:
----
echo "Z2VuZXJhdGVkcGFzc3dvcmQ=" | base64 --decode
----

[id='simple-acl-{context}']
== Authorization

Simple authorization is configured using the `authorization` property in `KafkaUser.spec`.
The authorization type enabled for a user is specified using the `type` field.

If no authorization is specified, the User Operator does not provision any access rights for the user.

Additionally, if you are using {oauth} token based authentication, you can also xref:assembly-oauth-authorization_str[configure {oauth} authorization].

=== Simple authorization

Simple authorization uses the default Kafka authorization plugin, `SimpleAclAuthorizer`.

To use simple authorization, set the `type` property to `simple` in `KafkaUser.spec`.

.ACL rules

`SimpleAclAuthorizer` uses ACL rules to manage access to Kafka brokers.

ACL rules grant access rights to the user, which you specify in the `acls` property.

An `AclRule` is specified as a set of properties:

`resource`:: The `resource` property specifies the resource that the rule applies to.
+
--
Simple authorization supports four resource types, which are specified in the `type` property:

* Topics (`topic`)
* Consumer Groups (`group`)
* Clusters (`cluster`)
* Transactional IDs (`transactionalId`)
--
+
For Topic, Group, and Transactional ID resources you can specify the name of the resource the rule applies to in the `name` property.
+
Cluster type resources have no name.
+
A name is specified as a `literal` or a `prefix` using the `patternType` property.
+
* Literal names are taken exactly as they are specified in the `name` field.
* Prefix names use the value from the `name` as a prefix, and will apply the rule to all resources with names starting with the value.

`type`::
The `type` property specifies the type of ACL rule, `allow` or `deny`.
+
The `type` field is optional.
If `type` is unspecified, the ACL rule is treated as an `allow` rule.

`operation`:: The `operation` specifies the operation to allow or deny.
+
--
The following operations are supported:

* Read
* Write
* Delete
* Alter
* Describe
* All
* IdempotentWrite
* ClusterAction
* Create
* AlterConfigs
* DescribeConfigs
--
+
Only certain operations work with each resource.
+
For more details about `SimpleAclAuthorizer`, ACLs and supported combinations of resources and operations, see link:http://kafka.apache.org/documentation/#security_authz[Authorization and ACLs^].

`host`:: The `host` property specifies a remote host from which the rule is allowed or denied.
+
Use an asterisk (`\*`) to allow or deny the operation from all hosts.
The `host` field is optional. If `host` is unspecified, the `*` value is used by default.

For more information about the `AclRule` object, see xref:type-AclRule-reference[`AclRule` schema reference].

.An example `KafkaUser` with authorization
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaUserApiVersion}
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  # ...
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Describe
      - resource:
          type: group
          name: my-group
          patternType: prefix
        operation: Read
----

=== Super user access to Kafka brokers

If a user is added to a list of super users in a Kafka broker configuration, the user is allowed unlimited access to the cluster regardless of any authorization constraints defined in ACLs.

For more information on configuring super users, see xref:assembly-kafka-authentication-and-authorization-deployment-configuration-kafka[authentication and authorization] of Kafka brokers.

== User quotas

You can configure the `spec` for the `KafkaUser` resource to enforce quotas so that a user does not exceed access to Kafka brokers based on a byte threshold or a time limit of CPU utilization.

.An example `KafkaUser` with user quotas
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaUserApiVersion}
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  # ...
  quotas:
    producerByteRate: 1048576 <1>
    consumerByteRate: 2097152 <2>
    requestPercentage: 55 <3>
----
<1> Byte-per-second quota on the amount of data the user can push to a Kafka broker
<2> Byte-per-second quota on the amount of data the user can fetch from a Kafka broker
<3> CPU utilization limit as a percentage of time for a client group

For more information on these properties, see xref:type-KafkaUserQuotas-reference[`KafkaUserQuotas` schema reference]
