// Module included in the following assemblies:
//
// assembly-healthchecks.adoc

[id='ref-healthchecks-{context}']
= Healthcheck configurations

Liveness and readiness probes can be configured using the `livenessProbe` and `readinessProbe` properties in following resources:

* `Kafka.spec.kafka`
* `Kafka.spec.zookeeper`
* `Kafka.spec.entityOperator.tlsSidecar`
* `Kafka.spec.entityOperator.topicOperator`
* `Kafka.spec.entityOperator.userOperator`
* `Kafka.spec.KafkaExporter`
* `KafkaConnect.spec`
* `KafkaConnectS2I.spec`
* `KafkaMirrorMaker.spec`
* `KafkaBridge.spec`

Both `livenessProbe` and `readinessProbe` support the following options:

* `initialDelaySeconds`
* `timeoutSeconds`
* `periodSeconds`
* `successThreshold`
* `failureThreshold`

For more information about the `livenessProbe` and `readinessProbe` options, see xref:type-Probe-reference[].

.An example of liveness and readiness probe configuration
[source,yaml,subs="attributes+"]
----
# ...
readinessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5
livenessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5
# ...
----
