#!/bin/bash
set -e

cat <<EOF
This is S2I image for extending the strimzi/kafka-connect image with additional Kafka Connect plugins.
For more information please go to https://github.com/strimzi/strimzi#kafka-connect
EOF