// This assembly is included in the following assemblies:
//
// assembly-operators.adoc

[id='assembly-using-the-user-operator-{context}']
= Using the User Operator

[role="_abstract"]
When you create, modify or delete a user using the `KafkaUser` resource,
the User Operator ensures those changes are reflected in the Kafka cluster.

For more information on the `KafkaUser` resource, see the xref:type-KafkaUser-reference[`KafkaUser` schema reference].

.Deploying the User Operator

You can deploy the User Operator using the Cluster Operator or as a standalone operator.
You would use a standalone User Operator with a Kafka cluster that is not managed by the Cluster Operator.

For deployment instructions, see the following:

* link:{BookURLDeploying}#deploying-the-user-operator-using-the-cluster-operator-{context}[Deploying the User Operator using the Cluster Operator (recommended)^]
* link:{BookURLDeploying}#deploying-the-user-operator-standalone-{context}[Deploying the standalone User Operator^]

[IMPORTANT]
====
To deploy the standalone User Operator, you need to set environment variables to connect to a Kafka cluster.
These environment variables do not need to be set if you are deploying the User Operator using the Cluster Operator as they will be set by the Cluster Operator.
====

.Authenticating and authorizing access to Kafka
Use `KafkaUser` to enable the authentication and authorization mechanisms that a specific client uses to access Kafka.

For more information on using `KafkUser` to manage users and secure access to Kafka brokers, see xref:assembly-securing-kafka-{context}[Securing access to Kafka brokers].

include::../../modules/operators/proc-user-operator-with-resource-requests-limits.adoc[leveloffset=+1]
