{
 "title": "Strimzi Kafka Consumer Groups",
 "tags": [
  "Strimzi",
  "Kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(kafka_server_replicamanager_leadercount)"
    }
   },
   {
    "name": "strimzi_cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "query_result(kafka_server_replicamanager_leadercount{namespace=\"$kubernetes_namespace\"})"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Active Consumer Groups (members>0)",
   "type": "stat",
   "description": "Number of Active Consumer Groups (members>0)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kafka_consumergroup_members {namespace=~\"$kubernetes_namespace\",strimzi_io_cluster=~\"$strimzi_cluster_name\"}>0) by (consumergroup))"
    }
   ]
  },
  {
   "title": "Inactive Consumer Groups (members=0)",
   "type": "stat",
   "description": "Number of Inactive Consumer Groups (members=0)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kafka_consumergroup_members {namespace=~\"$kubernetes_namespace\",strimzi_io_cluster=~\"$strimzi_cluster_name\"}==0) by (consumergroup))"
    }
   ]
  },
  {
   "title": "CG (lag>0+lag=0)",
   "type": "stat",
   "description": "Number of Consumer Groups with topic-partition lag>0+lag=0 ",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count((kafka_consumergroup_lag{namespace=~\"$kubernetes_namespace\",strimzi_io_cluster=~\"$strimzi_cluster_name\"})>0) by (consumergroup))+count(count((kafka_consumergroup_lag{namespace=~\"$kubernetes_namespace\",strimzi_io_cluster=~\"$strimzi_cluster_name\"})==0) by (consumergroup))"
    }
   ]
  },
  {
   "title": "CG (lag>0)",
   "type": "stat",
   "description": "Number of Consumer Groups with lag > 0",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count((kafka_consumergroup_lag{namespace=~\"$kubernetes_namespace\",strimzi_io_cluster=~\"$strimzi_cluster_name\"})>0) by (consumergroup))"
    }
   ]
  },
  {
   "title": "CG (lag=0)",
   "type": "stat",
   "description": "Number of Consumer Groups with lag=0",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count((kafka_consumergroup_lag{namespace=~\"$kubernetes_namespace\",strimzi_io_cluster=~\"$strimzi_cluster_name\"})==0) by (consumergroup))"
    }
   ]
  },
  {
   "title": "Active Consumer Groups (members>0)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count(kafka_consumergroup_members {namespace=~\"$kubernetes_namespace\",strimzi_io_cluster=~\"$strimzi_cluster_name\"}>0) by (consumergroup)",
     "legendFormat": "{{topic}}:{{partition}}"
    }
   ]
  },
  {
   "title": "Topic-Partition Lag of Active Consumer Groups (members>0)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{namespace=~\"$kubernetes_namespace\",strimzi_io_cluster=~\"$strimzi_cluster_name\"} and on (consumergroup) kafka_consumergroup_members {namespace=~\"$kubernetes_namespace\",strimzi_io_cluster=~\"$strimzi_cluster_name\"}>0",
     "legendFormat": "{{topic}}:{{partition}}"
    }
   ]
  },
  {
   "title": "Topic-Partition Lag of Inactive Consumer Groups (members=0)",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{namespace=~\"$kubernetes_namespace\",strimzi_io_cluster=~\"$strimzi_cluster_name\"} and on (consumergroup) kafka_consumergroup_members {namespace=~\"$kubernetes_namespace\",strimzi_io_cluster=~\"$strimzi_cluster_name\"}==0",
     "legendFormat": "{{topic}}:{{partition}}"
    }
   ]
  }
 ]
}