[[files-and-attributes]]
= Files and attributes

== Important files

|===
| Standard attributes         | shared/attributes.adoc
| Shared includes             | shared/
| Images                      | shared/images/
|===

[[anchor-and-file-names]]
== Anchor names and file names

To optimize modular documentation, follow these guidelines for naming module anchors and files:

Anchor names:: Provide an anchor in the format `++[id='anchor-name']++` for every module so that it can be identified by Asciidoctor when reused or cross-referenced. Give the anchor the same or similar name as the module heading, separated by dashes:
+
[source]
----
[id='anchor-name']
= Module Heading

First sentence of topic.
----
+
[NOTE]
.Note on other anchor formats (Not Recommended)
====
The format defined here is recommended because it is the most stable and versatile of anchor formats, and supports variables that enable topics to be reused and cross-referenced properly. Other anchor formats include `\[[anchor-name]]` and `+[#anchor-name]+`, but these formats either do not support variables for content reuse or do not support certain character types, such as periods. These limitations cause errors at build time.
====

File names:: Name the module file using the same name as the anchor used in it, which should also align with or resemble the module heading. Separate these elements with dashes. Add a prefix with an underscore to the file name to indicate the module type in the format `prefix-file-name`. Use `snip-` for a snippet, `con-` for concept, `ref-` for reference, `proc-` for procedure, `assembly-` for assembly, and `image-` for images and screenshots.
+
.Examples
* `snip-guided-decision-urls.adoc`  (Snippet of reusable content)
* `con-guided-decision-tables.adoc`  (Concept module)
* `proc-creating-guided-decision-tables.adoc`  (Procedure module for creating)
* `proc-editing-guided-decision-tables.adoc`  (Procedure module for editing)
* `ref-guided-decision-table-examples.adoc`  (Reference module with examples)
* `ref-guided-decision-table-columns.adoc`  (Reference module with column types)
* `assembly-guided-decision-tables.adoc`  (Assembly of guided decision table modules)
* `image-guided-decision-example.adoc`  (Screenshot or image of guided decision table modules)

Learn more in the link:https://redhat-documentation.github.io/modular-docs/[Modular Documentation Reference Guide^].
