= Introduction

This guide provides information to assist contributors to the Strimzi documentation.

== Dependencies

* asciidoctor
* python

== Project layout

Strimzi uses git to manage repositories.

https://github.com/strimzi/strimzi-kafka-operator[`strimzi-kafka-operator`^] (GitHub):: The public GitHub repo hosts all of the Strimzi code and documentation.
https://github.com/strimzi/strimzi-kafka-operator/tree/master/documentation[`strimzi-kafka-operator/documentation`^] (GitHub):: The _documentation_ folder is split into _category_ folders to manage the content.

Category folders contain files related to Strimzi guides (Deploying, Quickstart, Overview, Using), and the files that provide the content for one or more of these guides – _assemblies_ and _modules_.
Assemblies, which usually encapsulate a feature or process, bring the related content contained in modules together.

[source,options="nowrap",subs="+quotes"]
----
deploying/                           # Deploying and Upgrading guide
quickstart/                          # Quick Start guide
overview/                            # Overview guide
using/                               # User guide
assemblies/                          # Assemblies provide content for all guides
modules/                             # Modules provide the content for assemblies
shared/                              # Shared include files
shared/attributes.adoc               # Global book attributes
shared/images/                       # Shared image files
----

=== Strimzi Overview guide

The intention of the _Strimzi Overview guide_ is for developing an understanding of Strimzi and Apache Kafka.
The guide does not contain any instructions.
It provides an overview of the concepts behind Apache Kafka, the Kafka component architecture, and how Strimzi supports Kafka in a Kubernetes cluster.
The guide also describes how Strimzi _Operators_ help manage a deployment.

The guide contains high-level outlines of the processes required to deploy, configure, secure and monitor a deployment of Strimzi.

=== Deploying Strimzi

The _Deploying Strimzi_ guide provides instructions on all the options available for deploying and upgrading Strimzi.
The guide describes what is deployed, and the order of deployment required.

As well as describing the deployment steps, the guide also provides pre- and post-deployment instructions to prepare for and verify a deployment.
Additional deployment options described include the steps to introduce metrics.

=== Strimzi Quick Start guide

The _Strimzi Quick Start guide_ provides instructions for evaluating Strimzi.
The steps describe how to get a Strimzi deployment up-and-running as quickly as possible.

In contrast to the _Deploying_ guide, this guide provides a reduced set of instructions for a specific type of deployment, with minimal configuration.

=== Using Strimzi

The _Using Strimzi_ guide provides configuration instructions for Kafka components, and instructions for using Strimzi Operators.
The majority of the content relates to how you might want to modify your deployment and introduce additional features, such as cruise control or distributed tracing.
