[[make-tooling]]
= Using make with documentation

When you make changes to the documentation, it is a good practice to do a local test build to verify the book builds successfully and renders as you expect before you submit the merge request back to upstream master.

Make is a useful tool for building your documentation and pushing it to a public website so that peer and quality reviewers can see your edits as the user would.

== Make commands to build documentation

`make docu_clean`:: Delete all temporary files
`make docu_check`:: Execute the documentation checks in `.travis/check_docs.sh`
`make docu_html`:: Generate the HTML version of all the guides (the HTML files can be found in `documentation/html)
`make docu_htmlnoheader`:: Generate the HTML version of all the guides without the HTML headers which are suitable for including into a website (the HTML files can be found in `documentation/htmlnoheader)

== Generate the API Reference

The API Reference is stored in `documentation/modules/appendix_crds.adoc` file.
It is generated directly from the Java code when building the operators.
If you change the Strimzi API, you need to regenerate the API Reference with following command:

[source,shell,subs=attributes+]
----
mvn clean -DskipTests install
----

NOTE: You have to generate the API Reference only if you changed anything in the `api` module of the Java code.
