oc delete -f /Users/morsak/Documents/Work/strimzi-kafka-operator/packaging/install/cluster-operator
oc delete ServiceAccount strimzi-cluster-operator
oc delete ClusterRole strimzi-cluster-operator-namespaced
oc delete ClusterRoleBinding strimzi-cluster-operator-namespaced
oc delete RoleBinding strimzi-cluster-operator
oc delete ClusterRole strimzi-cluster-operator-global
oc delete ClusterRole strimzi-kafka-broker
oc delete ClusterRoleBinding strimzi-cluster-operator-kafka-broker-delegation
oc delete ClusterRole strimzi-entity-operator
oc delete ClusterRoleBinding strimzi-cluster-operator-entity-operator-delegation
oc delete RoleBinding strimzi-cluster-operator-entity-operator-delegation
oc delete ClusterRole strimzi-kafka-client
oc delete ClusterRoleBinding strimzi-cluster-operator-kafka-client-delegation
