// This assembly is included in:
//
// deploying/assembly-deploy-create-cluster.adoc

[id="deploy-standalone-operators_{context}"]
= Alternative standalone deployment options for Strimzi Operators

[role="_abstract"]
As an alternative to deploying the Topic Operator and User Operator with the Cluster Operator, you can perform a standalone deployment.
Consider a standalone deployment of these operators if you are using a Kafka cluster that is not managed by the Cluster Operator.

You deploy the operators to Kubernetes.
Kafka can be running outside of Kubernetes.
For example, you might be using a Kafka as a managed service.
You adjust the deployment configuration for the standalone operator to match the address of your Kafka cluster.

//Procedure for standalone deployment of Topic Operator
include::modules/proc-deploy-topic-operator-standalone.adoc[leveloffset=+1]
//Procedure for standalone deployment of User Operator
include::modules/proc-deploy-user-operator-standalone.adoc[leveloffset=+1]
