// This assembly is included in:
//
// deploying/deploying.adoc

[id="deploy-intro_{context}"]
= Deployment overview

//Standard introduction text for the product
[role="_abstract"]
include::../../shared/snip-intro-text.adoc[leveloffset=+1]

This guide provides instructions for deploying and managing Strimzi.
Deployment options and steps are covered using the example installation files included with Strimzi. 
While the guide highlights important configuration considerations, it does not cover all available options. 
For a deeper understanding of the Kafka component configuration options, refer to the link:{BookURLConfiguring}[Strimzi Custom Resource API Reference^].

In addition to deployment instructions, the guide offers pre- and post-deployment guidance. 
It covers setting up and securing client access to your Kafka cluster. 
Furthermore, it explores additional deployment options such as metrics integration, distributed tracing, and cluster management tools like Cruise Control and the Strimzi Drain Cleaner. 
You'll also find recommendations on managing Strimzi and fine-tuning Kafka configuration for optimal performance.

Upgrade instructions are provided for both Strimzi and Kafka, to help keep your deployment up to date.

Strimzi is designed to be compatible with all types of Kubernetes clusters, irrespective of their distribution. 
Whether your deployment involves public or private clouds, or if you are setting up a local development environment, the instructions in this guide are applicable in all cases.

//Custom resources intro
include::assembly-deploy-intro-custom-resources.adoc[leveloffset=+1]
//operators
include::assembly-deploy-intro-operators.adoc[leveloffset=+1]
//info on kafka bridge
include::../../modules/deploying/con-kafka-bridge-concepts.adoc[leveloffset=+1]
//info on FIPS
include::../../modules/deploying/con-fips-support.adoc[leveloffset=+1]
//formatting conventions used in guide
include::../../shared/ref-document-conventions.adoc[leveloffset=+1]

[role="_additional-resources"]
== Additional resources

* link:{BookURLOverview}[Strimzi Overview^]
* link:{BookURLConfiguring}[Strimzi Custom Resource API Reference^]
* link:{BookURLBridge}[Using the Strimzi Kafka Bridge^]
