// This assembly is included in:
//
// deploying/master.adoc

[id="deploy-tasks_{context}"]
= Deploying Strimzi

Having xref:deploy-tasks-prereqs_{context}[prepared your environment for a deployment of Strimzi], this section shows:

* xref:deploy-create-cluster_{context}[How to create the Kafka cluster]
* Optional procedures to deploy other Kafka components according to your requirements:
** xref:kafka-connect-{context}[Kafka Connect]
** xref:kafka-mirror-maker-{context}[Kafka MirrorMaker]
** xref:kafka-bridge-{context}[Kafka Bridge]

The procedures assume a Kubernetes cluster is available and running.

ifdef::Downloading[]
This section describes the procedures to deploy Strimzi on Kubernetes {KubernetesVersion}.
endif::Downloading[]

ifndef::Downloading[]
Strimzi is based on Strimzi {StrimziVersion}.
This section describes the procedures to deploy Strimzi on OpenShift {OpenShiftVersion}.
endif::Downloading[]

NOTE: To run the commands in this guide, your cluster user must have the rights to manage role-based access control (RBAC) and CRDs.

//Procedures to create Kafka cluster: deploy the Cluster Operator, deploy the Kafka cluster
include::assembly-deploy-create-cluster.adoc[leveloffset=+1]
//Procedure to deploy Kafka Connect
include::assembly-deploy-kafka-connect.adoc[leveloffset=+1]
//Procedure to deploy Kafka MirrorMaker
include::assembly-deploy-kafka-mirror-maker.adoc[leveloffset=+1]
//Procedure to deploy Kafka Bridge
include::assembly-deploy-kafka-bridge.adoc[leveloffset=+1]
