// This assembly is included in the following assemblies:
//
// deploying/assembly-deploy-kafka-connect.adoc

[id='using-kafka-connect-with-plug-ins-{context}']
= Extending Kafka Connect with connector plugins

[role="_abstract"]
Kafka Connect uses connector instances to integrate with other systems to stream data.
Connectors can be one of the following type:

* Source connectors that push data into Kafka
* Sink connectors that extract data out of Kafka

The procedures in this section describe how you can add connectors by doing one of the following:

* xref:creating-new-image-using-kafka-connect-build-{context}[]
* xref:creating-new-image-from-base-{context}[](manually or using continuous integration)

IMPORTANT: You create the configuration for connectors directly xref:assembly-creating-managing-connectors-{context}[using the Kafka Connect REST API or `KafkaConnector` custom resources].

You can use your own connectors or try the example `FileStreamSourceConnector` and  `FileStreamSinkConnector` connectors for moving file-based data into and out of a Kafka cluster.
For information on deploying the example file connectors as `KafkaConnector` resources, see xref:proc-deploying-kafkaconnector-str[].  

NOTE: Up until Apache Kafka 3.1.0, the Strimzi container images for Kafka Connect included the example file connectors. From Apache Kafka 3.1.1 and 3.2.0, these connectors are no longer included and must be deployed like any connector. 

//Procedure to create a container images using Strimzi and Kafka Connect build
include::modules/proc-deploy-kafka-connect-using-kafka-connect-build.adoc[leveloffset=+1]
//Procedure to create a container images from base image
include::modules/proc-deploy-kafka-connect-new-image-from-base.adoc[leveloffset=+1]
