// This assembly is included in the following assemblies:
//
// deploying/assembly-deploy-kafka-connect.adoc

[id='using-kafka-connect-with-plug-ins-{context}']
= Extending Kafka Connect with connector plugins

Up until Apache Kafka 3.1.0, the Strimzi container images for Kafka Connect included two built-in file connectors for moving file-based data into and out of your Kafka cluster.

.File connectors
[cols="2*",options="header",stripes="none",separator=¦]
|===

¦File Connector
¦Description

m¦FileStreamSourceConnector
¦Transfers data to your Kafka cluster from a file (the source).

m¦FileStreamSinkConnector
¦Transfers data from your Kafka cluster to a file (the sink).

|===

From Apache Kafka 3.1.1 and 3.2.0, these connectors are no longer included.

The procedures in this section describe how you can add the example connectors or your own connectors by doing one of the following:

* xref:creating-new-image-using-kafka-connect-build-{context}[Creating a new container image automatically using Strimzi]

* xref:creating-new-image-from-base-{context}[Creating a container image from the Kafka Connect base image (manually or using continuous integration)]

IMPORTANT: You create the configuration for connectors directly xref:assembly-creating-managing-connectors-{context}[using the Kafka Connect REST API or `KafkaConnector` custom resources].

//Procedure to create a container images using Strimzi and Kafka Connect build
include::modules/proc-deploy-kafka-connect-using-kafka-connect-build.adoc[leveloffset=+1]
//Procedure to create a container images from base image
include::modules/proc-deploy-kafka-connect-new-image-from-base.adoc[leveloffset=+1]
