:_mod-docs-content-type: CONCEPT

// Module included in the following assemblies:
//
// assembly-config.adoc

[id='con-config-mirrormaker2-sync-acls-{context}']
= Synchronizing ACL rules

[role="_abstract"]
MirrorMaker 2 can synchronize topic ACL rules from source to target clusters. 
Enable this feature by configuring the `MirrorSourceConnector`.

When using simple ACL-based authorization:

* Topic ACL rules can be synchronized between source and target topics
* MirrorMaker 2 copies topic-related ACL rules from the source cluster to the target cluster
* The `ALLOW ALL` topic ACL is not copied

Copying ACL rules does not guarantee equivalent access for all operations on the target cluster.
Additional ACL rules may still be required to allow producers or consumers to operate as expected on the target cluster, for example, ACLs for other resource types such as consumer groups or transactional IDs.

IMPORTANT: This feature is not compatible with the User Operator. 
If you use the User Operator, set `sync.topic.acls.enabled` to `false`.
When using OAuth 2.0 authorization, the setting has no effect.

.Example configuration to enable ACL synchronization
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: {KafkaMirrorMaker2ApiVersion}
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker2
  # ...
  mirrors:
    - source:
        # ...
      sourceConnector:
        config:
          sync.topic.acls.enabled: "true" # <1>
----
<1> Copies topic-related ACL rules from the source cluster to the target cluster.