// Module included in the following assemblies:
//
// assembly-config.adoc

[id='config-examples-{context}']
= Using example configuration files

[role="_abstract"]
Further enhance your deployment by incorporating additional supported configuration.
Example configuration files are provided with the downloadable release artifacts from the {ReleaseDownload}.
ifdef::Downloading[]
You can also access the example files directly from the
link:https://github.com/strimzi/strimzi-kafka-operator/tree/{GithubVersion}/examples/[`examples` directory^].
endif::Downloading[]

The example files include only the essential properties and values for custom resources by default. 
You can download and apply the examples using the `kubectl` command-line tool.
The examples can serve as a starting point when building your own Kafka component configuration for deployment.

NOTE: If you installed Strimzi using the Operator, you can still download the example files and use them to upload configuration.

The release artifacts include an `examples` directory that contains the configuration examples.

.Example configuration files provided with Strimzi
[source]
--
examples
├── user <1>
├── topic <2>
├── security <3>
│   ├── tls-auth
│   ├── scram-sha-512-auth
│   └── keycloak-authorization
├── mirror-maker <4>
├── metrics <5>
├── kafka <6>
│   └── nodepools <7>
├── cruise-control <8>
├── connect <9>
└── bridge <10>
--
<1> `KafkaUser` custom resource configuration, which is managed by the User Operator.
<2> `KafkaTopic` custom resource configuration, which is managed by Topic Operator.
<3> Authentication and authorization configuration for Kafka components. Includes example configuration for TLS and SCRAM-SHA-512 authentication. The Keycloak example includes `Kafka` custom resource configuration and a Keycloak realm specification. You can use the example to try Keycloak authorization services. There is also an example with enabled `oauth` authentication and `keycloak` authorization metrics.
<4> `Kafka` custom resource configuration for a deployment of Mirror Maker. Includes example configuration for replication policy and synchronization frequency.
<5> xref:assembly-metrics-config-files-{context}[Metrics configuration], including Prometheus installation and Grafana dashboard files.
<6> `Kafka` custom resource configuration for a deployment of Kafka. Includes example configuration for an ephemeral or persistent single or multi-node deployment.
<7> `KafkaNodePool` configuration for Kafka nodes in a Kafka cluster. Includes example configuration for nodes in clusters that use KRaft (Kafka Raft metadata) mode or ZooKeeper.  
<8> `Kafka` custom resource with a deployment configuration for Cruise Control. Includes `KafkaRebalance` custom resources to generate optimization proposals from Cruise Control, with example configurations to use the default or user optimization goals.
<9> `KafkaConnect` and `KafkaConnector` custom resource configuration for a deployment of Kafka Connect. Includes example configurations for a single or multi-node deployment.
<10> `KafkaBridge` custom resource configuration for a deployment of Kafka Bridge.