// Module included in the following assemblies:
//
// assembly-maintenance-time-windows.adoc

[id='con-maintenance-time-window-definition-{context}']
= Scheduling maintenance time windows

[role="_abstract"]
Use maintenance time windows to control when the Cluster Operator performs certificate renewals and rolling restarts.
This helps minimize disruption to Kafka clients by scheduling updates at convenient times.

Maintenance time windows apply only to certificates generated automatically by the Cluster Operator.
They do not apply to externally managed certificates, such as custom listener certificates or certificates issued by external certificate managers.
As a result, using custom certificates that are not managed by the Cluster Operator may lead to restarts occurring outside the defined maintenance windows.

Use time windows in conjunction with the xref:con-certificate-renewal-str[renewal periods for CA certificates] set in the `Kafka` resource (`Kafka.spec.clusterCa.renewalDays` and `Kafka.spec.clientsCa.renewalDays`).

Rolling restarts can be triggered in two ways:

* By user-driven changes to the `Kafka` custom resource
* Automatically, when certificates generated by the Cluster Operator near expiration

These restarts typically do not affect service availability but can temporarily impact client performance. 
Use maintenance time windows to schedule them during periods of low client activity.

Configure maintenance time windows as follows:

* Configure an array of strings using the `Kafka.spec.maintenanceTimeWindows` property of the `Kafka` resource.
* Each string is a {CronExpression} interpreted as being in UTC (Coordinated Universal Time)

The following example configures a single maintenance time window that starts at midnight and ends at 01:59am (UTC), on Sundays, Mondays, Tuesdays, Wednesdays, and Thursdays.

.Example maintenance time window configuration
[source,yaml,subs=attributes+]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    #...
  maintenanceTimeWindows:
    - "* * 0-1 ? * SUN,MON,TUE,WED,THU *"
  #...
----

NOTE: The Cluster Operator doesn't adhere strictly to the time windows 
Maintenance operations are triggered by the first reconciliation that occurs within the specified time window. 
If the time window is shorter than the interval between reconciliations, there's a risk that the reconciliation may happen outside of the time window, 
Therefore, maintenance time windows must be at least as long as the interval between reconciliations.
