// Module included in the following assemblies:
//
// assembly-kafka-entity-operator.adoc

[id='user-operator-{context}']
= User Operator configuration properties

User Operator deployment can be configured using additional options inside the `userOperator` object.
The following properties are supported:

`watchedNamespace`::
The Kubernetes namespace in which the user operator watches for `KafkaUsers`.
Default is the namespace where the Kafka cluster is deployed.

`reconciliationIntervalSeconds`::
The interval between periodic reconciliations in seconds.
Default `120`.

`zookeeperSessionTimeoutSeconds`::
The ZooKeeper session timeout in seconds.
Default `6`.

`image`::
The `image` property can be used to configure the container image which will be used.
For more details about configuring custom container images, see xref:con-common-configuration-images-reference[].

`resources`::
The `resources` property configures the amount of resources allocated to the User Operator.
For more details about resource request and limit configuration, see xref:con-common-configuration-resources-reference[].

`logging`::
The `logging` property configures the logging of the User Operator.
For more details, see xref:property-topic-operator-logging-reference[].

`secretPrefix`::
The `secretPrefix` property adds a prefix to the name of all Secrets created from the KafkaUser resource. For example, `STRIMZI_SECRET_PREFIX=kafka-` would prefix all Secret names with `kafka-`. So a KafkaUser named `my-user` would create a Secret named `kafka-my-user`.

.Example User Operator configuration
[source,yaml,subs=attributes+]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    # ...
  zookeeper:
    # ...
  entityOperator:
    # ...
    userOperator:
      watchedNamespace: my-user-namespace
      reconciliationIntervalSeconds: 60
    # ...
----
