// Module included in the following assemblies:
//
// assembly-kafka-connect-configuration.adoc

[id='con-kafka-connect-multiple-instances-{context}']
= Configuring Kafka Connect for multiple instances

If you are running multiple instances of Kafka Connect, you have to change the default configuration of the following `config` properties:

[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaConnectApiVersion}
kind: KafkaConnect
metadata:
  name: my-connect
spec:
  # ...
  config:
    group.id: connect-cluster <1>
    offset.storage.topic: connect-cluster-offsets <2>
    config.storage.topic: connect-cluster-configs <3>
    status.storage.topic: connect-cluster-status  <4>
    # ...
# ...
----
<1> The Kafka Connect cluster ID within Kafka.
<2> Kafka topic that stores connector offsets.
<3> Kafka topic that stores connector and task status configurations.
<4> Kafka topic that stores connector and task status updates.

NOTE: Values for the three topics must be the same for all Kafka Connect instances with the same `group.id`.

Unless you change the default settings, each Kafka Connect instance connecting to the same Kafka cluster is deployed with the same values.
What happens, in effect, is all instances are coupled to run in a cluster and use the same topics.

If multiple Kafka Connect clusters try to use the same topics, Kafka Connect will not work as expected and generate errors.

If you wish to run multiple Kafka Connect instances, change the values of these properties for each instance.
