// Module included in the following assemblies:
//
// configuring/assembly-reassign-tool.adoc

[id='proc-changing-topic-replicas-{context}']

= Changing the replication factor of topics

[role="_abstract"]
To change the replication factor of topics in a Kafka cluster, use the `kafka-reassign-partitions.sh` tool. 
This can be done by running the tool from an interactive pod container that is connected to the Kafka cluster, 
and using a reassignment file to describe how the topic replicas should be changed.

This procedure describes a secure process that uses TLS.
You'll need a Kafka cluster that uses TLS encryption and mTLS authentication.
A topic called `my-topic` has only 1 replica and we want to increase it to 3 replicas.

.Prerequisites

* You have a running Kafka cluster based on a `Kafka` resource configured with internal TLS encryption and mTLS authentication.
* You are connected as a `KafkaUser` configured with ACL rules that specify permission to manage the Kafka cluster and its topics.
* You have generated a reassignment JSON file named reassignment.json.

See xref:proc-generating-reassignment-json-files-{context}[Generating reassignment JSON files].

.Procedure

. Create some configuration files that will be used to run the `kafka-reassign-partitions.sh` tool
[source,shell,subs=+quotes]
----
$ mkdir -p /tmp/config

# client truststore and keystore
$ kubectl get secret my-cluster-cluster-ca-cert -o jsonpath="{.data['ca\.p12']}" | base64 -d >/tmp/config/truststore.p12
$ kubectl get secret my-user -o jsonpath="{.data['user\.p12']}" | base64 -d >/tmp/config/keystore.p12

# client authentication configuration
$ echo -e "security.protocol = SSL
ssl.truststore.type = PKCS12
ssl.truststore.location = /tmp/config/truststore.p12
ssl.truststore.password = $(kubectl get secret my-cluster-cluster-ca-cert -o jsonpath="{.data['ca\.password']}" | base64 -d)
ssl.keystore.type = PKCS12
ssl.keystore.location = /tmp/config/keystore.p12
ssl.keystore.password = $(kubectl get secret my-user -o jsonpath="{.data['user\.password']}" | base64 -d)" >/tmp/config/client.properties

# reassignment JSON file describing desired state
$ echo -e '{
  "version": 1,
  "partitions": [
    {"topic": "my-topic", "partition": 0, "replicas": [0, 2, 1]},
    {"topic": "my-topic", "partition": 1, "replicas": [2, 1, 0]},
    {"topic": "my-topic", "partition": 2, "replicas": [1, 0, 2]}
  ]
}' >/tmp/config/reassignment.json
----

. Run a new interactive pod container, copy all configuration files and connect to an interactive shell
[source,shell,subs=+quotes]
----
$ kubectl run reassignment --image="quay.io/strimzi/kafka:latest-kafka-3.6.0" -- /bin/bash -c "trap : TERM INT; sleep infinity & wait"
$ kubectl cp /tmp/config reassignment:/tmp/config
$ kubectl exec reassignment -itq -- bash
----

. From the shell, run the `kafka-reassign-partitions.sh` to start the reassignment with a throttle limit of 5 MB/s (increase if needed)
[source,shell,subs=+quotes]
----
[kafka@reassignment kafka]$ bin/kafka-reassign-partitions.sh \
  --bootstrap-server my-cluster-kafka-bootstrap:9093 \
  --command-config /tmp/config/client.properties \
  --reassignment-json-file /tmp/config/reassignment.json \
  --execute --throttle 5000000
Current partition replica assignment

{"version":1,"partitions":[{"topic":"my-topic","partition":0,"replicas":[2],"log_dirs":["any"]},{"topic":"my-topic","partition":1,"replicas":[1],"log_dirs":["any"]},{"topic":"my-topic","partition":2,"replicas":[0],"log_dirs":["any"]}]}

Save this to use as the --reassignment-json-file option during rollback
Warning: You must run --verify periodically, until the reassignment completes, to ensure the throttle is removed.
The inter-broker throttle limit was set to 5000000 B/s
Successfully started partition reassignments for my-topic-0,my-topic-1,my-topic-2
----

. It is important to also call `--verify` to check if the operation is completed, and to disable throttling
[source,shell,subs=+quotes]
----
[kafka@reassignment kafka]$ bin/kafka-reassign-partitions.sh \
  --bootstrap-server my-cluster-kafka-bootstrap:9093 \
  --command-config /tmp/config/client.properties \
  --reassignment-json-file /tmp/config/reassignment.json \
  --verify
Status of partition reassignment:
Reassignment of partition my-topic-0 is completed.
Reassignment of partition my-topic-1 is completed.
Reassignment of partition my-topic-2 is completed.

Clearing broker-level throttles on brokers 0,1,2
Clearing topic-level throttles on topic my-topic
----

. Once the reassignment is completed, delete the interactive pod, and wait for `KafkaTopic` reconciliation failure
[source,shell,subs=+quotes]
----
[kafka@reassignment kafka]$ exit
exit

$ kubectl delete po reassignment
pod "reassignment" deleted

$ kubectl get kt -w
NAME       CLUSTER      PARTITIONS   REPLICATION FACTOR   READY
my-topic   my-cluster   3            1                    True
my-topic   my-cluster   3            1                    False
----

. Finally, patch the `KafkaTopic` custom resource to match the new replication factor, and let the operator do the rest
[source,shell,subs=+quotes]
----
$ kubectl patch kt my-topic --type merge -p '
  spec:
    replicas: 3'
kafkatopic.kafka.strimzi.io/my-topic patched

$ kubectl get kt -w
NAME       CLUSTER      PARTITIONS   REPLICATION FACTOR   READY
my-topic   my-cluster   3            1                    False
my-topic   my-cluster   3            3                    True
----
