// Module included in the following assemblies:
//
// configuring/assembly-scaling-clusters.adoc

[id='proc-scaling-up-a-kafka-cluster-{context}']

= Scaling up a Kafka cluster

[role="_abstract"]
Use a reassignment file to increase the number of brokers in a Kafka cluster.

The reassignment file should describe how partitions are reassigned to brokers in the enlarged Kafka cluster.

This procedure describes a secure scaling process that uses TLS.
You'll need a Kafka cluster that uses TLS encryption and mTLS authentication.

.Prerequisites

* You have a running Kafka cluster based on a `Kafka` resource configured with internal TLS encryption and mTLS authentication.
* You have generated a reassignment JSON file named `reassignment.json`.
* You are running an interactive pod container that is connected to the running Kafka broker.
* You are connected as a `KafkaUser` configured with ACL rules that specify permission to manage the Kafka cluster and its topics.

See xref:proc-generating-reassignment-json-files-{context}[Generating reassignment JSON files].

.Procedure

. Add as many new brokers as you need by increasing the `Kafka.spec.kafka.replicas` configuration option.

. Verify that the new broker pods have started.

include::snip-reassign-partitions.adoc[]
