// Module included in the following assemblies:
//
// assembly-scheduling.adoc

[id='proc-configuring-node-affinity-{context}']
= Configuring pod affinity for specific nodes

[role="_abstract"]
Your Kubernetes cluster might have different types of worker nodes, some with specialized hardware like fast SSD storage, powerful CPUs, or high-speed network cards. 

To optimize performance and resource usage, configure `nodeAffinity` in your `KafkaNodePool` resource so that Kafka pods in a specific pool are scheduled only on the nodes that meet their requirements.

.Prerequisites

* A Kubernetes cluster
* A running Cluster Operator
* Worker nodes are labelled

.Procedure

. Label the worker nodes where you want to schedule your Kafka pods. 
+
If the nodes aren't already labeled, apply labels using `kubectl label`:
+
[source,shell,subs="+quotes,attributes+"]
----
kubectl label node <name_of_node> node-type=fast-network
----

. In your `KafkaNodePool` custom resource, edit the `affinity` property in the `spec.template.pod` section.
+
To assign Kafka pods from the same node pool to a worker node, add a `nodeAffinity` rule.
+
* Use `nodeSelectorTerms` with `matchExpressions` to specify the key (label name) and values of the nodes you want to schedule pods on. 
Pods are only scheduled on nodes that match these expressions.
+
.Example affinity configuration for specific nodes
[source,yaml,subs=attributes+]
----
apiVersion: {KafkaNodePoolApiVersion}
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - broker
  template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                    - fast-network
  # ...
----

. Apply the changes to the `KafkaNodePool` configuration.
