// Module included in the following assemblies:
//
// assembly-config.adoc

[id='proc-manual-restart-connector-{context}']
= Manually restarting Kafka Connect connectors

[role="_abstract"]
If you are using `KafkaConnector` resources to manage connectors, use the `strimzi.io/restart` annotation to manually trigger a restart of a connector.

.Prerequisites

* The Cluster Operator is running.

.Procedure

. Find the name of the `KafkaConnector` custom resource that controls the Kafka connector you want to restart:
+
[source,shell,subs="+quotes"]
----
kubectl get KafkaConnector
----

. Restart the connector by annotating the `KafkaConnector` resource in Kubernetes:
+
[source,shell,subs="+quotes"]
----
kubectl annotate KafkaConnector <kafka_connector_name> strimzi.io/restart="true"
----
+
The `restart` annotation is set to `true`. 
+
You can also refine the restart behavior with the `includeTasks` and `onlyFailed` parameters, which both default to `false`.  
+
--
* `includeTasks` restarts both the connector instance and its task instances.  
* `onlyFailed` restarts only instances with a `FAILED` status when set to `true`.  
--
+
For example: 
+
[source,shell]
----
strimzi.io/restart="includeTasks,onlyFailed"
----

. Wait for the next reconciliation to occur (every two minutes by default).
+
The Kafka connector is restarted, as long as the annotation was detected by the reconciliation process.
When Kafka Connect accepts the restart request, the annotation is removed from the `KafkaConnector` custom resource.
