// Module included in the following assemblies:
//
// assembly-deploy-kafka-connect.adoc

[id='ref-list-of-kafka-connect-resources-{context}']
= List of Kafka Connect cluster resources

The following resources are created by the Cluster Operator in the Kubernetes cluster:

<connect_cluster_name>-connect:: Name given to the following Kafka Connect resources:
+
- Deployment that creates the Kafka Connect worker node pods (when `StableConnectIdentities` feature gate is disabled).
- StrimziPodSet that creates the Kafka Connect worker node pods (when `StableConnectIdentities` feature gate is enabled).
- Headless service that provides stable DNS names to the Connect pods (when `StableConnectIdentities` feature gate is enabled).
- Pod Disruption Budget configured for the Kafka Connect worker nodes.
<connect_cluster_name>-connect-<pod_id>:: Pods created by the Kafka Connect StrimziPodSet (when `StableConnectIdentities` feature gate is enabled). 
<connect_cluster_name>-connect-api:: Service which exposes the REST interface for managing the Kafka Connect cluster.
<connect_cluster_name>-config:: ConfigMap which contains the Kafka Connect ancillary configuration and is mounted as a volume by the Kafka broker pods.
