// This assembly is included in the following assemblies:
//
// assembly-kafka-exporter.adoc
[id='con-metrics-kafka-exporter-lag{context}']

= Consumer lag

Consumer lag indicates the difference in the rate of production and consumption of messages.
Specifically, consumer lag indicates the delay between a Kafka broker writing a message created by a producer and the rate in which it is picked up by a consumer.

This difference is sometimes referred to as the _delta_ between the producer offset and consumer offset, the read and write positions in the Kafka broker topic partitions.

Suppose a topic streams 100 messages a second. A lag of 1000 messages between the producer offset (the topic partition head) and the last offset the consumer has read means a 10-second delay.

.The importance of monitoring consumer lag

For applications that rely on the processing of (near) real-time data, it is critical to monitor consumer lag to check that it does not become too big.
The bigger the lag becomes, the further the process moves from the real-time processing objective.

The lag, for example, might be a result of consuming too much old data that has not been purged, or through unplanned shutdowns.

.Reducing consumer lag

Typical actions to reduce lag include:

* Scaling-up consumer groups by adding new consumers
* Increasing the retention time for a message to remain in a topic
* Adding more disk capacity to increase the message buffer
* Dropping messages

Actions to reduce consumer lag depend on the underlying infrastructure and the use cases {ProductName} is supporting.
For instance, the potential impact of lag on broker performance can determine whether consumers are configured to use a disk cache or read from an actual disk.
And in certain cases, it might be acceptable to automatically drop messages until a consumer has caught up.
