{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: strimzi-cluster-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "strimzi.name" . }}
    chart: {{ template "strimzi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    name: strimzi-cluster-operator
    strimzi.io/kind: cluster-operator
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
{{- end }}
