// Module included in the following module:
//
// con-oauth-config.adoc

[id='proc-oauth-client-config-{context}']
= Configuring Kafka Java clients to use {oauth}

This procedure describes how to configure Kafka producer and consumer APIs to use {oauth} for interaction with Kafka brokers.

Add a client callback plugin to your _pom.xml_ file, and configure the system properties.

.Prerequisites

* AMQ Streams and Kafka is running
* {oauth} authorization server is deployed and configured for OAuth access to Kafka brokers
* Kafka brokers are configured for {oauth}

.Procedure

. Add the client callback plugin to the `pom.xml` file for the Kafka client:
+
[source,xml,subs="+attributes"]
----
<dependency>
 <groupId>io.strimzi</groupId>
 <artifactId>kafka-oauth-client</artifactId>
 <version>{oauth-artifact-version}</version>
</dependency>
----

. Configure the system properties for the callback:
+
[source,xml, subs="+quotes,attributes"]
----
System.setProperty(ClientConfig.OAUTH_TOKEN_ENDPOINT_URI, “https://<authorization-server-address>/auth/realms/demo/protocol/openid-connect/token”);
System.setProperty(Config.OAUTH_CLIENT_ID, "kafka-producer-client");
System.setProperty(Config.OAUTH_CLIENT_SECRET, "<client-secret>");
----

. Enable the _SASL OAUTHBEARER_ mechanism on a TLS encrypted connection in the Kafka client configuration:
+
[source,xml]
----
props.put("sasl.jaas.config", "org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;");
props.put("security.protocol", "SASL_SSL");
props.put("sasl.mechanism", "OAUTHBEARER");
props.put("sasl.login.callback.handler.class", "io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler");
----

. Verify that the Kafka client can access the Kafka brokers.

.What to do next

* xref:proc-oauth-kafka-config-{context}[Configure Kafka components to use {oauth}]
