[appendix]
[[installing_kubernetes_and_openshift_cluster]]
== Installing {ProductPlatformName} cluster

The easiest way to get started with {ProductPlatformName} is using the `Minikube`, `Minishift` or `oc cluster up`
utilities. This section provides basic guidance on how to use them. More details are provided on the websites of
the tools themselves.

ifdef::Kubernetes[]
=== {KubernetesName}

In order to interact with a {KubernetesName} cluster the https://kubernetes.io/docs/tasks/tools/install-kubectl/[`kubectl`]
utility needs to be installed.

The easiest way to get a running {KubernetesName} cluster is using `Minikube`. `Minikube` can be downloaded and installed
from the https://kubernetes.io/docs/getting-started-guides/minikube/[{KubernetesName} website]. Depending on the number of brokers
you want to deploy inside the cluster and if you need Kafka Connect running as well, it could be worth running `Minikube`
at least with 4 GB of RAM instead of the default 2 GB.
Once installed, it can be started using:

[source,shell]
minikube start --memory 4096
endif::Kubernetes[]

=== {OpenShiftName}

In order to interact with an {OpenShiftName} cluster, the https://github.com/openshift/origin/releases[`oc`] utility is needed.

An {OpenShiftName} cluster can be started in two different ways. The `oc` utility can start a cluster locally using the
command:

[source,shell]
oc cluster up

This command requires Docker to be installed. More information about this way can be found
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md[here].

Another option is to use `Minishift`. `Minishift` is an {OpenShiftName} installation within a VM. It can be downloaded and
installed from the https://docs.openshift.org/latest/minishift/index.html[Minishift website]. Depending on the number of brokers
you want to deploy inside the cluster and if you need Kafka Connect running as well, it could be worth running `Minishift`
at least with 4 GB of RAM instead of the default 2 GB.
Once installed, `Minishift` can be started using the following command:

[source,shell]
minishift start --memory 4GB
