[appendix]
[[installing_openshift_cluster]]
== Installing an OpenShift cluster

The easiest way to get started with OpenShift is using `minishift` or `oc cluster up`.

This section provides basic guidance on how to use them.

For more information on the tools, refer to the documentation available online.

The https://github.com/openshift/origin/releases[`oc`] utility is one of the main tools for interacting with OpenShift. 
It provides a simple way of starting a local cluster using the command

[source,shell]
oc cluster up

This command requires Docker to be installed. More information about this way can be found
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md[here].

Another option is to use `minishift`. `minishift` is an OpenShift installation within a VM. It can be downloaded and
installed from the https://docs.openshift.org/latest/minishift/index.html[Minishift website]. Depending on the number of brokers
you want to deploy inside the cluster and if you need Kafka Connect running as well, it could be worth running `minishift`
at least with 4 GB of RAM instead of the default 2 GB.
Once installed, `minishift` can be started using the following command:

[source,shell]
minishift start --memory 4GB

If you want to use `kubectl` with either an `oc cluster up` or `minishift` cluster you will need to https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/[configure it], as unlike with `minikube` this won't be done automatically.

=== `oc` and `kubectl`

The `oc` command also functions as an alternative to `kubectl`. 
In almost all cases the example `kubectl` commands given in this guide can be done using `oc` simply by replacing the command name (options and arguments remain the same).
In other words instead of 

[source,shell,subs=+quotes]
kubectl apply -f _your-file_

when using OpenShift you could alternatively use

[source,shell,subs=+quotes]
oc apply -f _your-file_

NOTE: As an exception to this general rule, the `oc` tool makes "cluster management" subcommands of `oc adm`, while `kubectl` does not make such a distinction.
For example, the `oc` equivalent of `kubectl taint` is `oc adm taint`.

