// This assembly is included in the following assemblies:
//
// master.adoc

[id='assembly-distributed-tracing-{context}']
= Distributed tracing

{ProductName} provides support for the distributed tracing of transactions within a typical Kafka architecture. When Kafka client applications are instrumented for distributed tracing, {ProductName} generates __traces__ for transactions such as producing and consuming messages, or writing offsets to the consumer offsets log.

A sample of the total number of traces is visualized in a user interface using Jaeger. You can use this trace data to monitor the operation of your Kafka cluster from end-to-end, and debug performance issues with target systems and applications. Trace data complements the metrics available to view in Grafana dashboards -- for more information, see xref:assembly-metrics-setup-{context}[]. 

.Components supported for tracing

{ProductName} supports distributed tracing in the following components:

* Producers and consumers
* Kafka clusters
* Kafka Streams applications
* Mirror Maker
* Kafka Connect, including Kafka Connect with Source2Image support

Only Java client applications are supported. 

The procedures in this chapter describe how to instrument your client applications for distributed tracing.

.Overview of OpenTracing and Jaeger

Distributed tracing in {ProductName} is implemented using the open source {OpenTracingHome} and {JaegerHome} projects.

* An emerging specification, OpenTracing defines APIs that developers can use to instrument their applications -- often in microservice architectures -- for distributed tracing. It is independent from the tracing system.
+
NOTE: The OpenTracing project is currently merging with the OpenCensus project. The new combined project is named {OpenTelemetryHome}. OpenTelemetry will provide compatibility for applications that are instrumented using the OpenTracing APIs.

* Jaeger is a popular tracing system used for monitoring and troubleshooting microservices-based distributed systems. Jaeger is an implementation of the OpenTracing APIs that developers and administrators can use to visualize, query, filter, and analyze trace data.

{ProductName} uses the https://github.com/opentracing-contrib/java-kafka-client/blob/master/README.md[OpenTracing Apache Kafka Client Instrumentation^] library, which simplifies the instrumentation of Kafka clients for OpenTracing. This library is an example of a __tracer__.

.Summary

Setting up distributed tracing within {ProductName} involves several procedures.

* xref:proc-configuring-jaeger-tracer-kafka-clients-{context}[]

* xref:proc-instrumenting-producers-consumers-for-opentracing-{context}[]

* xref:proc-instrumenting-kafka-streams-with-tracers-{context}[]

* xref:assembly-setting-up-tracing-mirror-maker-connect-{context}[]

Setting up distributed tracing across process boundaries is outside the scope of this documentation. For more information on this subject, see the {OpenTracingDocs} and search for "inject and extract".

.Prerequisites

Before you set up distributed tracing, it is helpful to understand:

* The basics of OpenTracing, including key concepts such as traces, spans, and tracers. Refer to the {OpenTracingDocs}.

* The components of the {JaegerArch}. 

include::assembly-setting-up-tracing-kafka-clients.adoc[leveloffset=+1]

include::assembly-instrumenting-kafka-clients-tracers.adoc[leveloffset=+1]

include::assembly-setting-up-tracing-mirror-maker-connect.adoc[leveloffset=+1]