// This assembly is included in the following assemblies:
//
// master.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.
:parent-context: {ContextProduct}

include::common/attributes.adoc[]

[id='security-{context}']
= Security

The Strimzi project supports data encryption of communication between the different Kafka and Strimzi components (Kafka brokers, Zookeeper nodes, Kafka Connect and Strimzi Topic Operator) by means of the SSL/TLS protocol.
This makes it possible to encrypt data transferred between Kafka brokers (interbroker communication), between Zookeeper nodes (internodal communication), and between clients and Kafka brokers. For the Kafka and Strimzi components, TLS certificates are also used for authentication.

The Cluster Operator sets up the SSL/TLS certificates to provide this encryption and authentication.

:context: str
include::con-security-certificates.adoc[leveloffset=+1]

:context: str
include::con-interbroker-communications.adoc[leveloffset=+1]

:context: str
include::con-zookeeper-communications.adoc[leveloffset=+1]

:context: str
include::con-client-connection-tls.adoc[leveloffset=+1]

// Restore the context to what it was before this assembly.
:context: {parent-context}





