// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration.adoc

[id='assembly-oauth-{context}']
= Using {oauth} token based authentication

{ProductName} supports the use of {oauth} authentication.
{oauth} enables standardized token based authentication and authorization between applications by way of a central {oauth} authorization server that issues tokens that grant limited access to resources.

Using {oauth} token based authentication, application clients can access resources on application servers (called ‘resource servers’) without exposing account credentials.
Rather, they present an access token as a means of authenticating, which application servers can also use to find more information about the level of access granted.
The authorization server handles the granting of access and inquiries about access.

In the context of {ProductName}:

* Kafka brokers act as resource servers
* Kafka clients act as resource clients

The brokers and clients communicate with the {oauth} authorization server, as necessary, to obtain or validate access tokens.

For a deployment of {ProductName}, {oauth} integration provides:

* Server-side {oauth} support for Kafka brokers
* Client-side {oauth} support for:
** Java-based Kafka clients
** Kafka Mirror Maker, Kafka Connect and the Kafka Bridge

.Additional resources

* {oauth2-site}

include::oauth/con-oauth-authentication-flow.adoc[leveloffset=+1]
include::oauth/con-oauth-authentication-client-options.adoc[leveloffset=+1]
include::assembly-oauth-config.adoc[leveloffset=+1]
