// This assembly is included in the following assemblies:
//
// assembly-metrics-setup.adoc
[id='assembly-metrics-kafka-{context}']

= Kafka metrics configuration

{ProductName} uses the link:https://github.com/prometheus/jmx_exporter[Prometheus JMX Exporter^] to export JMX metrics from Kafka and ZooKeeper to a Prometheus HTTP metrics endpoint, which is then scraped by the Prometheus server.

The Grafana dashboard provided with {ProductName} is dependent on Prometheus JMX Exporter relabeling rules, which are defined for Kafka and ZooKeeper as `Kafka` resource configuration in an example `kafka-metrics.yaml` file.

To use the Grafana dashboard, do one of the following:

* link:https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/{GithubVersion}/metrics/examples/kafka/kafka-metrics.yaml[Copy the example configuration to your own `Kafka` resource definition^]
* xref:proc-metrics-deploying-kafka-{context}[Deploy an example Kafka cluster with the metrics configuration]

include::proc-metrics-deploying-kafka.adoc[leveloffset=+1]
