// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration-kafka.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.
:parent-context: {context}

[id='assembly-zookeeper-replicas-{context}']

= Replicas

Zookeeper clusters / ensembles usually run in odd number of nodes.
It always requires majority of the nodes to be available in order to maintain quorum.
Maintaining quorum is important, because when the Zookeeper cluster looses quorum, it will stop responding to clients.
As a result, Zookeeper cluster without a quorum will cause the Kafka brokers to stop working as well.
This is why having stable and highly available Zookeeper cluster is very important for {ProductName}.

Zookeeper cluster is usually deployed with 3, 5 or 7 nodes.

3 nodes::
Zookeeper cluster consisting of 3 nodes requires at least 2 nodes to be up and running in order to maintain the quorum.
It can tolerate only one node being unavailable.

5 nodes::
Zookeeper cluster consisting of 5 nodes requires at least 3 nodes to be up and running in order to maintain the quorum.
It can tolerate 2 nodes being unavailable.

7 nodes::
Zookeeper cluster consisting of 7 nodes requires at least 4 nodes to be up and running in order to maintain the quorum.
It can tolerate 3 nodes being unavailable.

NOTE: For development purposes, it is also possible to run Zookeeper only with a single node.

Having more nodes doesn't necessarily mean better performance, as the costs to maintain the quorum will rise with the number of nodes in the cluster.
Depending on your availability requirements, you can decide for the number of nodes to use.

include::ref-zookeeper-replicas.adoc[leveloffset=+1]

include::proc-configuring-zookeeper-replicas.adoc[leveloffset=+1]

// Restore the context to what it was before this assembly.
:context: {parent-context}