// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration-kafka-bridge.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='assembly-kafka-bridge-bootstrap-servers-{context}']

= Bootstrap servers

A Kafka Bridge always works in combination with a Kafka cluster.
A Kafka cluster is specified as a list of bootstrap servers.
On Kubernetes, the list must ideally contain the Kafka cluster bootstrap service named `_cluster-name_-kafka-bootstrap`, and a port of 9092 for plain traffic or 9093 for encrypted traffic.

The list of bootstrap servers is configured in the `bootstrapServers` property in `KafkaBridge.kafka.spec`. The servers must be defined as a comma-separated list specifying one or more Kafka brokers, or a service pointing to Kafka brokers specified as a `_hostname_:_port_` pairs.

When using Kafka Bridge with a Kafka cluster not managed by {ProductName}, you can specify the bootstrap servers list according to the configuration of the cluster.

include::proc-configuring-kafka-bridge-bootstrap-servers.adoc[leveloffset=+1]
