// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration-kafka.adoc
// assembly-deployment-configuration-kafka-connect.adoc
// assembly-deployment-configuration-kafka-connect-s2i.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='assembly-configuring-container-images-{context}']

= Container images

{ProductName} allows you to configure container images which will be used for its components.
Overriding container images is recommended only in special situations, where you need to use a different container registry.
For example, because your network does not allow access to the container repository used by {ProductName}.
In such a case, you should either copy the {ProductName} images or build them from the source.
If the configured image is not compatible with {ProductName} images, it might not work properly.

include::ref-configuring-container-images.adoc[leveloffset=+1]

include::proc-configuring-container-images.adoc[leveloffset=+1]
