// This assembly is included in the following assemblies:
//
// master.adoc

[id='assembly-distributed-tracing-{context}']
= Distributed tracing

This chapter provides an overview of the support for distributed tracing in {ProductName}. It includes procedures for configuring distributed tracing in {ProductName} components and instrumenting client applications.

include::con-overview-distributed-tracing.adoc[leveloffset=+1]

.Summary

Setting up distributed tracing for {ProductName} involves the following procedures.

* xref:proc-configuring-jaeger-tracer-kafka-clients-{context}[]

* xref:proc-instrumenting-producers-consumers-for-opentracing-{context}[]

* xref:proc-instrumenting-kafka-streams-with-tracers-{context}[]

* xref:assembly-setting-up-tracing-mirror-maker-connect-{context}[]

Setting up distributed tracing across process boundaries is outside the scope of this documentation. For more information on this subject, see the {OpenTracingDocs} and search for "inject and extract".

.Prerequisites

Before you set up distributed tracing, it is helpful to understand:

* The basics of OpenTracing, including key concepts such as traces, spans, and tracers. Refer to the {OpenTracingDocs}.

* The components of the {JaegerArch}. 

include::assembly-setting-up-tracing-kafka-clients.adoc[leveloffset=+1]

include::assembly-instrumenting-kafka-clients-tracers.adoc[leveloffset=+1]

include::assembly-setting-up-tracing-mirror-maker-connect.adoc[leveloffset=+1]