// This assembly is included in the following assemblies:
//
// master.adoc

[id='assembly-upgrade-{context}']
= {ProductName} and Kafka upgrades

Each version of {ProductName} supports a range of versions of Apache Kafka.
You can upgrade to a higher Kafka version as long as that version is supported by your version of {ProductName}.
In some cases, you can also downgrade to a lower supported Kafka version.

When a newer version of {ProductName} is available, it may provide support for newer versions of Kafka. 
Therefore, you will need to upgrade to the new version of {ProductName} before you can upgrade to a higher supported Kafka version.
Upgrading the version of {ProductName} is done by upgrading the Cluster Operator deployment to the new version.

ifdef::StrimziUpgrades[]
include::proc-upgrading-the-cluster-operator-0-10-0-to-0-11-0.adoc[leveloffset=+1]
endif::StrimziUpgrades[]

include::proc-upgrading-the-cluster-operator-0-9-0-to-0-10-0.adoc[leveloffset=+1]

include::assembly-upgrading-kafka-versions.adoc[leveloffset=+1]