// This assembly is included in the following assemblies:
//
// master.adoc

[id='assembly-distributed-tracing-{context}']
= Distributed tracing

This chapter provides an overview of distributed tracing in {ProductName}. It includes procedures for configuring distributed tracing in Kafka Connect and Mirror Maker, and for instrumenting client applications for tracing.

include::con-overview-distributed-tracing.adoc[leveloffset=+1]

.Outline of procedures

To set up distributed tracing for {ProductName}, you must:

* xref:proc-configuring-jaeger-tracer-kafka-clients-{context}[Initialize a Jaeger tracer for Kafka clients]

* xref:proc-instrumenting-producers-consumers-for-opentracing-{context}[Instrument producers and consumers for tracing]

* xref:proc-instrumenting-kafka-streams-with-tracers-{context}[Instrument Kafka Streams for tracing]

* xref:assembly-setting-up-tracing-mirror-maker-connect-{context}[Set up tracing for Mirror Maker and Kafka Connect]

//Need to reword
Setting up distributed tracing across process boundaries is outside the scope of this documentation. For more information on this subject, see the {OpenTracingDocs} and search for "inject and extract".

.Prerequisites

Before you set up distributed tracing, it is helpful to understand:

* The basics of OpenTracing, including key concepts such as traces, spans, and tracers. Refer to the {OpenTracingDocs}.

* The components of the {JaegerArch}. 

include::assembly-setting-up-tracing-kafka-clients.adoc[leveloffset=+1]

include::assembly-instrumenting-kafka-clients-tracers.adoc[leveloffset=+1]

include::assembly-setting-up-tracing-mirror-maker-connect.adoc[leveloffset=+1]