// This assembly is included in the following assemblies:
//
// master.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='overview-{context}']
= Overview

{ProductName} makes it easy to run Apache Kafka on {ProductPlatformName}. Apache Kafka is a popular platform for streaming data delivery and processing. For more information about Apache Kafka, see the http://kafka.apache.org[Apache Kafka website^].

{ProductName} is based on Apache Kafka 1.1.0 and consists of two main components:

Cluster Operator:: Responsible for deploying and managing Apache Kafka clusters within {ProductPlatformName} cluster.
Topic Operator:: Responsible for managing Kafka topics within a Kafka cluster running within {ProductPlatformName} cluster.

This guide describes how to install and use {ProductLongName}.

include::ref-key-features.adoc[leveloffset=+1]

include::ref-document-conventions.adoc[leveloffset=+1]