// Module included in the following assemblies:
//
// getting-started.adoc

[id='assembly-custom-resources-{context}']
= Custom resources

Custom resource definitions (CRDs) extend the Kubernetes API, providing definitions to create and modify custom resources to a Kubernetes cluster. Custom resources are created as instances of CRDs.

In {ProductName}, CRDs introduce custom resources specific to {ProductName} to a Kubernetes cluster, such as Kafka, Kafka Connect, Kafka Mirror Maker, and users and topics custom resources.  CRDs provide configuration instructions, defining the schemas used to instantiate and manage the {ProductName}-specific resources. CRDs also allow {ProductName} resources to benefit from native Kubernetes features like CLI accessibility and configuration validation.

CRDs require a one-time installation in a cluster. Depending on the cluster setup, installation typically requires cluster admin privileges.

NOTE: Access to manage custom resources is limited to xref:assembly-getting-started-strimzi-admin-{context}[{ProductName} administrators].

CRDs and custom resources are defined as YAML files.

A CRD defines a new `kind` of resource, such as `kind:Kafka`, within a Kubernetes cluster.

The Kubernetes API server allows custom resources to be created based on the `kind` and understands from the CRD how to validate and store the custom resource when it is added to the Kubernetes cluster.

WARNING: When CRDs are deleted, custom resources of that type are also deleted. Additionally, the resources created by the custom resource, such as pods and statefulsets are also deleted.

.Additional resources
* {K8sCRDs}

include::con-custom-resources-example.adoc[leveloffset=+1]

include::con-custom-resources-status.adoc[leveloffset=+1]
