// This assembly is included in the following assemblies:
//
// getting-started.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.
[id='cluster-operator-{context}']
= Cluster Operator

{ProductName} uses the Cluster Operator to deploy and manage Kafka (including Zookeeper) and Kafka Connect clusters.
The Cluster Operator is deployed inside of the Kubernetes cluster.
To deploy a Kafka cluster, a `Kafka` resource with the cluster configuration has to be created within the Kubernetes cluster.
Based on what is declared inside of the `Kafka` resource, the Cluster Operator deploys a corresponding Kafka cluster.
For more information about the different configuration options supported by the `Kafka` resource, see xref:assembly-deployment-configuration-kafka-str[]

NOTE: {ProductName} contains example YAML files, which make deploying a Cluster Operator easier.

include::con-what-the-cluster-operator-does.adoc[leveloffset=+1]

include::proc-deploying-cluster-operator.adoc[leveloffset=+1]

include::proc-deploying-cluster-operator-to-watch-multiple-namespaces.adoc[leveloffset=+1]

include::proc-deploying-cluster-operator-to-watch-whole-cluster.adoc[leveloffset=+1]

ifdef::Helm[]
include::proc-deploying-cluster-operator-helm-chart.adoc[leveloffset=+1]
endif::Helm[]

ifdef::OperatorHubio[]
include::con-deploying-cluster-operator-from-operator-hub.adoc[leveloffset=+1]
endif::OperatorHubio[]