// This assembly is included in the following assemblies:
//
// master.adoc

[id='assembly-using-the-kafka-bridge-{context}']
= Using the {ProductName} Kafka Bridge

This chapter provides an overview of the {ProductName} Kafka Bridge. 

ifdef::TechPreview[]
IMPORTANT: The {ProductName} Kafka Bridge is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service-level agreements (SLAs) and might not be functionally complete; therefore, Red Hat does not recommend implementing any Technology Preview features in production environments. This Technology Preview feature provides early access to upcoming product innovations, enabling you to test functionality and provide feedback during the development process. For more information about support scope, see {TechPreviewFeatures} on the Red Hat Customer Portal.
endif::TechPreview[]

include::con-overview-of-kafka-bridge.adoc[leveloffset=+1]

include::con-supported-data-formats-kafka-bridge.adoc[leveloffset=+1]

include::proc-deploying-kafka-bridge.adoc[leveloffset=+1]

include::con-configuring-consumer-producer-options-kafka-bridge.adoc[leveloffset=+1]

include::con-sending-requests-to-kafka-bridge.adoc[leveloffset=+1]

include::proc-using-port-forwarding-kafka-bridge.adoc[leveloffset=+1]

include::ref-api-resources-kafka-bridge.adoc[leveloffset=+1]



