// This assembly is included in the following assemblies:
//
// master.adoc

[id='assembly-distributed-tracing-{context}']
= Distributed tracing

This chapter provides an overview of distributed tracing in {ProductName}. It includes procedures for configuring distributed tracing in Kafka Connect and Mirror Maker, and for instrumenting Kafka Producer, Consumer, and Streams API applications for tracing.

include::con-overview-distributed-tracing.adoc[leveloffset=+1]

.Outline of procedures

To set up distributed tracing for {ProductName}, follow these procedures:

* xref:proc-configuring-jaeger-tracer-kafka-clients-{context}[Initialize a Jaeger tracer for Kafka clients]

* xref:proc-instrumenting-producers-consumers-for-opentracing-{context}[Instrument Kafka Producers and Consumers for tracing]

* xref:proc-instrumenting-kafka-streams-with-tracers-{context}[Instrument Kafka Streams applications for tracing]

* xref:assembly-setting-up-tracing-mirror-maker-connect-{context}[Set up tracing for Mirror Maker and Kafka Connect]

This chapter covers setting up distributed tracing for {ProductName} components only. Setting up distributed tracing for applications and systems beyond {ProductName} is outside the scope of this chapter. To learn more about this subject, see the {OpenTracingDocs} and search for "inject and extract".

.Prerequisites

* The Jaeger backend components are deployed to your Kubernetes cluster. For deployment instructions, see the https://www.jaegertracing.io/docs/1.14/deployment/[Jaeger deployment documentation^].

Before you set up distributed tracing for {ProductName}, it is helpful to understand:

* The basics of OpenTracing, including key concepts such as traces, spans, and tracers. Refer to the {OpenTracingDocs}.

* The components of the {JaegerArch}. 

include::assembly-setting-up-tracing-kafka-clients.adoc[leveloffset=+1]

include::assembly-instrumenting-kafka-clients-tracers.adoc[leveloffset=+1]

include::assembly-setting-up-tracing-mirror-maker-connect.adoc[leveloffset=+1]