// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration-kafka-bridge.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='assembly-kafka-bridge-replicas-{context}']

= Replicas

Kafka Bridge can run multiple nodes.
The number of nodes is defined in the `KafkaBridge` resource.
Running a Kafka Bridge with multiple nodes can provide better availability and scalability.
However, when running Kafka Bridge on Kubernetes it is not absolutely necessary to run multiple nodes of Kafka Bridge for high availability.

IMPORTANT: If a node where Kafka Bridge is deployed to crashes, Kubernetes will automatically reschedule the Kafka Bridge pod to a different node.
In order to prevent issues arising when client consumer requests are processed by different Kafka Bridge instances, addressed-based routing must be employed to ensure that requests are routed to the right Kafka Bridge instance.
Additionally, each independent Kafka Bridge instance must have a replica. A Kafka Bridge instance has its own state which is not shared with another instances.

include::proc-configuring-kafka-bridge-replicas.adoc[leveloffset=+1]
