// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration-kafka-connect.adoc
// assembly-deployment-configuration-kafka-connect-s2i.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='assembly-kafka-connect-bootstrap-servers-{context}']

= Bootstrap servers

Kafka Connect cluster always works together with a Kafka cluster.
The Kafka cluster is specified in the form of a list of bootstrap servers.
On {ProductPlatformName}, the list must ideally contain the Kafka cluster bootstrap service which is named `_<cluster-name>_-kafka-bootstrap` and a port of 9092 for plain traffic or 9093 for encrypted traffic.

The list of bootstrap servers can be configured in the `bootstrapServers` property in `KafkaConnect.spec` and `KafkaConnectS2I.spec`. The servers should be a comma-separated list containing one or more Kafka brokers or a service pointing to Kafka brokers specified as a `<hostname>:<port>` pairs.

When using Kafka Connect with a Kafka cluster not managed by {ProductName}, you can specify the bootstrap servers list according to the configuration of a given cluster.

include::proc-configuring-kafka-connect-bootstrap-servers.adoc[leveloffset=+1]
