// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration-kafka.adoc
// assembly-deployment-configuration-kafka-connect.adoc
// assembly-deployment-configuration-kafka-connect-s2i.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.
:parent-context: {context}

[id='assembly-configuring-container-images-{context}']

= Container images

{ProductName} allows you to configure container images which will be used for its componenets.
Overriding container images is recommended especially in situations where you need to use a different container registry.
For example, because your network doesn't allow access to the container repository used by {ProductName}.
In such case, you should either copy the {ProductName} images or build them from source.
In case the configured image is not compatible with {ProductName} images, it might not work properly.

include::ref-configuring-container-images.adoc[leveloffset=+1]

include::proc-configuring-container-images.adoc[leveloffset=+1]

// Restore the context to what it was before this assembly.
:context: {parent-context}