// This assembly is included in the following assemblies:
//
// master.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.
:parent-context:{Context}

[id='encryption-{context}']
= Encryption

The {ProductName} encrypts communication between the Kafka and Strimzi components through the SSL/TLS protocol.
Using the SSL/TLS protocol, it can encrypt data transferred between Kafka brokers (interbroker communication), between Zookeeper nodes (internodal communication), and between clients and Kafka brokers. For the Kafka and {ProductName} components, TLS certificates are also used for authentication.

The Cluster Operator sets up the SSL/TLS certificates to provide this encryption and authentication.

include::con-encryption-certificates.adoc[leveloffset=+1]

include::con-interbroker-communications.adoc[leveloffset=+1]

include::con-zookeeper-communications.adoc[leveloffset=+1]

include::con-client-connection-tls.adoc[leveloffset=+1]

// Restore the context to what it was before this assembly.
:context: {parent-context}





