// This assembly is included in the following assemblies:
//
// getting-started.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.
:parent-context: {context}

include::common/attributes.adoc[]

[id='kafka-connect-{context}']
= Kafka Connect

The Cluster Operator can also deploy a link:https://kafka.apache.org/documentation/#connect[Kafka Connect^] cluster, which can be used with your Kafka broker deployment.
It is implemented as a `Deployment` with a configurable number of workers.
The default image currently contains only the `FileStreamSinkConnector` and `FileStreamSourceConnector` connectors.
The REST interface for managing the Kafka Connect cluster is exposed internally within the {ProductPlatformName} cluster as a `kafka-connect` service on port `8083`.

Example `KafkaConnect` resources and the details about the `KafkaConnect` format for deploying Kafka Connect can be found in
xref:kafka_connect_config_map_details[].

ifdef::Kubernetes[]
:context: str
include::proc-deploying-kafka-connect-kubernetes.adoc[leveloffset=+1]
endif::Kubernetes[]

:context: str
include::proc-deploying-kafka-connect-openshift.adoc[leveloffset=+1]

:context: str
include::assembly-using-kafka-connect-with-plugins.adoc[leveloffset=+2]

// Restore the context to what it was before this assembly.
:context: {parent-context}
