// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration-kafka.adoc
// assembly-deployment-configuration-kafka-connect.adoc
// assembly-deployment-configuration-kafka-connect-s2i.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='assembly-logging-{context}']
= Logging

Logging enables you to diagnose error and performance issues of {ProductName}.
For the logging, various logger implementations are used.
Kafka and Zookeeper use `log4j` logger and Topic Operator, User Operator, and other components use `log4j2` logger.

This section provides information about different loggers and describes how to configure log levels.

You can set the log levels by specifying the loggers and their levels directly (inline) or by using a custom (external) config map.

include::proc-kafka-inline-logging.adoc[leveloffset=+1]

include::proc-kafka-external-logging.adoc[leveloffset=+1]

include::ref-kafka-logging.adoc[leveloffset=+1]