// Module included in the following assemblies:
//
// assembly-security.adoc

= Certificates

Each {ProductName} component needs its own private and public keys in order to support encryption.
The public key has to be signed by a certificate authority (CA) in order to have a related X.509 certificate for providing server authentication and encrypting the communication channel with the client (which could be another broker as well).
All component certificates are signed by a Certification Authority (CA) called _cluster CA_.
Another CA is used for authentication of Kafka clients connecting to Kafka brokers.
This CA is called _clients CA_.
The CAs themselves use self-signed certificates.

All of the generated certificates are saved as Secrets in the {ProductPlatformName} cluster, named as follows:

`<cluster-name>-cluster-ca`::
Contains the private and public keys of the cluster CA which is used for signing server certificates for the Kafka and {ProductName} components (Kafka brokers, Zookeeper nodes, and so on).
`<cluster-name>-cluster-ca-cert`::
Contains only the public key of the cluster CA.
The public key used by Kafka clients to verify the identity of the Kafka brokers they are connecting to (TLS server authentication).
`<cluster-name>-clients-ca`::
Contains the private and public keys of the clients CA.
The clients CA is used for TLS client authentication of Kafka clients when connecting to Kafka brokers.
`<cluster-name>-clients-ca-cert`::
Contains only the public key of the client CA.
The public key is used by the Kafka brokers to verify the identity of Kafka clients when TLS client authentication is used.
`<cluster-name>-kafka-brokers`::
Contains all the Kafka broker private and public keys (certificates signed with the cluster CA).
`<cluster-name>-zookeeper-nodes`::
Contains all the Zookeeper node private and public keys (certificates signed with the cluster CA).
`<cluster-name>-topic-operator-certs`::
Contains the private and public keys (certificates signed with the cluster CA) used for encrypting communication between the Topic Operator and Kafka or Zookeeper.

All the keys are 2048 bits in size and are valid for 365 days from initial generation.

NOTE: "certificates rotation" for generating new ones on their expiration will be supported in future releases.