// Module included in the following assemblies:
//
// getting-started.adoc

[id='downloads-{context}']
= Installing and deploying {ProductName} components

ifdef::Downloading[]
{ProductName} releases are available to download from {ReleaseDownload}. The release artefacts contain documentation, installation, and example `.yaml` files for deployment on {ProductPlatformName}. The installation, and example files are used throughout this documentation. Additionally, a Helm Chart is provided for deploying the Cluster Operator using link:https://helm.sh/[Helm^]. The container images are available through the {DockerRepository}.
endif::Downloading[]
ifndef::Downloading[]
The following sections provide overviews and deployment instructions for each of the core components of {ProductName}:

* The Cluster Operator
* Kafka Cluster
* Kafka Connect
* The Topic Operator
* The User Operator

When following the deployment instructions, use the YAML files provided. These help you to install {ProductName} on {ProductPlatformName}, perform common operations, and configure your Kafka cluster. {ExampleYAMLURL} are available to download from the AMQ Streams website.

NOTE: Container images for {ProductName} are available in the {ReleaseDownload}. We recommend that you use the installation and example YAML files instead of downloading the container images.

endif::Downloading[]
