// Module included in the following assemblies:
//
// assembly-using-the-kafka-bridge.adoc

[id='con-requests-kafka-bridge-{context}']
= Requests to the {ProductName} Kafka Bridge

== Authentication and encryption

Authentication and encryption between clients and the Kafka Bridge is not yet supported. This means that requests sent from clients to the Kafka Bridge are:

* Not encrypted, and must use HTTP rather than HTTPS

* Sent without authentication

Within your {ProductPlatformName} cluster, you can configure TLS or SASL-based authentication between the Kafka Bridge and your Kafka cluster. For more information, see LINK TO CHAPTER 3 **Connecting to Kafka brokers with Authentication**. 

== Data formats and headers

Request and response bodies are encoded as JSON. When sending a `POST` request to a resource, you must provide the following `Content-Type` header, which is specific to Kafka:

[source,http,subs=+quotes]
----
Content-Type: application/vnd.kafka.v2+json
----

Sent and received messages can have an **embedded data format** of either JSON or binary. You specify the embedded data format in the `format` field of the request body when creating a consumer using the `/consumers/{groupid}` endpoint. For example:

[source,json,subs=attributes+]
----
{
  "name": "my-consumer",
  "format": "json",
...
}
----

If you specify `binary` format, you must provide binary data as a base-64 encoded string. 

After creating a consumer, you must provide an `Accept` header that corresponds to the consumer's embedded data format with all subsequent requests. The `Accept` header is in the following format:

[source,http,subs=+quotes]
----
Accept: application/vnd._embedded-data-format_.kafka.v2+json
----

For example, when committing a list of consumer offsets for a consumer that has an embedded data format of JSON, include this Accept header:

[source,http,subs=+quotes]
----
Accept: application/vnd.json.kafka.v2+json
----

When using Producer operations, such as the `/topics/{topicname}` endpoint, to produce messages, make sure you provide a `Content-Type` header that corresponds to the embedded data format of the consumer that will consume the messages.

== API version

Using v2.

application/vnd.kafka.[embedded_format].[api_version]+[serialization_format]


== HTTP Verbs

The quick brown fox.