// Module included in the following assemblies:
//
// assembly-using-the-kafka-bridge.adoc

[id='con-overview-of-kafka-bridge-{context}']

= Overview of the {ProductName} Kafka Bridge

The {ProductName} Kafka Bridge provides an API for integrating HTTP-based clients with a Kafka cluster running on {ProductPlatformName}. The API enables such clients to produce and consume messages without the requirement to use the native Kafka protocol.

The API has two resources -- `consumers` and `topics` -- that provide endpoints to interact with consumers and producers in your Kafka cluster. You can: 

* Send messages to a topic.

* Create and delete consumers.

* Subscribe consumers to topics, so that they start receiving messages from those topics.

* Unsubscribe consumers from topics.

* Assign partitions to consumers.

* Retrieve messages from topics.

* Commit a list of consumer offsets.

* Seek on a partition, so that a consumer starts receiving messages from the first or last offset position, or a given offset position.

Similar to a Kafka Connect cluster, you can choose to deploy the Kafka Bridge into your {ProductPlatformName} cluster using the Cluster Operator. For deployment instructions, see xref:kafka-bridge-{context}[].

After the Kafka Bridge is deployed, the Cluster Operator creates a Deployment, Service, and Pod in your {ProductPlatformName} cluster, each named `strimzi-kafka-bridge`.
