// Module included in the following assemblies:
//
// assembly-custom-resources.adoc

[id='con-custom-resources-status-{context}']
= {ProductName} custom resource status

The `status` property of a {ProductName}-specific custom resource is configured to capture the _current_ state of the resource and make that information available.

Status information is useful for tracking progress related to a resource achieving its _desired_ state, providing the time and reason the state of the resource changed and details of events causing delays.

NOTE: The status field is different from the spec field, which describes the _desired_ state of an object.

{ProductName} creates and maintains the status of custom resources. Periodically, {ProductName} evaluates the current state of the custom resource and updates the status of that resource accordingly.

Here we see the `status` property specified for a Kafka custom resource.

.Kafka custom resource with status
[source,yaml,subs="attributes+"]
----
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
spec:
  # ...
status:
  conditions: <1>
  listeners: <2>
    plain:
      host: my-cluster-kafka-bootstrap.myproject.svc
      port: 9092
    tls:
      host: my-cluster-kafka-bootstrap.myproject.svc
      port: 9093
    external::
      host: my-cluster-kafka-external-bootstrap.myproject.svc
      Port: 9094
    ready: true <3>
    # ...
----
<1> Status `conditions` describe criteria related to the status that cannot be deduced from the existing resource information, or are specific to the instance of a resource.
<2> The `listeners` describe the current Kafka bootstrap addresses by type.
<3> The `ready` field indicates whether the resource has been successfully reconciled (approved for traffic by the cluster operator).

You can access status information for a resource from the command line. For more information, see
