// Module included in the following assemblies:
//
// assembly-using-the-kafka-bridge.adoc

[id='con-supported-clients-kafka-bridge-{context}']

= Supported clients for the {ProductName} Kafka Bridge

You can use the Kafka Bridge to integrate both _internal_ and _external_ HTTP client applications with your Kafka cluster.

* Internal clients are container-based HTTP clients running in _the same_ Kubernetes cluster as the Kafka Bridge itself.

* External clients are HTTP clients running _outside_ the Kubernetes cluster in which the Kafka Bridge is deployed and running.

Internal clients can access the Kafka Bridge on the host and port defined in the `KafkaBridge` custom resource. External clients can access the Kafka Bridge through an OpenShift Route, a LoadBalancer Service, or a Ingress.

.Additional resources

* For more information on configuring the host and port for the `KafkaBridge` resource, see xref:ref-kafka-bridge-http-configuration-deployment-configuration-kafka-bridge[].
* For more information on integrating external clients, see xref:con-accessing-kafka-bridge-from-outside-{context}[].
