// Module included in the following assemblies:
//
// assembly-configuring-kafka-listeners.adoc

[id='con-kafka-listeners-{context}']
= Kafka listeners

Kafka broker listeners can be configured using the `listeners` property in the `Kafka.spec.kafka` resource.
The `listeners` property contains two sub-properties:

* `plain`
* `tls`

When these sub-properties are not defined, the listener will be disabled.

.An example of `listeners` property with all listeners enabled
[source,yaml,subs="attributes+"]
----
# ...
listeners:
  plain: {}
  tls: {}
# ...
----

.An example of `listeners` property with only the plain listener enables
[source,yaml,subs="attributes+"]
----
# ...
listeners:
  plain: {}
# ...
----

== Listener authentication

The listener sub-properties can also contain additional configuration.
Both listeners support the `authentication` property. This be used to specify an authentication mechanism specific to that listener:

* mutual TLS authentication
* SCRAM-SHA authentication

If no `authentication` property is specified then the listener does not authenticate clients which connect though that listener.

.An example where the plain listener is configured for SCRAM-SHA authentication and the `tls` listener with mutual TLS authentication
[source,yaml,subs="attributes+"]
----
# ...
listeners:
  plain:
    authentication:
      type: scram-sha-512
  tls:
    authentication:
      type: tls
# ...
----


Authentication must be configured when using the User Operator to manage `KafkaUsers`.