// Module included in the following assemblies:
//
// assembly-using-the-kafka-bridge.adoc

[id='con-requests-kafka-bridge-{context}']
= Requests to the {ProductName} Kafka Bridge

== Authentication and encryption

Authentication and encryption between clients and the Kafka Bridge is not yet supported. This means that requests sent from clients to the Kafka Bridge are:

* Not encrypted, and must use HTTP rather than HTTPS

* Sent without authentication

Within your {ProductPlatformName} cluster, you can configure TLS or SASL-based authentication between the Kafka Bridge and your Kafka cluster. For more information, see LINK TO CHAPTER 3 **Connecting to Kafka brokers with Authentication**. 

== Content types

The quick brown fox.

embedded format

two formats: 
1) used for encoding the body of the HTTP request - always JSON to encode the body INSIDE every message. Specified in the HTTP Header of POST requests as content-type: application/vnd.kafka.v2+json

2) The embedded format of the "Kafka message" sent by the client to Kafka or received from Kafka, which can be JSON *or* binary. This is specified in the body of the request, see `create Consumer`.
   - JSON: The body of the message and the value of the message are both encoded as JSON.
   - Binary: Used for sending binary data rather than a simple string. Have to send this value inside the HTTP message encoded as base-64. The message value must be a string because the body is JSON - base-64 allows you to encode the binary data as a string so it can be sent.

   when you create a consumer, you specify the "format" in the request body: JSON or binary. Let's create a new consumer that will be able to ACCEPT messages created in EITHER JSON or binary - the embedded format. The consumer needs to specify an ACCEPT header

   On the consumer side, you MUST specify an Accept header that corresponds with the embedded format that was specificed when the consumer was created.

   The producer must supply a CONTENT-TYPE header: "I'm sending a message to you and this message is encoded as binary or JSON"


   From Confluent docs: "You should specify preferred content types in requests and check the content types of responses."

== API version

Using v2.

application/vnd.kafka.[embedded_format].[api_version]+[serialization_format]


== HTTP Verbs

The quick brown fox.