// Module included in the following assemblies:
//
// assembly-node-scheduling.adoc

include::common/attributes.adoc[]

[id='con-scheduling-to-specific-nodes-{context}']
= Node scheduling

It is a common situation that an {ProductPlatformName} cluster consists of many different types of worker nodes.
Some are optimized for CPU heavy workloads, some for memory, while other might be optimized for storage (fast local SSDs) or network.
Using different nodes helps to optimize both costs and performance.
To achieve the best possible performance, it is important to be able to schedule the {ProductName} components to use the right nodes.

To schedule workloads onto specific nodes, {ProductPlatformName} has a feature called node affinity.
Node affinity allows users to create a scheduling constraint for the node on which the pod will be scheduled.
The constraint is specified as a label selector.
It can either use the built-in node label such as `beta.kubernetes.io/instance-type`.
Or it can use some custom labels to select the right node.
