// This module is included in the following assemblies:
//
// assembly-upgrading-kafka-versions.adoc

[id='con-kafka-downgrades-using-cluster-operator-{context}']
= Kafka downgrades using the Cluster Operator

Whether and how the Cluster Operator will perform a downgrade depends on the differences between:

* The interbroker protocol version of the two Kafka versions
* The log message format version of the two Kafka versions
* The version of Zookeeper used by the two Kafka versions

If the downgraded version of Kafka has the same log message format version then downgrade is always possible.
In this case the Cluster Operator will be able to downgrade by performing a single rolling restart of the brokers.

If the downgraded version of Kafka has a different log message format version, then downgrade is only possible if the running cluster has
_always_ had `log.message.format.version` set to the version used by the downgraded version. 
This is typically only the case when the upgrade procedure has been aborted before the `log.message.format.version` was changed.
In this case the downgrade will require two rolling restarts of the brokers if the interbroker protocol of the two versions is different, or a single rolling restart if they are the same.