// Module included in the following assemblies:
//
// assembly-kafka-mirror-maker-authentication.adoc

[id='con-kafka-mirror-maker-authentication{context}']
= Authentication support in Kafka Mirror Maker

Authentication can be configured in the `KafkaMirrorMaker.spec.consumer.authentication` and `KafkaMirrorMaker.spec.producer.authentication` properties.
The `authentication` property specifies the type of the authentication method which should be used and additional configuration details depending on the mechanism.
The currently supported authentication types are:

* TLS client authentication
* SASL based authentication using SCRAM-SHA-512 mechanism


== TLS Client Authentication

To use the TLS client authentication, set the `type` property to the value `tls`.
The TLS client authentication uses TLS certificate to authenticate.
The certificate has to be specified in the certificateAndKey property.
It is always loaded from an {ProductPlatformName} secret.
Inside the secret, it has to be stored in the X.509 format separately as public and private keys.

NOTE: TLS client authentication can be used only with TLS connections.
For more details about TLS configuration in Kafka Mirror Maker see xref:assembly-kafka-mirror-maker-tls-{context}[].

.An example showing TLS client authentication configuration
[source,yaml,subs=attributes+]
----
apiVersion: {KafkaApiVersion}
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
spec:
  # ...
  consumer:
    authentication:
      type: tls
      certificateAndKey:
        secretName: my-source-secret
        certificate: public.crt
        key: private.key
  # ...
  producer:
    authentication:
      type: tls
      certificateAndKey:
        secretName: my-target-secret
        certificate: public.crt
        key: private.key
  # ...
----

== SCRAM-SHA-512 authentication

To configure Kafka Mirror Maker to use SCRAM-SHA-512 authentication, set the `type` property to `scram-sha-512`.
The broker listener to which clients are connecting must also be configured to use SCRAM-SHA-512 SASL authentication.
This authentication mechanism requires a username and password.

* Specify the username in the `username` property.
* In the `passwordSecret` property specify a link to a `Secret` containing the password. The `secretName` property contains the name of such a `Secret` and the `password` property contains the name of the key under which the password is stored inside the `Secret`.

WARNING: Do not specify the actual password in the `password` field.

.An example showing SCRAM-SHA-512 client authentication configuration
[source,yaml,subs=attributes+]
----
apiVersion: {KafkaApiVersion}
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
spec:
  # ...
  consumer:
    authentication:
      type: scram-sha-512
      username: my-source-user
      passwordSecret:
        secretName: my-source-user
        password: my-source-password-key
  # ...
  producer:
    authentication:
      type: scram-sha-512
      username: my-producer-user
      passwordSecret:
        secretName: my-producer-user
        password: my-producer-password-key
  # ...
----