// This assembly is included in the following assemblies:
//
// assembly-deployment-configuration-kafka-mirror-maker.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='assembly-configuring-container-images-{context}']

= Container images

Use the `image` property to configure the container image used by the component.

Overriding container images is recommended only in special situations where you need to use a different container registry.

For example, if your network does not allow access to the container repository used by {ProductName}, you can copy the {ProductName} images or build them from the source.
However, if the configured image is not compatible with {ProductName} images, it might not work properly.

For more information see xref:ref-configuring-container-images-deployment-configuration-kafka[Container image configurations].
