// This assembly is included in the following assemblies:
//
// assembly-kafka-connect-external-configuration.adoc

[id='con-kafka-connect-external-configuration-{context}']

= Externalizing Kafka Connect connector configuration

{ProductName} lets you to mount ConfigMaps or Secrets into the Kafka Connect pods as either volumes or environment variables.
The volumes and environment variables can be configured in the `externalConfiguration` property in `KafkaConnect.spec` and `KafkaConnectS2I.spec`

== External configuration as environment variable

The `env` property can be used to specify one or more environment variables.
These variables can contain a value from a ConfigMap or from a Secret.
The names of the environment variables configured by the user cannot start with `KAFKA_` or `STRIMZI_`.

To mount a value from a Secret to an environment variable, you have to use the `valueFrom` property and the `secretKeyReference`

.Example of environment variable set to a value from a Secret
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaApiVersion}
kind: KafkaConnect
metadata:
  name: my-connect
spec:
  # ...
  externalConfiguration:
    env:
      - name: MY_ENVIRONMENT_VARIABLE
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: my-key
----

A common use case for mounting Secrets into environment variables is for example when your connector needs to communicate with Amazon AWS and needs to read the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables with credentials.

To mount a value from a ConfigMap use `configMapKeyRef` in the `valueFrom` property.

.Example of environment variable set to a value from a ConfigMap
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaApiVersion}
kind: KafkaConnect
metadata:
  name: my-connect
spec:
  # ...
  externalConfiguration:
    env:
      - name: MY_ENVIRONMENT_VARIABLE
        valueFrom:
          configMapKeyRef:
            name: my-config-map
            key: my-key
----

== External configuration as volume

The ConfigMaps and Secrets can be also mounted as volumes.
Using volumes instead of environment variables migth be useful for example for:
* Mounting truststores / keystores with TLS certificates
* Mounting properties file which should used to configure Kafka Connect connectors

The ConfigMaps and Secrets which should be mounted as volumes should be listed in the `volumes` property of `externalConfiguration`.
Each volume has to specify a name in the `name` property and a reference to ConfigMap or Secret.

.Example of volumes with external configuration
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaApiVersion}
kind: KafkaConnect
metadata:
  name: my-connect
spec:
  # ...
  externalConfiguration:
    volumes:
      - name: connector1
        configMap:
          name: connector1-configuration
    - name: connector1-certificates
      secret:
        secretName: connector1-certificates
----

The volumes will be mounted inside the Kafka Connect containers in the path `/opt/kafka/external-configuration/_<volume-name>_`.
For example the files from the volume named `connector1` will be in the directory `/opt/kafka/external-configuration/connector1`.

The `FileConfigProvider` has to be used to read the values from the mounted properties files in connector configurations.