// Module included in the following assemblies:
//
// getting-started.adoc

[id='downloads-{context}']
= {ProductName} downloads

ifdef::Downloading[]
{ProductName} releases are available to download from {ReleaseDownload}. The release artefacts contain documentation, installation and example `.yaml` files for deployment on {ProductPlatformName}. The installation and example files are used throughout this documentation. Additionally, a Helm Chart is provided for deploying the Cluster Operator using link:https://helm.sh/[Helm^]. The container images are available through the {DockerRepository}.
endif::Downloading[]
ifndef::Downloading[]
The following procedures use installation and example YAML files to help you install {ProductName} on {ProductPlatformName}, perform common operations, and configure your Kafka cluster. {ExampleYAMLURL} are available to download from the AMQ Streams website.

NOTE: Container images for {ProductName} are available in the {ReleaseDownload}. We recommend that you use the installation and example YAML files instead of downloading the container images.

endif::Downloading[]
