// Module included in the following assemblies:
//
// getting-started.adoc

[id='downloads-{context}']
= Installing {ProductName} and deploying components

ifdef::Downloading[]
To install {ProductName}, download the release artefacts from {ReleaseDownload}.

The folder contains several YAML files to help you deploy the components of {ProductName} to {ProductPlatformName}, perform common operations, and configure your Kafka cluster. The YAML files are referenced throughout this documentation.

Additionally, a Helm Chart is provided for deploying the Cluster Operator using link:https://helm.sh/[Helm^]. The container images are available through the {DockerRepository}.

The remainder of this chapter provides an overview of each component and short instructions for deploying the components to {ProductPlatformName} using the YAML files provided.
endif::Downloading[]
ifndef::Downloading[]
To install {ProductName}, download and extract the `install_and_examples.zip` file from the https://access.redhat.com/node/3596931/423/0[AMQ Streams website].

The folder contains several YAML files to help you deploy the components of {ProductName} to {ProductPlatformName}, perform common operations, and configure your Kafka cluster. The YAML files are referenced throughout this documentation.

The remainder of this chapter provides an overview of each component and short instructions for deploying the components to {ProductPlatformName} using the YAML files provided.

NOTE: Although container images for {ProductName} are available in the {ReleaseDownload}, we recommend that you use the YAML files provided instead.
endif::Downloading[]
