// This assembly is included in the following assemblies:
//
// master.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='getting-started-{context}']
= Getting started with {ProductName}

{ProductName} works on all types of clusters, from public and private clouds to local deployments intended for development.
This guide assumes that a Kubernetes cluster is available and the `kubectl` command-line tool is installed and configured to connect to the running cluster.

ifndef::Downloading[]
{ProductName} is based on Strimzi {StrimziVersion}. This chapter describes the procedures to deploy {ProductName} on OpenShift {OpenShiftVersion}.
endif::Downloading[]

ifdef::InstallationAppendix[]
When no existing Kubernetes cluster is available, `minikube` can be used to create a local cluster.
More details can be found in xref:installing_kubernetes_cluster[Installing Kubernetes clusters].
{ProductName} supports a few specific OpenShift-specific features. 
If you need an OpenShift cluster to use these and none is available `minishift` can be used to create a local cluster.
More details can be found in xref:installing_openshift_cluster[Installing OpenShift clusters].
endif::InstallationAppendix[]

NOTE: To run the commands in this guide, your cluster user must have the rights to manage role-based access control (RBAC) and CRDs.


include::con-product-downloads.adoc[leveloffset=+1]

include::assembly-custom-resources.adoc[leveloffset=+1]

include::assembly-cluster-operator.adoc[leveloffset=+1]

include::assembly-kafka-cluster.adoc[leveloffset=+1]

include::assembly-kafka-connect.adoc[leveloffset=+1]

include::assembly-kafka-mirror-maker.adoc[leveloffset=+1]

include::assembly-kafka-bridge.adoc[leveloffset=+1]

include::proc-deploying-example-clients.adoc[leveloffset=+1]

include::assembly-getting-started-topic-operator.adoc[leveloffset=+1]

include::assembly-getting-started-user-operator.adoc[leveloffset=+1]

include::assembly-getting-started-strimzi-admin.adoc[leveloffset=+1]

include::con-container-images.adoc[leveloffset=+1]
