// This assembly is included in the following assemblies:
//
// master.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='getting-started-{context}']
= Getting started with {ProductName}

{ProductName} works on all types of clusters, from public and private clouds to local deployments intended for development.
This guide expects that an {ProductPlatformName} cluster is available and the
ifdef::Kubernetes[`kubectl` and]
`oc` command-line tools are installed and configured to connect to the running cluster.

ifndef::Downloading[]
{ProductName} is based on Strimzi {StrimziVersion}. This chapter describes the procedures to deploy {ProductName} on {OpenShiftName} {OpenShiftVersion}.
endif::Downloading[]

ifdef::InstallationAppendix[]
When no existing {ProductPlatformName} cluster is available, `Minikube` or `Minishift` can be used to create a local
cluster. More details can be found in xref:installing_kubernetes_and_openshift_cluster[Installing Kubernetes and OpenShift clusters].
endif::InstallationAppendix[]

NOTE: To run the commands in this guide, your
ifdef::Kubernetes[]
{KubernetesLongName} and
endif::Kubernetes[]
{OpenShiftLongName} user must have the rights to manage role-based access control (RBAC).

For more information about {OpenShiftName} and setting up {OpenShiftName} cluster, see link:https://docs.openshift.com/container-platform/3.9/welcome/index.html[OpenShift documentation].


include::con-product-downloads.adoc[leveloffset=+1]

include::assembly-cluster-operator.adoc[leveloffset=+1]

include::assembly-kafka-cluster.adoc[leveloffset=+1]

include::assembly-kafka-connect.adoc[leveloffset=+1]

include::assembly-kafka-mirror-maker.adoc[leveloffset=+1]

include::proc-deploying-example-clients.adoc[leveloffset=+1]

include::assembly-getting-started-topic-operator.adoc[leveloffset=+1]

include::assembly-getting-started-user-operator.adoc[leveloffset=+1]

include::assembly-getting-started-strimzi-admin.adoc[leveloffset=+1]

include::con-container-images.adoc[leveloffset=+1]
