// Module included in the following assemblies:
//
// assembly-storage.adoc

[id='proc-resizing-persistent-volumes-{context}']
= Resizing persistent volumes

You can provision increased storage capacity by increasing the size of the persistent volumes used by an existing {ProductName} cluster.
Resizing persistent volumes is supported in clusters that use either a single persistent volume or multiple persistent volumes in a JBOD storage configuration.

NOTE: You can increase but not decrease the size of persistent volumes. Decreasing the size of persistent volumes is not currently supported in {ProductPlatformName}.
Decreasing the size of persistent volumes is currently not possible.

.Prerequisites

* An {ProductPlatformName} cluster with support for volume resizing
* The Cluster Operator is running.
* A storage class which supports volume expansion
* A Kafka cluster using persistent volumes created using a given storage class

.Procedure

. Edit the `spec.kafka.storage` or `spec.zookeeper.storage` property in the `Kafka` resource.
Increase the volume size.
For example, to increase the volume size from `1000Gi` to `2000Gi`:
+
[source,yaml,subs=attributes+]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    # ...
    storage:
      type: persistent-claim
      size: 2000Gi
      class: my-storage-class
    # ...
  zookeeper:
    # ...
----
+
. Create or update the resource.
+
ifdef::Kubernetes[]
On {KubernetesName}, use `kubectl apply`:
[source,shell,subs=+quotes]
kubectl apply -f _your-file_
+
endif::Kubernetes[]
On {OpenShiftName}, use `oc apply`:
+
[source,shell,subs=+quotes]
oc apply -f _your-file_
+
{ProductPlatformName} increases the capacity of the selected persistent volumes in response to a request from the Cluster Operator. When the resizing is complete, the Cluster Operator restarts all pods that use the resized persistent volumes. This happens automatically.
. Once the persistent volumes are resized, the pods using them need to be restarted in order to resize the file system.
The restart is performed automatically by the Cluster Operator.

.Additional resources

For more information about resizing persistent volumes in {ProductPlatformName}, see {K8sResizingPersistentVolumesUsingKubernetes}.
