// Module included in the following assemblies:
//
// assembly-kafka-cluster.adoc

[id='deploying-kafka-cluster-openshift-{context}']
= Deploying the Kafka cluster to {OpenShiftName}

{ProductName} includes two templates for deploying a Kafka cluster to {OpenShiftName}:

* `kafka-ephemeral.yaml` deploys an ephemeral cluster named `my-cluster` by default.
* `kafka-persistent.yaml` deploys a persistent cluster named `my-cluster` by default.

To rename the cluster before deployment, edit the `Kafka.metadata.name` resource in the relevant YAML file.

The following procedure describes how to deploy both types of clusters on the command line. You can also deploy clusters in the {OpenShiftName} console. 

.Prerequisites

* You must have deployed the Cluster Operator before you can deploy a cluster.

.Procedure

. If you plan to use the cluster for development or testing purposes, create and deploy an ephemeral cluster using `oc apply`.
+
[source,shell]
----
oc apply -f examples/kafka/kafka-ephemeral.yaml
----

. If you plan to use the cluster in production, create and deploy a persistent cluster using `oc apply`.
+
[source,shell]
----
oc apply -f examples/kafka/kafka-persistent.yaml
----

.Additional resources
* For more information on deploying the Cluster Operator, see xref:cluster-operator-str[].
For more information on the different configuration options supported by the `Kafka` resource, see xref:assembly-deployment-configuration-kafka-str[].
