// Module included in the following assemblies:
//
// assembly-using-the-user-operator.adoc

[id='proc-changing-kafka-user-{context}']
= Editing a Kafka user

This procedure describes how to change the configuration of an existing Kafka user by using a `KafkaUser` {ProductPlatformName} resource.

.Prerequisites

* A running Kafka cluster.
* A running User Operator.
* An existing `KafkaUser` to be changed

.Procedure

. Edit the user either by preparing a YAML file containing the desired KafkaUser or by using {ProductPlatformName} tools.

Using YAML file::

.. Prepare a YAML file containing the desired `KafkaUser`.
+
An example `KafkaUser`
+
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaUserApiVersion}
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Describe
      - resource:
          type: group
          name: my-group
          patternType: literal
        operation: Read
----
+
.. Update the `KafkaUser` resource in {ProductPlatformName}.
+
ifdef::Kubernetes[]
On {KubernetesName} this can be done using `kubectl apply`:
[source,shell,subs=+quotes]
kubectl apply -f _<your-file>_
endif::Kubernetes[]
+
On {OpenShiftName} this can be done using `oc apply`:
+
[source,shell,subs=+quotes]
oc apply -f _<your-file>_
+

Editing the `KafkaUser` resource using {ProductPlatformName} tools::

.. Run the following command to edit the `KafkaUser` resource in the command line.

ifdef::Kubernetes[]
On {KubernetesName} this can be done using `kubectl edit`:
[source,shell,subs=+quotes]
kubectl edit kafkauser _<your-user-name>_
endif::Kubernetes[]

On {OpenShiftName} this can be done using `oc edit`:
[source,shell,subs=+quotes]
oc edit kafkauser _<your-user-name>_

.. Save the changes to the file.

. Use the updated credentials from the secret `my-user` in your application


.Additional resources

* For more information about deploying the Cluster Operator, see xref:cluster-operator-str[].
* For more information about deploying the Entity Operator, see xref:assembly-kafka-entity-operator-deployment-configuration-kafka[].
* For more information about the `KafkaUser` object, see xref:type-KafkaUser-reference[`KafkaUser` schema reference].
