// Module included in the following assemblies:
//
// assembly-kafka-bridge-quickstart.adoc

[id='proc-exposing-kafka-bridge-service-local-machine-{context}']
= Exposing the Kafka Bridge Service to your local machine

Next, create an OpenShift Route to expose the {ProductName} Kafka Bridge Service to your local machine on port 8080.

.Prerequisites

* The Kafka Bridge is deployed to your Kubernetes cluster.

.Procedure

. In a text editor, create a YAML definition for an unsecured OpenShift Route.
+
[source,yaml,subs=attributes+]
----
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quickstart-route
  labels:
    app: quickstart-route
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: quickstart-bridge-service
    weight: 100
----

. Save the file to the `examples/kafka-bridge` directory as `bridge-quickstart-route.yaml`.

. Use `oc` to create the Route in your Kubernetes cluster:
+
[source,shell,subs=attributes+]
----
oc apply -f examples/kafka-bridge/bridge-quickstart-route.yaml
----

. Use `oc` to retrieve the location of the Route:
+
[source,shell,subs=attributes+]
----
oc get routes
----
+
[source,shell,subs=attributes+]
----
NAME               HOST/PORT                              
quickstart-route   quickstart-route-<namespace>.<address>
----
+
Use the HOST/PORT as the `<bridge-address>` parameter in the remainder of this quick start.

.What to do next

After exposing the Kafka Bridge Service to your local machine, xref:proc-producing-messages-from-bridge-topics-partitions-{context}[produce messages to topics and partitions].