// Module included in the following assemblies:
//
// assembly-configuring-kafka-listeners.adoc

[id='proc-kafka-authorization-{context}']
= Configuring authorization in Kafka brokers

Authorization can be configured using the `authorization` property in the `Kafka.spec.kafka` resource.
When the `authorization` property is missing, no authorization will be enabled.
When authorization is enabled it will be applied for all enabled xref:assembly-configuring-kafka-broker-listeners-{context}[listeners].
The authorization method is defined by the `type` field.

NOTE: Currently, the only supported authorization method is the Simple authorization. Simple authorization is using the `SimpleAclAuthorizer` plugin, the default authorization plugin in Apache Kafka.

.Prerequisites

* An {ProductPlatformName} cluster
* A running Cluster Operator

.Procedure

. Add or edit the `authorization` property in the `Kafka.spec.kafka` resource.
For example:
+
[source,yaml,subs=attributes+]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
spec:
  kafka:
    # ...
    authorization:
      type: simple
    # ...
  zookeeper:
    # ...
----

. Create or update the resource.
+
ifdef::Kubernetes[]
On {KubernetesName} this can be done using `kubectl apply`:
[source,shell,subs=+quotes]
kubectl apply -f _<your-file>_
+
endif::Kubernetes[]
On {OpenShiftName} this can be done using `oc apply`:
+
[source,shell,subs=+quotes]
oc apply -f _<your-file>_

.Additional resources
//* For more information about the supported authorization methods, see xref:ref-kafka-authorization-{context}[authorization reference].
* For more information about the schema for `Kafka`, see xref:type-Kafka-reference[`Kafka` schema reference].
