// Module included in the following assemblies:
//
// assembly-cluster-operator.adoc
// assembly-operators-cluster-operator.adoc

[id='deploying-cluster-operator-to-watch-whole-cluster-{context}']
= Deploying the Cluster Operator to watch all namespaces

You can configure the Cluster Operator to watch {ProductName} resources across all namespaces in your Kubernetes cluster. When running in this mode, the Cluster Operator automatically manages clusters in any new namespaces that are created.

.Prerequisites

* Your Kubernetes cluster is running.

.Procedure

. Configure the Cluster Operator to watch all namespaces:
  
.. Edit the `050-Deployment-strimzi-cluster-operator.yaml` file.

.. Set the value of the `STRIMZI_NAMESPACE` environment variable to `*`.
+
[source,yaml,subs="attributes"]
----
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  template:
    spec:
      # ...
      serviceAccountName: strimzi-cluster-operator
      containers:
      - name: strimzi-cluster-operator
        image: {DockerClusterOperator}
        imagePullPolicy: IfNotPresent
        env:
        - name: STRIMZI_NAMESPACE
          value: "*"
        # ...
----

. Create `ClusterRoleBindings` that grant cluster-wide access to all namespaces to the Cluster Operator.
+
Use the `kubectl create clusterrolebinding` command:
+
[source,shell,subs="+quotes,attributes+"]
kubectl create clusterrolebinding strimzi-cluster-operator-namespaced --clusterrole=strimzi-cluster-operator-namespaced --serviceaccount _my-namespace_:strimzi-cluster-operator
kubectl create clusterrolebinding strimzi-cluster-operator-entity-operator-delegation --clusterrole=strimzi-entity-operator --serviceaccount _my-namespace_:strimzi-cluster-operator
kubectl create clusterrolebinding strimzi-cluster-operator-topic-operator-delegation --clusterrole=strimzi-topic-operator --serviceaccount _my-namespace_:strimzi-cluster-operator
+
Replace `_my-namespace_` with the namespace in which you want to install the Cluster Operator.

. Deploy the Cluster Operator to your Kubernetes cluster.
+
Use the `kubectl apply` command:
+
[source,shell,subs="+quotes,attributes+"]
kubectl apply -f install/cluster-operator -n _my-namespace_
