// Module included in the following assemblies:
//
// assembly-deploying-the-topic-operator.adoc

[id='proc-topic-operator-with-resource-requests-limits-{context}']
= Configuring the Topic Operator with resource requests and limits

.Prerequisites

* A running Cluster Operator

.Procedure

. Edit the `Kafka` resource specifying in the `Kafka.spec.entityOperator.topicOperator.resources` property the resource requests and limits you want the Topic Operator to have.
+
[source,yaml,subs=attributes+]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
spec:
  # kafka and zookeeper sections...
  topicOperator:
    resources:
      request:
        cpu: "1"
        memory: 500Mi
      limit:
        cpu: "1"
        memory: 500Mi
----

. Create or update the `Kafka` resource.
+
ifdef::Kubernetes[]
On {KubernetesName} this can be done using `kubectl apply`:
[source,shell,subs=+quotes]
kubectl apply -f _<your-file>_
+
endif::Kubernetes[]
On {OpenShiftName} this can be done using `oc apply`:
+
[source,shell,subs=+quotes]
oc apply -f _<your-file>_

.Additional resources

* For more information about the schema of the resources object, see xref:type-Resources-reference[].
//* For more information about the resource requirements of the Topic Operator, see xref:topic-operator-resource-requirements-str[].