// Module included in the following assemblies:
//
// assembly-kafka-mirror-maker-authentication.adoc

[id='proc-configuring-kafka-mirror-maker-authentication-scram-sha-512-{context}']
= Configuring SCRAM-SHA-512 authentication in Kafka Mirror Maker

.Prerequisites

* A Kubernetes cluster
* A running Cluster Operator with a `listener` configured for SCRAM-SHA-512 authentication
* Username to be used for authentication
* If they exist, the name of the `Secret` with the password used for authentication, and the key under which it is stored in the `Secret`

.Procedure

As the Kafka Mirror Maker connects to two Kafka clusters (source and target), you can choose to configure SCRAM-SHA-512 authentication for one or both the clusters.
The following steps describe how to configure SCRAM-SHA-512 authentication on the consumer side for connecting to the source Kafka cluster:

. (Optional) If they do not already exist, prepare a file with the password used for authentication and create the `Secret`.
+
NOTE: Secrets created by the User Operator may be used.
+
This can be done using `kubectl create`:
[source,shell,subs=+quotes]
echo -n '_<password>_' > _<my-password.txt>_
kubectl create secret generic _<my-secret>_ --from-file=_<my-password.txt>_

. Edit the `KafkaMirrorMaker.spec.consumer.authentication` property.
For example:
+
[source,yaml,subs=attributes+]
----
apiVersion: {KafkaApiVersion}
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
spec:
  # ...
  consumer:
    authentication:
      type: scram-sha-512
      username: _<my-username>_
      passwordSecret:
        secretName: _<my-secret>_
        password: _<my-password.txt>_
  # ...
----
+
. Create or update the resource.
+
This can be done using `kubectl apply`:
[source,shell,subs=+quotes]
kubectl apply -f _<your-file>_

Repeat the above steps for configuring SCRAM-SHA-512 authentication on the target Kafka cluster.
In this case, the secret containing the certificate has to be configured in the `KafkaMirrorMaker.spec.producer.authentication` property.
