// This assembly is included in the following assemblies:
//
// assembly-metrics-prometheus.adoc
[id='proc-metrics-deploying-prometheus-{context}']

= Deploying Prometheus

To deploy Prometheus to your Kafka cluster, apply the link:https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/{GithubVersion}/metrics/examples/prometheus/install/prometheus.yaml[Prometheus YAML^] resource file and the YAML files for Prometheus-related resources using the source for the Prometheus docker image in the `./metrics/examples/prometheus/install` directory of the repository.

The deployment process creates a `ClusterRoleBinding` and discovers an Alertmanager instance in the namespace defined in the YAML.

NOTE: Currently, the Prometheus Operator only supports jobs that include an `endpoints` role for service discovery. Targets are discovered and scraped for each endpoint port address. For endpoint discovery, the port address may be derived from service (`role: service`) or pod (`role: pod`) discovery.

.Prerequisites

* Check the xref:ref-metrics-alertmanager-examples-{context}[example alerting rules provided]

.Procedure

. Download the Prometheus resource file from the repository and replace the example namespace with your own:
+
On Linux, use:
+
[source,shell,subs="+quotes,attributes"]
curl -s https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/{GithubVersion}/metrics/examples/prometheus/install/prometheus.yaml | sed -e 's/namespace: .*/namespace: _my-namespace_/' > prometheus.yaml
+
On MacOS, use:
+
[source,shell,subs="+quotes,attributes"]
curl -s https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/{GithubVersion}/metrics/examples/prometheus/install/prometheus.yaml | sed -e '' 's/namespace: .*/namespace: _my-namespace_/' > prometheus.yaml

. Download and edit the `ServiceMonitor` resource in `strimzi-service-monitor.yaml` to define Prometheus jobs that will scrape the metrics data:
+
[source,shell,subs="+quotes,attributes"]
curl -O https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/{GithubVersion}/metrics/examples/prometheus/install/strimzi-service-monitor.yaml

. To use another role:
+
.. Create a `Secret` resource:
+
[source,shell,subs="+quotes,attributes"]
curl -O https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/{GithubVersion}/metrics/examples/prometheus/additional-properties/prometheus-additional.yaml
oc create secret generic additional-scrape-configs --from-file=prometheus-additional.yaml
+
.. Edit the `additionalScrapeConfigs` property in the `prometheus.yaml` file to include the name of the `Secret` and the YAML file (`prometheus-additional.yaml`) that contains the additional configuration.

. Download and edit the `prometheus-rules.yaml` file that creates sample alert notification rules:
+
On Linux, use:
+
[source,shell,subs="+quotes,attributes"]
curl -s https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/{GithubVersion}/metrics/examples/prometheus/install/prometheus-rules.yaml | sed -e 's/namespace: .*/namespace: _my-namespace_/' > prometheus-rules.yaml
+
On MacOS, use:
+
[source,shell,subs="+quotes,attributes"]
curl -s https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/{GithubVersion}/metrics/examples/prometheus/install/prometheus-rules.yaml | sed -e '' 's/namespace: .*/namespace: _my-namespace_/' > prometheus-rules.yaml

. Deploy the Prometheus resources:
+
[source,shell,subs="+quotes,attributes"]
{cmdcli} apply -f strimzi-service-monitor.yaml
{cmdcli} apply -f prometheus-rules.yaml
{cmdcli} apply -f prometheus.yaml
