// Module included in the following assemblies:
//
// assembly-kafka-bridge-quickstart.adoc

[id='proc-bridge-retrieving-latest-messages-from-consumer-{context}']
= Retrieving the latest messages from a Kafka Bridge consumer

Next, retrieve the latest messages from a Kafka Bridge consumer by requesting data from the link:https://strimzi.io/docs/bridge/latest/#_poll[records^] endpoint. In production use, HTTP clients can call this endpoint repeatedly (in a loop).

.Procedure

* Retrieve messages from the Kafka Bridge consumer (these messages were sent to the consumer in xref:proc-producing-messages-from-bridge-topics-partitions-{context}[Producing messages to topics and partitions]):
+
[source,curl,subs=attributes+]
----
curl -X GET http://localhost:8080/consumers/bridge-quickstart-consumer-group/instances/bridge-quickstart-consumer/records \
  -H 'accept: application/vnd.kafka.json.v2+json'
----
+
If the request is successful, the Kafka Bridge returns an array of messages -- describing the topic name, key, value, partition, and offset -- in the response body, along with a `200` code. Messages are retrieved from the latest offset by default.
+
[source,json,subs=attributes+]
----
INSERT JSON HERE
----
+
NOTE: If the response body is empty, produce more records to the consumer as described in xref:proc-producing-messages-from-bridge-topics-partitions-{context}[Producing messages to topics and partitions], and then try retrieving messages again. 

.What to do next

After retrieving messages from a Kafka Bridge consumer, try xref:proc-bridge-committing-consumer-offsets-to-log-{context}[committing offsets to the log].

.Additional resources

* link:https://strimzi.io/docs/bridge/latest/#_poll[GET /consumers/{groupid}/instances/{name}/records^] in the API reference documentation.
