// Module included in the following assemblies:
//
// 

[id='proc-topic-operator-with-resource-requests-limits-{context}']
= Configuring the Topic Operator with resource requests and limits

.Prerequisites

* A running Cluster Operator.

.Procedure

<<<<<<< Updated upstream
. Edit the `Kafka` resource specifying in the `Kafka.spec.topicOperator.resources` property the resource requests and limits you want the Topic Operator to have. 
* Create of update the `Kafka` resource.
=======
. Edit the `Kafka` resource specifying in the `Kafka.spec.topicOperator.resources` property the resource requests and limits you want the Topic Operator to have.
+
[source,yaml]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
spec:
  # kafka and zookeeper sections...
  topicOperator:
    resources:
      request:
        cpu: "1"
        memory: 500Mi
      limit:
        cpu: "1"
        memory: 500Mi      
----

. Create of update the `Kafka` resource.
>>>>>>> Stashed changes

.Additional resources

* For more information about the resource requirements of the Topic Operator, see xref:topic-operator-resource-requirements-str[]