// Module included in the following assemblies:
//
// assembly-using-kafka-connect-with-plugins.adoc

[id='creating-new-image-from-base-{context}']
= Creating a Docker image from the Kafka Connect base image

A container image for running Kafka Connect using {ProductName} is available on {DockerRepository} as `{DockerKafkaConnect}`. You can use this as a base image when creating your own custom image with additional plug-ins. 

.Prerequisites

NEED TO ADD CONDITIONALIZED LINKS TO THE PROCEDURES FOR DEPLOYING THE CLUSTER OPERATOR TO OCP OR KUBERNETES.


.Procedure

To create a custom image and add your connector to the `/opt/kafka/plugins` directory:

. Create a new `Dockerfile` using `{DockerKafkaConnect}` as the base image:
+
[source,subs="+quotes,attributes"]
----
FROM {DockerKafkaConnect}
USER root:root
COPY ./_my-plugins_/ /opt/kafka/plugins/
USER {DockerImageUser}
----

. Build the container image.

. Upload your custom image to the appropriate container image repository.

. Perform one of the following tasks:

* Set the `KafkaConnect.spec.image` property of the `KafkaConnect` custom resource to point to the new container image.

* Set the `STRIMZI_DEFAULT_KAFKA_CONNECT_IMAGE` variable to point to the new container image.

.Additional resources
* For more information on the `STRIMZI_DEFAULT_KAFKA_CONNECT_IMAGE` variable, see xref:ref-operators-cluster-operator-configuration-deploying-co[].
* For more information on the `KafkaConnect.spec.image property`, see xref:assembly-configuring-container-images-deployment-configuration-kafka-connect[].
