// Module included in the following assemblies:
//
// assembly-name.adoc

[id='proc-configuring-jaeger-tracer-kafka-clients-{context}']
= Initializing a Jaeger tracer for Kafka clients

Configure and initialize a Jaeger tracer by using a set of tracing environment variables.

.Procedure

Perform the following steps for each client application.

. Add Maven dependencies for Jaeger to the `pom.xml` file for the client application. For example:
+
[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.jaegertracing</groupId>
    <artifactId>jaeger-client</artifactId>
    <version>$jaegerVersion</version>
</dependency>
----

. Define the configuration of the Jaeger tracer by using xref:ref-tracing-environment-variables-{context}[tracing environment variables].

. Create the Jaeger tracer from the environment variables that you defined in step two:
+
[source,java,subs=attributes+]
----
Tracer tracer = Configuration.fromEnv().getTracer();
----
+
NOTE: For alternative ways to initialize a Jaeger tracer, see the https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-core[Java OpenTracing library^] documentation.

. Register the Jaeger tracer as a global tracer:
+
[source,java,subs=attributes+]
----
GlobalTracer.register(tracer);
----

A Jaeger tracer is now initialized for the client application.