// Module included in the following assemblies:
//
// assembly-configuring-kafka-listeners.adoc

[id='proc-restricting-access-to-listeners-using-network-policies-{context}']
= Restricting access to Kafka listeners using NetworkPolicies

.Prerequisites

* An {ProductPlatformName} cluster with SDN supporting Ingress NetworkPolicies
* A running Cluster Operator

.Procedure

. Deploy Kafka cluster and configure the pods or namespaces which will be allowed to access it in the `networkPolicyPeers` field.
An example configuration with an `tls` listener configured to allow connections from Pods which have the label `app` set to `kafka-client`:
+
[source,yaml,subs=attributes+]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
spec:
  kafka:
    # ...
    listeners:
      tls:
        networkPolicyPeers:
          - podSelector:
              matchLabels:
                app: kafka-client
    # ...
  zookeeper:
    # ...
----

. Create or update the resource.
+
ifdef::Kubernetes[]
On {KubernetesName} this can be done using `kubectl apply`:
[source,shell,subs=+quotes]
kubectl apply -f _your-file_
+
endif::Kubernetes[]
On {OpenShiftName} this can be done using `oc apply`:
+
[source,shell,subs=+quotes]
oc apply -f _your-file_

.Additional resources
* For more information about the schema, see {K8sNetworkPolicyPeerAPI} and xref:type-KafkaListeners-reference[`KafkaListeners` schema reference].
