// Module included in the following assemblies:
//
// 

[id='proc-topic-operator-with-resource-requests-limits-{context}']
= Configuring the Topic Operator with resource requests and limits

.Prerequisites

* A running Cluster Operator.

.Procedure

. Edit the `Kafka` resource specifying in the `Kafka.spec.topicOperator.resources` property the resource requests and limits you want the Topic Operator to have.
+
[source,yaml]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
spec:
  # kafka and zookeeper sections...
  topicOperator:
    resources:
      request:
        cpu: "1"
        memory: 500Mi
      limit:
        cpu: "1"
        memory: 500Mi      
----

. Create or update the `Kafka` resource.
+
ifdef::Kubernetes[]
In {KubernetesName} this can be done using `kubectl apply`.
+
.Creating or updating the `KafkaTopic` resource using `kubctl apply`
[source,shell,subs=+quotes]
----
kubectl apply -f _<your-file>_
----
+
In {OpenShiftName} this can be done using `oc apply`.
endif::Kubernetes[]
ifndef::Kubernetes[]
This can be done using `oc apply`.
+
endif::Kubernetes[]
+
.Creating or replacing the `KafkaTopic` resource using `oc apply`
[source,shell,subs=+quotes]
----
oc apply -f _<your-file>_
----

.Additional resources

* For more information about the schema of the resources object, see xref:type-Resources-reference[]
//* For more information about the resource requirements of the Topic Operator, see xref:topic-operator-resource-requirements-{context}[]