// This module is included in the following assemblies:
//
// master.adoc

[id='uninstalling-{context}']
= Uninstalling {ProductName}

This procedure describes how to uninstall {ProductName} and remove resources related to the deployment.

.Prerequisites

In order to perform this procedure, you need to identify resources specific to a deployment, such as:
+
* Secrets (Custom CAs and certificates, Kafka Connect secrets, and other secrets)
* Logging `ConfigMaps`
+
These are resources:
+
--
* Referenced by `Kafka`, `KafkaConnect` or `KafkaMirrorMaker` configuration
* Consumed by the operators
--

.Procedure

. Delete the cluster operator `Deployment`, related `CustomResourceDefinitions` and `RBAC` resources:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} delete -f install/cluster-operator
----
+
Deleting `CustomResourceDefinitions` results in the garbage collection of the corresponding custom resources (`Kafka`, `KafkaConnect` or `KafkaMirrorMaker`) and the resources dependent on them (Deployments, StatefulSets, and other dependent resources).

. Delete the resources you identified in the prerequisites.
