// This module is included in the following assemblies:
//
// assembly-upgrading-kafka-versions.adoc

[id='proc-downgrading-brokers-older-kafka-{context}']

= Downgrading brokers to an older Kafka version

NOTE: The _previous version_ is the Kafka version that you are downgrading _to_ (such as {KafkaVersionLower}). The _new version_ is the version that you are downgrading _from_ (such as {KafkaVersionHigher}).

You can downgrade a {ProductName} Kafka cluster from one version to a lower version; for example, from {KafkaVersionHigher} to {KafkaVersionLower}. Downgrading is not possible if the new version has ever used a `log.message.format.version` that is not supported by the previous version (including where the default value for `log.message.format.version` is used). 

For example:

[source,yaml,subs=attributes+]
----
apiVersion: v1alpha1
kind: Kafka
spec:
  # ...
  kafka:
    version: {KafkaVersionHigher}
    config:
      log.message.format.version: "{LogMsgVersLower}"
      # ...
----

This resource can be downgraded to Kafka version {KafkaVersionLower} because the `log.message.format.version` has not been changed.
If the `log.message.format.version` were absent (so that the parameter took its default value for a 2.1.0 broker of {LogMsgVersHigher}), or was `"{LogMsgVersHigher}"` then downgrade would not be possible.

.Prerequisites

* The Cluster Operator is up and running.
* A `Kafka` resource to be downgraded.
* The `Kafka.spec.kafka.config` has a `log.message.format.version` that is supported by the version being downgraded to.
* You have checked that your `Kafka.spec.kafka.config` contains no options which are not supported in the version of Kafka being downgraded to.

.Procedure

. Change the `Kafka.spec.kafka.version` to specify the previous version.
If the image to be used is different from the image for the given version of Kafka configured in the Cluster Operator's `STRIMZI_KAFKA_IMAGES` then configure the `Kafka.spec.kafka.image` as well.
+
For example, if downgrading from Kafka {KafkaVersionHigher} to {KafkaVersionLower}:
+
[source,yaml,subs=attributes+]
----
apiVersion: v1alpha1
kind: Kafka
spec:
  # ...
  kafka:
    version: {KafkaVersionLower} <1>
    config:
      log.message.format.version: "{LogMsgVersLower}" <2>
      # ...
----
<1> This is changed to the previous version
<2> This is unchanged
+
NOTE: It is necessary to format the value of `log.message.format.version` as a string to prevent it from being interpreted as a number.

. Wait for the Cluster Operator to downgrade the cluster.
If both the previous and new versions of Kafka have a different interbroker protocol version, check the Cluster Operator logs for an `INFO` level message  in the following format:
+
[source,subs="+quotes"]
----
Reconciliation #_<num>_(watch) Kafka(_<namespace>_/_<name>_): Kafka version downgrade from _<from-version>_ to _<to-version>_, phase 2 of 2 completed
----
+
Alternatively, if both the previous and new versions of Kafka have the same interbroker protocol version look in the Cluster Operator logs for an `INFO` level message in the following format:
+
[source,subs="+quotes"]
----
Reconciliation #_<num>_(watch) Kafka(_<namespace>_/_<name>_): Kafka version downgrade from _<from-version>_ to _<to-version>_, phase 1 of 1 completed
----
+
For example, using `grep`:
+
[source,shell,subs="+quotes"]
----
oc logs -f _<cluster-operator-pod-name>_ | grep -E "Kafka version downgrade from [0-9.]+ to [0-9.]+, phase ([0-9]+) of \1 completed"
----

. Downgrade each client application to use the previous version of the client libraries.