[id='deleting-a-topic-{context}']
= Deleting a topic

This procedure describes how to delete a Kafka topic using a `KafkaTopic` {ProductPlatformName} resource.

.Prerequisites

* A running Kafka cluster.
* A running Topic Operator, either deployed by the Cluster Operator using the `Kafka.spec.topicOperator` property, or deployed standalone.
* An existing `KafkaTopic` to be deleted.

.Procedure

. Delete the `KafkaTopic` resource in {ProductPlatformName}.
+
ifdef::Kubernetes[]
In {KubernetesName} this can be done using `kubectl`
+
.Replacing the `KafkaTopic` resource using `kubctl delete`
[source,shell,subs=+quotes]
----
kubectl delete kafkatopic _<your-topic-name>_
----
+
In {OpenShiftName} this can be done using `oc`
endif::Kubernetes[]
ifndef::Kubernetes[]
This can be done using `oc`
+
endif::Kubernetes[]
+
.Replacing the `KafkaTopic` resource using `oc delete`
[source,shell,subs=+quotes]
----
oc delete kafkatopic _<your-topic-name>_
----
+
NOTE: Whether the topic can actually be deleted depends on the value of the `delete.topic.enable` Kafka broker configuration, specified in the `Kafka.spec.kafka.config` property.
