// Module included in the following assemblies:
//
// assembly-kafka-bridge-quickstart.adoc

[id='proc-exposing-kafka-bridge-service-local-machine-{context}']
= Exposing the Kafka Bridge Service to your local machine

Create an OpenShift Route to expose the {ProductName} Kafka Bridge Service to your local machine on port 8080.

.Prerequisites

* The Kafka Bridge is deployed to your Kubernetes cluster.

.Procedure

. In a text editor, create a YAML definition for an unsecured OpenShift Route:
+
[source,yaml,subs=attributes+]
----
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: <bridge-name>
  labels:
    app: <bridge-name>
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: <bridge-name>-bridge-service
    weight: 100
    / ...
----
In the three `<bridge-name>` fields, specify the name of the Kafka Bridge that you deployed to your Kubernetes cluster.

. Save the file to the `examples/kafka-bridge` directory as `bridge-quickstart-route.yaml`.

. Create the Route in your Kubernetes cluster:
+
[source,shell,subs=attributes+]
----
oc apply -f examples/kafka-bridge/bridge-quickstart-route.yaml
----

. Retrieve the address of the route; you will use the address as the `<bridge-address>` parameter in the remainder of this quick start.
+
[source,shell,subs=attributes+]
----
export BRIDGE="$(oc get routes my-bridge -o jsonpath='{.status.ingress[0].host}')"
----
