// Module included in the following assemblies:
//
// assembly-cluster-operator.adoc

[id='deploying-cluster-operator-to-watch-multiple-namespaces{context}']
= Deploying the Cluster Operator to watch multiple namespaces

.Prerequisites

* This procedure requires use of a Kubernetes user account which is able to create `CustomResourceDefinitions`, `ClusterRoles` and `ClusterRoleBindings`.
Use of Role Base Access Control (RBAC) in the Kubernetes cluster usually means that permission to create, edit, and delete these resources is limited to Kubernetes cluster administrators, such as `system:admin`.
* Edit the installation files according to the namespace the Cluster Operator is going to be installed in.
+
include::frag-cluster-operator-namespace-sed.adoc[]

.Procedure

. Edit the file `install/cluster-operator/050-Deployment-strimzi-cluster-operator.yaml` and in the environment variable `STRIMZI_NAMESPACE` list all the namespaces where Cluster Operator should watch for resources.
For example:
+
[source,yaml,subs="attributes"]
----
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  template:
    spec:
      serviceAccountName: strimzi-cluster-operator
      containers:
      - name: strimzi-cluster-operator
        image: {DockerClusterOperator}
        imagePullPolicy: IfNotPresent
        env:
        - name: STRIMZI_NAMESPACE
          value: watched-namespace-1,watched-namespace-2,watched-namespace-3
----

. For all namespaces which should be watched by the Cluster Operator (`watched-namespace-1`, `watched-namespace-2`, `watched-namespace-3` in the above example), install the `RoleBindings`.
Replace the `_watched-namespace_` with the namespace used in the previous step.
+
This can be done using `kubectl apply`:
[source,shell,subs="+quotes,attributes+"]
kubectl apply -f install/cluster-operator/020-RoleBinding-strimzi-cluster-operator.yaml -n _watched-namespace_
kubectl apply -f install/cluster-operator/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml -n _watched-namespace_
kubectl apply -f install/cluster-operator/032-RoleBinding-strimzi-cluster-operator-topic-operator-delegation.yaml -n _watched-namespace_

. Deploy the Cluster Operator
+
This can be done using `kubectl apply`:
[source,shell,subs="+quotes,attributes+"]
kubectl apply -f install/cluster-operator -n _my-namespace_
