// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// Base the file name and the ID on the module title. For example:
// * file name: assembly-cluster-operator.adoc
// * ID: [id='cluster-operator-{context}']
// * Title: = Configure Cluster Operator

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.

include::common/attributes.adoc[]

[id='operator-configuration-{context}']
= Configuring Cluster Operator

You can configure the Cluster Operator using the following environment variables.

.Prerequisites

//Add prerequisites if any

.Procedure

//Add a procedure for defining clusterroles

[[STRIMZI_NAMESPACE]] `STRIMZI_NAMESPACE`:: Required. A comma-separated list of namespaces that the operator should
operate in. The Cluster Operator deployment might use the link:https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#the-downward-api[{KubernetesName} Downward API^]
to set this automatically to the namespace the Cluster Operator is deployed in. See the example below:
+
[source,yaml,options="nowrap"]
----
env:
  - name: STRIMZI_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
----

[id=`STRIMZI_FULL_RECONCILIATION_INTERVAL_MS`] `STRIMZI_FULL_RECONCILIATION_INTERVAL_MS`:: Optional, default: 120000 ms. The interval between periodic reconciliations, in milliseconds.


[id=`STRIMZI_OPERATION_TIMEOUT_MS`] `STRIMZI_OPERATION_TIMEOUT_MS`:: Optional, default: 300000 ms. The timeout for internal operations, in milliseconds. This value should be
increased when using {ProductName} on clusters where regular {ProductPlatformName} operations take longer than usual. For example, slow downloading of container images.

[id=`STRIMZI_DEFAULT_KAFKA_IMAGE`] `STRIMZI_DEFAULT_KAFKA_IMAGE`:: Optional, default `strimzi/kafka:latest`.
The image name to use as a default when deploying Kafka, if
no image is specified as the `kafka-image` in the xref:kafka-config-map-details-{context}[Kafka cluster ConfigMap].

[id=`STRIMZI_DEFAULT_KAFKA_INIT_IMAGE`] `STRIMZI_DEFAULT_KAFKA_INIT_IMAGE`:: Optional, default `strimzi/kafka-init:latest`.
The image name to use as default for the init container started before the broker for doing initial configuration work (that is, rack support), if no image is specified as the `kafka-init-image` in the xref:kafka-config-map-details-{context}[Kafka cluster ConfigMap].

[id=`STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE`] `STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE`:: Optional, default `strimzi/kafka-stunnel:latest`.
The image name to be used as a default when deploying the sidecar container which provides TLS support for Kafka if
no image is specified as the `spec.kafka.tlsSidecar.image` in the xref:kafka-config-map-details-{context}[Kafka cluster ConfigMap].

[id=`STRIMZI_DEFAULT_KAFKA_CONNECT_IMAGE`] `STRIMZI_DEFAULT_KAFKA_CONNECT_IMAGE`:: Optional, default `strimzi/kafka-connect:latest`.
The image name to use as a default when deploying Kafka Connect, if
no image is specified as the `image` in the
xref:kafka_connect_config_map_details[Kafka Connect configuration].

[id=`STRIMZI_DEFAULT_KAFKA_CONNECT_S2I_IMAGE`] `STRIMZI_DEFAULT_KAFKA_CONNECT_S2I_IMAGE`:: Optional, default `strimzi/kafka-connect-s2i:latest`.
The image name to use as a default when deploying Kafka Connect S2I, if
no image is specified as the `image` in the cluster ConfigMap.

[id=`STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE`] `STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE`:: Optional, default `strimzi/topic-operator:latest`.
The image name to use as a default when deploying the topic operator, if
no image is specified as the `image` in the xref:topic_operator_json_config-{context}[Topic Operator]
of the Kafka cluster ConfigMap.

[id=`STRIMZI_DEFAULT_ZOOKEEPER_IMAGE`] `STRIMZI_DEFAULT_ZOOKEEPER_IMAGE`:: Optional, default `strimzi/zookeeper:latest`.
The image name to use as a default when deploying Zookeeper, if
no image is specified as the `zookeeper-image` in the xref:kafka-config-map-details-{context}[Kafka cluster ConfigMap].

[id=`STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE`] `STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE`:: Optional, default `strimzi/zookeeper-stunnel:latest`.
The image name to use as a default when deploying the sidecar container which provides TLS support for Zookeeper, if
no image is specified as the `spec.zookeeper.tlsSidecar.image` in the xref:kafka-config-map-details-{context}[Kafka cluster ConfigMap].

[id=`STRIMZI_LOG_LEVEL`] `STRIMZI_LOG_LEVEL`:: Optional, default `INFO`.
The level for printing logging messages. The value can be set to: `ERROR`, `WARNING`, `INFO`, `DEBUG` and `TRACE`.

[id=`STRIMZI_DEFAULT_TLS_SIDECAR_TOPIC_OPERATOR_IMAGE`] `STRIMZI_DEFAULT_TLS_SIDECAR_TOPIC_OPERATOR_IMAGE`:: Optional, default `strimzi/topic-operator-stunnel:latest`.
The image name to use as a default when deploying the sidecar container which provides TLS support for the Topic Operator, if
no image is specified as the `spec.topicOperator.tlsSidecar.image` in the xref:kafka-config-map-details-{context}[Kafka cluster ConfigMap].
