// This assembly is included in the following assemblies:
//
// assembly-upgrade.adoc.adoc


[id='proc-upgrading-cluster-operator-{context}']
= Upgrading the Cluster Operator

This procedure describes how to upgrade the Cluster Operator from a previous version of {ProductName}.

.Prerequisites

* An already installed version of the {ProductName} Cluster Operator.
* A new version of the {ProductName} Cluster Operator is available.

.Procedure

. Determine the version of Kafka being used in all existing Kafka clusters, Kafka Connect and Kafka Mirror Maker deployments. Update the custom resources for each of these to include the Kafka version currently being used. For example, for `Kafka` resources:
+
[yaml]
----
kind: Kafka
# ...
spec:
  kafka:
    version: 2.0.0
    # ...
  # ...
----
+
Similarly, for `KafkaConnect` resources:
+
[yaml]
----
kind: KafkaConnect
# ...
spec:
  version: 2.0.0
  # ...
----
+
And, for `KafkaMirrorMaker` resources:
+
[yaml]
----
kind: KafkaConnect
# ...
spec:
  version: 2.0.0
  # ...
----


. Determine how the running Cluster Operator differs from the default configuration provided in the release artefacts of the previous version downloaded from {ReleaseDownload}.
You can do this using `diff`.
For example if the original release artefacts are in the `old-install` directory:
+
[shell]
----
diff -r old-install/install/cluster-operator $(oc TODO)
----


. Determine the differences between the old and new provided configurations of the Cluster Operator. 
You can do this using `diff`, for example
+
[shell]
----
diff -r old-install/install/cluster-operator new-install/install/cluster-operator
----


. Consult the release notes of the new version of {ProductName} to discover removed or deprecated Cluster Operator configuration settings.


. Copy the release artefacts of the new version into a separate directory, so you can modify them
+
[shell]
----
cp -r downloaded-new modified-new
----


. Using the information from the previous steps, modify the new provided configuration (in the `install/cluster-operator` directory) of the Cluster Operator to retain any custom settings you have made in your existing installation, taking into account settings that have been changed, deprecated and removed between the two releases. 

. Apply the configuration
+
[shell]
----
oc apply -f modified-new
----

