// Module included in the following assemblies:
//
// assembly-deployment-configuration-kafka-connect-s2i.adoc

[id='ref-list-of-kafka-cluster-resources-{context}']
= List of resources created as part of Kafka Connect cluster with Source2Image support

The resources created by the Cluster Operator in the {ProductPlatformName} cluster will be the following:

<connect-cluster-name>-connect-source:: ImageStream which is used as the base image for the newly-built Docker images.
<connect-cluster-name>-connect:: BuildConfig which is responsible for building the new Kafka Connect Docker images.
<connect-cluster-name>-connect:: ImageStream where the newly built Docker images will be pushed.
<connect-cluster-name>-connect:: DeploymentConfig which is in charge of creating the Kafka Connect worker node pods.
<connect-cluster-name>-connect:: Service which exposes the REST interface for managing the Kafka Connect cluster.
<connect-cluster-name>-config:: ConfigMap which contains the Kafka Connect ancillary configuration and is mounted as a volume by the Kafka broker pods

// TODO:
// Verify and add missing resources