// Module included in the following assemblies:
//
// topic-operator.adoc

[id='topic-operator-usage-recommendations-{context}']
= Topic Operator usage recommendations

When working with topics, be consistent and always operate on either `KafkaTopic` resources or topics directly. Avoid routinely switching between both methods for a given topic.

Use topic names that reflect the nature of the topic, and remember that names cannot be changed later.

If creating a topic in Kafka, use a name that is a valid {KubernetesName} resource name, otherwise the Topic Operator will need to create the corresponding `KafkaTopic` with a different name which obeys the {KubernetesName} rules.

.Kafka topic naming conventions

Kafka and {KubernetesName} impose their own validation rules for the naming of topics in Kafka and `KafkaTopic.metadata.name` respectively.
So there are valid naming conventions for each which are invalid in the other.

The `spec.topicName` property provides a way to create a name for a topic in Kafka that would be a valid name for `KafkaTopic` in {KubernetesName}, link:https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md[(according to the recommendations for identifiers and names in {KubernetesName})^].

The `spec.topicName` property inherits Kafka naming validation rules:

* The name must not be longer than 249 characters
* Valid characters for Kafka topics are ASCII alphanumerics, ‘.’, ‘_’, and ‘-‘

`spec.topicName` must not be changed.

For example:

[source,yaml]
----
KafkaTopic.metadata.name=A with KafkaTopic.spec.name=topicName-1
----

cannot be changed to

[source,yaml]
----
KafkaTopic.metadata.name=A with KafkaTopic.spec.topicName=name-2
----

NOTE: Some Kafka client applications, such as Kafka Streams, can create topics in Kafka programmatically. When those topics have a name that is an invalid {KubernetesName} resource name, the Topic Operator gives them a valid name based on the Kafka name. Invalid characters are replaced and a hash appended to the name.
