// Module included in the following assemblies:
//
// assembly-storage.adoc

[id='ref-jbod-storage-{context}']
= JBOD storage

The JBOD storage allows to provide more volumes to the Kafka brokers, for storing data.
It represents a way for providing more space and having better performance.

To use JBOD storage, the `type` has to be set to `jbod`.
A JBOD storage is described by one or more volumes and each of them can be an xref:ref-ephemeral-storage-{context}[Ephemeral] or a xref:ref-persistent-storage-{context}[Persistent] one.
Each volume declaration follows the same rules and constraints as for Ephemeral and Persistent storage.
The JBOD storage provides a way for putting together more of them.

Using the `volumes` property, it is possible to declare the disks which make the JBOD storage.

.Example fragment of JBOD storage configuration
[source,yaml]
----
# ...
storage:
  type: jbod
  volumes:
  - id: 0
    type: persistent-claim
    size: 100Gi
    deleteClaim: false
  - id: 1
    type: persistent-claim
    size: 100Gi
    deleteClaim: false
# ...
----

It is possible to update each volume following the rules of each declared Ephemeral and Persistent volume.
It is not possible to change the `id` property for a volume.
It is not possible to add or remove volumes from a JBOD storage configuration.

When Persistent storage is used for declaring volumes, the naming schema for the created Persistent Volume Claims is the following:

`data-_id_-_cluster-name_-kafka-_idx_`::
Persistent Volume Claim for the volume `_id_` used for storing data for the Kafka broker pod `_idx_`.
