
// This assembly is included in the following assemblies:
//
// assembly-metrics-setup.adoc
[id='ref-metrics-config-files-{context}']

= Example Metrics files

[source]
--
metrics
├── grafana-install
│   ├── grafana.yaml <1>
├── grafana-dashboards <2>
│   ├── strimzi-kafka-connect.json
│   ├── strimzi-kafka.json
│   └── strimzi-zookeeper.json
├── kafka-connect-metrics.yaml <3>
├── kafka-metrics.yaml <4>
├── prometheus-additional-properties
│   └── prometheus-additional.yaml <5>
├── prometheus-alertmanager-config
│   └── alert-manager-config.yaml <6>
└── prometheus-install
    ├── alert-manager.yaml <7>
    ├── prometheus-rules.yaml <8>
    ├── prometheus.yaml <9>
    └── strimzi-service-monitor.yaml <10>
--
<1> Grafana docker image
<2> Grafana dashboard configuration
<3> Metrics configuration that defines Prometheus JMX Exporter relabeling rules for Kafka Connect
<4> Metrics configuration that defines Prometheus JMX Exporter relabeling rules for Kafka and ZooKeeper
<5> Configuration to add roles for service monitoring
<6> Hook definitions for sending notifications through Alertmanager
<7> Resources for deploying and configuring Alertmanager
<8> Alerting rules examples for use with Prometheus Alertmanager (deployed with Prometheus)
<9> Prometheus docker image
<10> Prometheus job definitions to scrape metrics data
