/*
 * Copyright Strimzi authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */
package io.strimzi.operator.cluster.model;

import io.strimzi.operator.cluster.model.clustersecurity.kafka.KafkaClusterSecurityContext;
import io.strimzi.operator.cluster.model.clustersecurity.kafka.MtlsAuthenticationConfiguration;
import io.strimzi.operator.cluster.model.clustersecurity.kafka.TlsEncryptionConfiguration;
import io.strimzi.operator.common.Reconciliation;

import java.io.PrintWriter;
import java.io.StringWriter;

/**
 * This class is used to generate the Kafka agent configuration. The configuration is later passed using a ConfigMap to
 * the Kafka nodes. This class is using the builder pattern to make it easy to test the different parts etc. To
 * generate the configuration file, it is using the PrintWriter.
 */
public class KafkaAgentConfigurationBuilder {
    private final StringWriter stringWriter = new StringWriter();
    private final PrintWriter writer = new PrintWriter(stringWriter);
    private final Reconciliation reconciliation;
    private final NodeRef node;

    /**
     * Constructor of the Kafka Agent configuration builder
     *
     * @param reconciliation    The reconciliation
     * @param node              NodeRef instance
     */
    public KafkaAgentConfigurationBuilder(Reconciliation reconciliation, NodeRef node) {
        printHeader();
        this.reconciliation = reconciliation;
        this.node = node;
    }

    /**
     * Configures the KafkaAgent security
     *
     * @param securityContext   Kafka cluster Security Context
     *
     * @return Returns the builder instance
     */
    public KafkaAgentConfigurationBuilder withSecurity(KafkaClusterSecurityContext securityContext)   {
        printSectionHeader("Security configuration");

        if (securityContext.encryption() instanceof TlsEncryptionConfiguration)   {
            writer.println("namespace=" + reconciliation.namespace());
            writer.println("sslKeyStoreSecretName=" + node.podName());

            if (securityContext.authentication() instanceof MtlsAuthenticationConfiguration) {
                writer.println("sslTrustStoreSecretName=" + reconciliation.name() + "-cluster-ca-cert");
            }
        }

        return this;
    }

    /**
     * Internal method which prints the section header into the configuration file. This makes it more human-readable
     * when looking for issues in running pods etc.
     *
     * @param sectionName   Name of the section for which is this header printed
     */
    private void printSectionHeader(String sectionName)   {
        writer.println("##########");
        writer.println("# " + sectionName);
        writer.println("##########");
    }

    /**
     * Prints the file header which is on the beginning of the configuration file.
     */
    private void printHeader()   {
        writer.println("##############################");
        writer.println("##############################");
        writer.println("# This file is automatically generated by the Strimzi Cluster Operator");
        writer.println("# Any changes to this file will be ignored and overwritten!");
        writer.println("##############################");
        writer.println("##############################");
        writer.println();
    }

    /**
     * Generates the configuration template as String
     *
     * @return String with the Kafka agent configuration template
     */
    public String build()  {
        return stringWriter.toString();
    }
}
