/*
 * Copyright Strimzi authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */
package io.strimzi.operator.common.model;

import io.strimzi.api.kafka.model.common.CertificateAuthority;
import io.strimzi.api.kafka.model.common.CertificateExpirationPolicy;

/**
 * Representation of the Certificate Authority configuration which encapsulates applying the default values
 */
public class CaConfig {
    private final int validityDays;
    private final int renewalDays;
    private final boolean generateCa;
    private final boolean generateSecretOwnerRef;
    private final CertificateExpirationPolicy certificateExpirationPolicy;

    /**
     * Constructor to create CaConfig with default values
     * @return CaConfig initialised with default values
     */
    public static CaConfig createDefault() {
        return new CaConfig(null);
    }

    /**
     * CaConfig constructor
     * @param certificateAuthority CertificateAuthority configuration from the Custom Resource
     */
    public CaConfig(CertificateAuthority certificateAuthority) {
        this.validityDays = certificateAuthority != null && certificateAuthority.getValidityDays() > 0 ? certificateAuthority.getValidityDays()
                : CertificateAuthority.DEFAULT_CERTS_VALIDITY_DAYS;
        this.renewalDays = certificateAuthority != null && certificateAuthority.getRenewalDays() > 0 ? certificateAuthority.getRenewalDays()
                : CertificateAuthority.DEFAULT_CERTS_RENEWAL_DAYS;
        this.generateCa = certificateAuthority == null || certificateAuthority.isGenerateCertificateAuthority();
        this.generateSecretOwnerRef = certificateAuthority == null || certificateAuthority.isGenerateSecretOwnerReference();
        this.certificateExpirationPolicy = certificateAuthority != null && certificateAuthority.getCertificateExpirationPolicy() != null
                ? certificateAuthority.getCertificateExpirationPolicy()
                : CertificateExpirationPolicy.RENEW_CERTIFICATE;
    }

    /**
     * CaConfig constructor
     * @param validityDays Number of days for which the CA certificate should be value
     * @param renewalDays Number of day before expiration, when the certificate should be renewed
     * @param generateCa Flag indicating whether the Clients CA should be generated by Strimzi or not
     */
    public CaConfig(int validityDays, int renewalDays, boolean generateCa) {
        this.validityDays = validityDays;
        this.renewalDays = renewalDays;
        this.generateCa = generateCa;
        this.generateSecretOwnerRef = true;
        this.certificateExpirationPolicy = CertificateExpirationPolicy.RENEW_CERTIFICATE;

    }
    /**
     * Get validity days
     * @return Number of days for which the CA certificate should be value.
     */
    public int getValidityDays() {
        return validityDays;
    }

    /**
     * Get renewal days
     * @return Number of day before expiration, when the certificate should be renewed.
     */
    public int getRenewalDays() {
        return renewalDays;
    }

    /**
     * Get flag indicating whether the CA should be generated by Strimzi or not
     * @return Whether the CA should be generated by Strimzi or not.
     */
    public boolean isGenerateCa() {
        return generateCa;
    }

    /**
     * Get flag indicating whether the CA Secret owner reference should be generated by Strimzi or not
     * @return Whether the CA Secret owner reference should be generated by Strimzi or not.
     */
    public boolean isGenerateSecretOwnerRef() {
        return generateSecretOwnerRef;
    }

    /**
     * Get certificate expiration policy
     * @return Policy defining the behavior when the CA expires (renewal or completely replacing the CA).
     */
    public CertificateExpirationPolicy getCertificateExpirationPolicy() {
        return certificateExpirationPolicy;
    }
}
