// This assembly is included in:
//
// overview/overview.adoc

[id="metrics-overview_{context}"]
= Monitoring Kafka

[role="_abstract"]
Monitoring data allows you to monitor the performance and health of Strimzi.
You can configure your deployment to capture metrics data for analysis and notifications.

Metrics data is useful when investigating issues with connectivity and data delivery.
For example, metrics data can identify under-replicated partitions or the rate at which messages are consumed.
Alerting rules can provide time-critical notifications on such metrics through a specified communications channel.
Monitoring visualizations present real-time metrics data to help determine when and how to update the configuration of your deployment.
Example metrics configuration files are provided with Strimzi.

You can employ the following tools for metrics and monitoring:

Prometheus:: {PrometheusHome} pulls metrics from Kafka, Kafka Connect, and other clusters.
The Prometheus *Alertmanager* plugin handles alerts and routes them to a notification service.
Kafka Exporter:: {kafka-exporter-project} adds additional Prometheus metrics.
Grafana:: {GrafanaHome} provides dashboard visualizations of Prometheus metrics.
OpenTelemetry:: {OpenTelemetry} complements the gathering of metrics data by providing a facility for end-to-end tracking of messages through Strimzi.
Cruise Control:: {CruiseControlProject} monitors data distribution and performs data rebalances, based on workload data, across a Kafka cluster.