// This module is included in:
//
// overview/assembly-configuration-points.adoc

[id="con-configuration-points-mm-{context}"]
= Kafka MirrorMaker configuration
Kafka MirrorMaker (also referred to as MirrorMaker 1) uses producers and consumers to replicate data across clusters as follows:

* Consumers consume data from the source cluster
* Producers output data to the target cluster

Consumer and producer configuration includes any required authentication and encryption settings.
An `include` property defines the topics to mirror from the source to the target cluster.

NOTE: MirrorMaker was deprecated in Kafka 3.0.0 and will be removed in Kafka 4.0.0.
As a consequence, the Strimzi `KafkaMirrorMaker` custom resource which is used to deploy MirrorMaker has been deprecated. 
The `KafkaMirrorMaker` resource will be removed from Strimzi when Kafka 4.0.0 is adopted.

[discrete]
== Key Consumer configuration

Consumer group identifier:: The consumer group ID for a MirrorMaker consumer so that messages consumed are assigned to a consumer group.
Number of consumer streams:: A value to determine the number of consumers in a consumer group that consume a message in parallel.
Offset commit interval:: An offset commit interval to set the time between consuming and committing a message.

[discrete]
== Key Producer configuration

Cancel option for send failure:: You can define whether a message send failure is ignored or MirrorMaker is terminated and recreated.

[discrete]
== Example YAML showing MirrorMaker configuration
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: {KafkaMirrorMakerApiVersion}
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
spec:
  # ...
  consumer:
    bootstrapServers: my-source-cluster-kafka-bootstrap:9092
    groupId: "my-group"
    numStreams: 2
    offsetCommitInterval: 120000
    # ...
  producer:
    # ...
    abortOnSendFailure: false
    # ...
  include: "my-topic|other-topic"
  # ...
----
