// Module included in the following assemblies:
//
// deploying/assembly_deploy-tasks-prep.adoc

[id='downloads-{context}']
= Downloading Strimzi release artifacts

[role="_abstract"]
ifdef::Downloading[]
To use deployment files to install Strimzi, download the release artifacts from {ReleaseDownload}.

Download the `strimzi-_<version>_.zip` or `strimzi-_<version>_.tar.gz` archive file.
endif::Downloading[]
ifndef::Downloading[]
To use deployment files to install Strimzi, download and extract the *{ProductName} _<version>_ installation and example files* archive from the {ZipDownload}.
endif::Downloading[]

Strimzi release artifacts include sample YAML files to help you deploy the components of Strimzi to Kubernetes, perform common operations,
and configure your Kafka cluster.

Use `kubectl` to deploy the Cluster Operator from the `install/cluster-operator` folder of the downloaded ZIP file.
For more information about deploying and configuring the Cluster Operator, see xref:cluster-operator-{context}[].

In addition, if you want to use standalone installations of the Topic and User Operators with a Kafka cluster that is not managed by the Strimzi Cluster Operator, you can deploy them from the `install/topic-operator` and `install/user-operator` folders.

NOTE: Additionally, Strimzi container images are available through the {DockerRepository}.
However, we recommend that you use the YAML files provided to deploy Strimzi.
