// Module included in the following assemblies:
//
// deploying/assembly_deploy-tasks-prep.adoc

[id='downloads-{context}']
= Downloading Strimzi release artifacts

ifdef::Downloading[]
To install Strimzi, download the release artifacts from {ReleaseDownload}.
endif::Downloading[]

ifndef::Downloading[]
To install Strimzi, download and extract the release artifacts from the `amq-streams-__<version>__-ocp-install-examples.zip` file from the {ZipDownload}.
endif::Downloading[]

Strimzi release artifacts include sample YAML files to help you deploy the components of Strimzi to Kubernetes, perform common operations,
and configure your Kafka cluster.

Use `kubectl` to deploy Strimzi Cluster Operator from the `install/cluster-operator` folder from the downloaded zip file.
In addition, if you want to use stand-alone installations of the Topic and User Operators with a Kafka cluster not managed by the Strimzi Cluster Operator, you can deploy them from the `install/topic-operator` and `install/user-operator` folders.

NOTE: Additionally, Strimzi container images are available through the {DockerRepository}.
However, we recommend that you use the YAML files provided to deploy Strimzi.
