// Module included in the following assemblies:
//
// deploying/assembly_deploy-cluster-operator.adoc

[id='con-cluster-operator-watch-options-{context}']

= Specifying the namespaces the Cluster Operator watches

[role="_abstract"]
The Cluster Operator watches for updates in the namespaces where the Kafka resources are deployed. 
When you deploy the Cluster Operator, you specify which namespaces to watch.
You can specify the following namespaces:

* xref:deploying-cluster-operator-{context}[A single namespace] (the same namespace containing the Cluster Operator)
* xref:deploying-cluster-operator-to-watch-multiple-namespaces-{context}[Multiple namespaces]
* xref:deploying-cluster-operator-to-watch-whole-cluster-{context}[All namespaces]

NOTE: The Cluster Operator can watch one, multiple, or all namespaces in a Kubernetes cluster.
The Topic Operator and User Operator watch for `KafkaTopic` and `KafkaUser` resources in a single namespace. For more information, see link:{BookURLConfiguring}#con-operators-namespaces-str[Watching namespaces with Strimzi operators^].

The Cluster Operator watches for changes to the following resources:

* `Kafka` for the Kafka cluster.
* `KafkaConnect` for the Kafka Connect cluster.
* `KafkaConnector` for creating and managing connectors in a Kafka Connect cluster.
* `KafkaMirrorMaker` for the Kafka MirrorMaker instance.
* `KafkaMirrorMaker2` for the Kafka MirrorMaker 2.0 instance.
* `KafkaBridge` for the Kafka Bridge instance.
* `KafkaRebalance` for the Cruise Control optimization requests.

When one of these resources is created in the Kubernetes cluster, the operator gets the cluster description from the resource and starts creating a new cluster for the resource by creating the necessary Kubernetes resources, such as StatefulSets, Services and ConfigMaps.

Each time a Kafka resource is updated, the operator performs corresponding updates on the Kubernetes resources that make up the cluster for the resource.

Resources are either patched or deleted, and then recreated in order to make the cluster for the resource reflect the desired state of the cluster.
This operation might cause a rolling update that might lead to service disruption.

When a resource is deleted, the operator undeploys the cluster and deletes all related Kubernetes resources.
