// Module included in the following assemblies:
//
// deploying/assembly_deploy-kafka-connect.adoc

[id='deploying-kafka-connect-{context}']
= Deploying Kafka Connect to your Kubernetes cluster

[role="_abstract"]
This procedure shows how to deploy a Kafka Connect cluster to your Kubernetes cluster using the Cluster Operator.

A Kafka Connect cluster is implemented as a `Deployment` with a configurable number of nodes (also called _workers_) that distribute the workload of connectors as _tasks_ so that the message flow is highly scalable and reliable.

The deployment uses a YAML file to provide the specification to create a `KafkaConnect` resource.

Strimzi provides xref:deploy-examples-{context}[example configuration files].
In this procedure, we use the following example file:

* `examples/connect/kafka-connect.yaml`

.Prerequisites

* xref:deploying-cluster-operator-str[The Cluster Operator must be deployed.]
* xref:deploying-kafka-cluster-str[Running Kafka cluster.]

.Procedure

. Deploy Kafka Connect to your Kubernetes cluster.
Use the `examples/connect/kafka-connect.yaml` file to deploy Kafka Connect.
+
[source,shell,subs="attributes+"]
----
kubectl apply -f examples/connect/kafka-connect.yaml
----

. Check the status of the deployment:
+
[source,shell,subs="+quotes"]
----
kubectl get deployments -n _<my_cluster_operator_namespace>_
----
+
.Output shows the deployment name and readiness
[source,shell,subs="+quotes"]
----
NAME                        READY  UP-TO-DATE  AVAILABLE
my-connect-cluster-connect  1/1    1           1
----
+
`my-connect-cluster` is the name of the Kafka Connect cluster.
+
`READY` shows the number of replicas that are ready/expected.
The deployment is successful when the `AVAILABLE` output shows `1`.

[role="_additional-resources"]
.Additional resources
link:{BookURLConfiguring}#assembly-kafka-connect-str[Kafka Connect cluster configuration^]
