// Module included in the following assemblies:
//
// deploying/assembly_deploy-kafka-bridge.adoc

[id='deploying-kafka-bridge-{context}']
= Deploying Kafka Bridge to your Kubernetes cluster

[role="_abstract"]
This procedure shows how to deploy a Kafka Bridge cluster to your Kubernetes cluster using the Cluster Operator.

The deployment uses a YAML file to provide the specification to create a `KafkaBridge` resource.

Strimzi provides xref:config-examples-{context}[example configuration files].
In this procedure, we use the following example file:

* `examples/bridge/kafka-bridge.yaml`

.Prerequisites

* xref:deploying-cluster-operator-str[The Cluster Operator must be deployed.]

.Procedure

. Deploy Kafka Bridge to your Kubernetes cluster:
+
[source,shell,subs="attributes+"]
----
kubectl apply -f examples/bridge/kafka-bridge.yaml
----

. Check the status of the deployment:
+
[source,shell,subs="+quotes"]
----
kubectl get pods -n _<my_cluster_operator_namespace>_
----
+
.Output shows the deployment name and readiness
[source,shell,subs="+quotes"]
----
NAME                       READY  STATUS   RESTARTS
my-bridge-bridge-<pod_id>  1/1    Running  0
----
+
`my-bridge` is the name of the Kafka Bridge cluster.
+
A pod ID identifies each pod created.
+
With the default deployment, you install a single Kafka Bridge pod.
+
`READY` shows the number of replicas that are ready/expected.
The deployment is successful when the `STATUS` displays as `Running`.

[role="_additional-resources"]
.Additional resources

* xref:con-config-kafka-bridge-str[Kafka Bridge cluster configuration]
* link:{BookURLBridge}[Using the Strimzi Kafka Bridge^]
