:_mod-docs-content-type: PROCEDURE

// Module included in the following assemblies:
//
// deploying/assembly_deploy-access-operator.adoc

[id='deploying-access-operator-to-watch-multiple-namespaces-{context}']
= Deploying the Access Operator to watch multiple namespaces

[role="_abstract"]
This procedure shows how to deploy the Access Operator to watch Strimzi resources across multiple namespaces in your Kubernetes cluster.

.Prerequisites

* You need an account with permission to create and manage `CustomResourceDefinition` and RBAC (`ClusterRole`, and `RoleBinding`) resources.

.Procedure

. Edit the installation files to use the namespace the Access Operator is going to be installed into.
+
For example, in this procedure the Access Operator is installed into the namespace `my-access-operator-namespace`.
+
include::../../shared/snip-access-operator-namespace-sed.adoc[]

. Edit the `install/050-Deployment.yaml` file
to add a list of all the namespaces the Cluster Operator will watch to the `STRIMZI_NAMESPACE` environment variable.
+
For example, in this  procedure the Access Operator will watch the namespaces `watched-namespace-1`, `watched-namespace-2`, `watched-namespace-3`.
+
[source,yaml,subs="attributes"]
----
apiVersion: apps/v1
kind: Deployment
spec:
  # ...
  template:
    spec:
      serviceAccountName: strimzi-access-operator
      containers:
      - name: strimzi-access-operator
        image: {DockerAccessOperator}
        imagePullPolicy: IfNotPresent
        env:
        - name: STRIMZI_NAMESPACE
          value: watched-namespace-1,watched-namespace-2,watched-namespace-3
----

. For each namespace listed, install the `RoleBindings`.
+
In this example, we replace `watched-namespace` in these commands with the namespaces listed in the previous step,
repeating them for `watched-namespace-1`, `watched-namespace-2`, `watched-namespace-3`:
+
[source,shell]
kubectl create -f install/060-RoleBinding-strimzi-acces-operator.yaml -n <watched_namespace>

. Deploy the Access Operator:
+
[source,shell,subs="+quotes,attributes+"]
kubectl create -f install -n my-access-operator-namespace

. Check the status of the deployment:
+
[source,shell,subs="+quotes"]
----
kubectl get deployments -n my-access-operator-namespace
----
+
.Output shows the deployment name and readiness
[source,shell,subs="+quotes"]
----
NAME                      READY  UP-TO-DATE  AVAILABLE
strimzi-access-operator  1/1    1           1
----
+
`READY` shows the number of replicas that are ready/expected.
The deployment is successful when the `AVAILABLE` output shows `1`.
