:_mod-docs-content-type: PROCEDURE

// This assembly is included in the following assemblies:
//
// security/assembly-access-operator.adoc

[id='proc-deploy-access-operator-{context}']
= Deploying the Access Operator

[role="_abstract"]
This procedure shows how to deploy the Access Operator for access management of a Kafka cluster.
You cannot use the Access Operator with a Kafka cluster that is not managed by the Cluster Operator.  

.Prerequisites

* The Access Operator installation files must be downloaded and extracted from the latest release archive (`{ReleaseFile}`) from the {ReleaseDownload}. +
The installation files are contained in the `./install` directory.
* xref:deploying-cluster-operator-str[The Cluster Operator must be deployed.]

By default, the Access Operator is deployed in the `strimzi-access-operator` namespace. 
To deploy the operator in a different namespace, update the `namespace` property in the installation files.
For instructions on the various namespace deployment options, see below:

//Deploy the Cluster Operator to watch a single namespace
include::../../modules/deploying/proc-deploy-access-operator-watch-single-namespace.adoc[leveloffset=+1]
//Deploy the Cluster Operator to watch multiple namespaces
include::../../modules/deploying/proc-deploy-access-operator-watch-multiple-namespaces.adoc[leveloffset=+1]
//Deploy the Cluster Operator to watch all namespaces
include::../../modules/deploying/proc-deploy-access-operator-watch-whole-cluster.adoc[leveloffset=+1]