// Module included in the following assemblies:
//
// assembly-deploy-restart-events.adoc

[id='ref-operator-restart-events-fields-{context}']
= Restart event filters

[role="_abstract"]
When checking restart events from the command line, you can specify a `field-selector` to filter on Kubernetes event fields.

The following fields are available when filtering events with `field-selector`.

`regardingObject.kind`:: The object that was restarted, and for restart events, the kind is always `Pod`.
`regarding.namespace`:: The namespace that the pod belongs to.
`regardingObject.name`:: The pod's name, for example, `strimzi-cluster-kafka-0`.
`regardingObject.uid`:: The unique ID of the pod.
`reason`:: The reason the pod was restarted, for example, `JbodVolumesChanged`.
`reportingController`:: The reporting component is always `strimzi.io/cluster-operator` for Strimzi restart events.
`source`:: `source` is an older version of `reportingController`. The reporting component is always `strimzi.io/cluster-operator` for Strimzi restart events.
`type`:: The event type, which is either `Warning` or `Normal`. For Strimzi restart events, the type is `Normal`.

NOTE: In older versions of Kubernetes, the fields using the `regarding` prefix might use an `involvedObject` prefix instead. `reportingController` was previously called `reportingComponent`.