# This file contains the definitions for the self-signed issuer, that is used to issue the root certificates for the Clients and Cluster CAs.
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}

---
# Certificate for the Strimzi Cluster CA
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: strimzi-cluster-ca
spec:
  isCA: true
  commonName: Strimzi Cluster CA
  secretName: strimzi-cluster-ca
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

---
# Issuer for the Strimzi Cluster CA
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: strimzi-cluster-ca
spec:
  ca:
    secretName: strimzi-cluster-ca

---
# Certificate for the Strimzi Clients CA
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: strimzi-clients-ca
spec:
  isCA: true
  commonName: Strimzi Clients CA
  secretName: strimzi-clients-ca
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

---
# Issuer for the Strimzi Clients CA
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: strimzi-clients-ca
spec:
  ca:
    secretName: strimzi-clients-ca
