// This assembly is included in:
//
// overview/overview.adoc

[id="key-features_{context}"]
= Key features

//standard introduction
[role="_abstract"]
include::../../shared/snip-intro-text.adoc[leveloffset=+1]

This guide is intended as a starting point for building an understanding of Strimzi.
The guide introduces some of the key concepts behind Kafka, which is central to Strimzi, explaining briefly the purpose of Kafka components.
Configuration points are outlined, including options to secure and monitor Kafka.
A distribution of Strimzi provides the files to deploy and manage a Kafka cluster, as well as link:{BookURLDeploying}#deploy-examples-{context}[example files for configuration and monitoring of your deployment^].

A typical Kafka deployment is described, as well as the tools used to deploy and manage Kafka.

//description of Kafka features and concepts
include::../../modules/overview/con-key-features-kafka.adoc[leveloffset=+1]

//description of product features
include::../../modules/overview/con-key-features-product.adoc[leveloffset=+1]
