To use custom authorization in Strimzi, you can configure your own `Authorizer` plugin to define Access Control Lists (ACLs).

ACLs allow you to define which users have access to which resources at a granular level.

Configure the `Kafka` custom resource to use custom authorization.
Set the `type` property in the `authorization` section to the value `custom`,
and the set following properties.

IMPORTANT: The custom authorizer must implement the `org.apache.kafka.server.authorizer.Authorizer` interface, and support configuration of `super.users` using the super.users configuration property.

[id='property-custom-authorization-authorizerclass-{context}']
=== `authorizerClass`
(Required) Java class that implements the `org.apache.kafka.server.authorizer.Authorizer` interface to support custom ACLs.


[id='property-custom-authorization-superusers-{context}']
=== `superUsers`
A list of user principals treated as super users, so that they are always allowed without querying ACL rules.
For more information see xref:con-securing-kafka-authorization-str[Kafka authorization].

You can add configuration for initializing the custom authorizer using `Kafka.spec.kafka.config`.

.An example of custom authorization configuration under `Kafka.spec`
[source,yaml,subs="attributes+"]
----
spec:
  kafka:
    # ...
    authorization:
      type: custom
      authorizerClass: io.mycompany.CustomAuthorizer
      superUsers:
        - CN=client_1
        - user_2
        - CN=client_3
    # ...
    config:
      authorization.custom.property1=value1
      authorization.custom.property2=value2
    # ...
----

In addition to the `Kafka` custom resource configuration, the JAR file containing the custom authorizer class along with its dependencies must be available on the classpath of the Kafka broker.

The Strimzi Maven build process provides a mechanism to add custom third-party libraries to the generated Kafka broker container image by adding them as dependencies in the `pom.xml` file under the `docker-images/kafka/kafka-thirdparty-libs` directory. The directory contains different folders for different Kafka versions. Choose the appropriate folder. Before modifying the `pom.xml` file, the third-party library must be available in a Maven repository, and that Maven repository must be accessible to the Strimzi build process.

NOTE: The `super.user` configuration option in the `config` property in `Kafka.spec.kafka` is ignored.
Designate super users in the `authorization` property instead.
For more information, see xref:type-KafkaClusterSpec-reference[Kafka broker configuration].
