Configures automatic restarts for connectors and tasks that are in a `FAILED` state.

A back-off algorithm applies the automatic restart to each failed connector and its tasks.

The operator attempts an automatic restart on reconciliation. 
If the first attempt fails, the operator makes up to six more attempts. 
The duration between each restart attempt increases from 2 to 30 minutes. 
If the restart fails after the final attempt, there is likely to be a problem with the connector configuration. 
The connector and tasks remain in a `FAILED` state.  


If you are using Kafka 3.0.0 or later, only the failed connector is restarted not failed tasks.

To disable the automatic restarting of the connector and it's tasks when they are in the FAILED state on a KafkaConnector resource:

.Disabling automatic restarts of failed connectors for Kafka Connect
[source,yaml,subs="attributes+"]
----
apiVersion: strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
    name: my-source-connector
spec:
    autoRestart:
        enabled: false
----

For MirrorMaker 2.0, use the `autoRestartConnectorsAndTasks` property of the `KafkaMirrorMaker2` resource to disable automatic restarts of failed connectors and tasks.

.Disabling automatic restarts of failed connectors for MirrorMaker 2.0
[source,yaml,subs="attributes+"]
----
apiVersion: strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: my-mm2-cluster
spec:
  autoRestartConnectorsAndTasks:
    enabled: false
----