To use link:https://www.openpolicyagent.org/[Open Policy Agent^] authorization, set the `type` property in the `authorization` section to the value `opa`.
The Open Policy Agent authorizer has several configuration options:

`url`::
The URL used to connect to the Open Policy Agent server.
The URL has to include the policy which will be queried by the authorizer.
**Required.**

`allowOnError`::
Defines whether Kafka client should be allowed or denied by default when the authorizer fails to query the Open Policy Agent (for example because it is temporarily unavailable).
Defaults to `false` - all actions will be denied.

`initialCacheCapacity`::
Initial capacity of the local cache used by the authorizer to avoid querying Open Policy Agent for every request.
Defaults to `5000`.

`maximumCacheSize`::
Maximum capacity of the local cache used by the authorizer to avoid querying Open Policy Agent for every request.
Defaults to `50000`.

`expireAfterMs`::
The expiration of the records kept in the local cache to avoid querying Open Policy Agent for every request.
Defines how often will the cached authorization decisions will expire and be reloaded from the Open Policy Agent server.
In milliseconds.
Defaults to `3600000` milliseconds (1 hour).

`superUsers`::
A list of user principals which will be treated as super users and will be always allowed without querying the open Policy Agent policy.
For more information see xref:ref-kafka-authorization-super-user-deployment-configuration-kafka[Super users].

.An example of Open Policy Agent authorizer configuration
[source,yaml,subs=attributes+]
----
authorization:
  type: opa
  url: http://opa:8181/v1/data/kafka/allow
  allowOnError: false
  initialCacheCapacity: 1000
  maximumCacheSize: 10000
  expireAfterMs: 60000
  superUsers:
    - CN=fred
    - sam
    - CN=edward
----
