[id='nodeport-listener-{context}']
Configures an external listener to expose Kafka using `NodePort` type `Services`.
Kafka clients connect directly to the nodes of Kubernetes.

An additional `NodePort` type of service is created to serve as a Kafka bootstrap address.

.Example of an external listener of type `nodeport`
[source,yaml,subs="attributes+"]
----
# ...
listeners:
  - name: external
    port: 9094
    type: nodeport
    tls: false
# ...
----

When configuring the advertised addresses for the Kafka broker pods, Strimzi uses the address of the node on which the given pod is running.
Nodes often have multiple addresses.

The address type used is based on the first type found in the following order of priority:

. ExternalDNS
. ExternalIP
. Hostname
. InternalDNS
. InternalIP

You must enable access to the ports on the Kubernetes nodes for each node port (for example, in firewalls or security groups).
Each Kafka broker pod is then accessible on a separate port.

[id='property-nodeport-listener-tls-{context}']
.`tls`

By default, TLS encryption is not enabled.
To enable it, set the `tls` property to `true`.

.Example of an external listener of type `nodeport` and enabled TLS encryption
[source,yaml,subs="attributes+"]
----
# ...
listeners:
  - name: external
    port: 9094
    type: nodeport
    tls: true
# ...
----

NOTE: TLS hostname verification is not currently supported when exposing Kafka clusters using node ports.
