Configures a TLS sidecar, which is a container that runs in a pod, but serves a supporting purpose.
In Strimzi, the TLS sidecar uses TLS to encrypt and decrypt communication between components and ZooKeeper.

The TLS sidecar is used in the Entity Operator.

The TLS sidecar is configured using the `tlsSidecar` property in `Kafka.spec.entityOperator`.

The TLS sidecar supports the following additional options:

* `image`
* `resources`
* `logLevel`
* `readinessProbe`
* `livenessProbe`

The `resources` property specifies the xref:con-common-configuration-resources-reference[memory and CPU resources] allocated for the TLS sidecar.

The `image` property configures the xref:con-common-configuration-images-reference[container image] which will be used.

The `readinessProbe` and `livenessProbe` properties configure xref:con-common-configuration-healthchecks-reference[healthcheck probes] for the TLS sidecar.

The `logLevel` property specifies the logging level.
The following logging levels are supported:

* emerg
* alert
* crit
* err
* warning
* notice
* info
* debug

The default value is _notice_.

.Example TLS sidecar configuration
[source,yaml,subs=attributes+]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
metadata:
  name: my-cluster
spec:
  # ...
  entityOperator:
    # ...
    tlsSidecar:
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
    # ...
----
