Custom authorization in Strimzi lets user configure their own `Authorizer` plugin to define the Access Control Lists (ACLs)

ACLs allow you to define which users have access to which resources at a granular level.

Configure the `Kafka` custom resource to use custom authorization.
Set the `type` property in the `authorization` section to the value `custom`,
and the set following properties.

=== `implementionClass`
Implementation class of the `org.apache.kafka.server.authorizer.Authorizer` interface to support the custom ACLs
**Required.**

[id='property-simple-authorization-superusers-{context}']
=== `superUsers`
A list of user principals treated as super users, so that they are always allowed without querying ACL rules.
For more information see xref:con-securing-kafka-authorization-str[Kafka authorization].

.An example of simple authorization configuration
[source,yaml,subs="attributes+"]
----
authorization:
  type: custom
  implementionClass: io.mycompany.CustomAuthorizer
  superUsers:
    - CN=client_1
    - user_2
    - CN=client_3
----

NOTE: The `super.user` configuration option in the `config` property in `Kafka.spec.kafka` is ignored.
Designate super users in the `authorization` property instead.
For more information, see xref:type-KafkaClusterSpec-reference[Kafka broker configuration].
