Configures a MirrorMaker consumer.

[id='property-consumer-streams-{context}']
= `numStreams`

Use the `consumer.numStreams` property to configure the number of streams for the consumer.

You can increase the throughput in mirroring topics by increasing the number of consumer threads.
Consumer threads belong to the consumer group specified for Kafka MirrorMaker.
Topic partitions are assigned across the consumer threads, which consume messages in parallel.

[id='property-consumer-offset-autocommit-{context}']
= `offsetCommitInterval`

Use the `consumer.offsetCommitInterval` property to configure an offset auto-commit interval for the consumer.

You can specify the regular time interval at which an offset is committed after Kafka MirrorMaker has consumed data from the source Kafka cluster.
The time interval is set in milliseconds, with a default value of 60,000.

[id='property-consumer-config-{context}']
= `config`

Use the `consumer.config` properties to configure Kafka options for the consumer as keys.

The values can be one of the following JSON types:

* String
* Number
* Boolean

*Exceptions*

You can specify and configure the options listed in the {ApacheKafkaConsumerConfig}.

However, Strimzi takes care of configuring and managing options related to the following, which cannot be changed:

* Kafka cluster bootstrap address
* Security (encryption, authentication, and authorization)
* Consumer group identifier
* Interceptors

Properties with the following prefixes cannot be set:

* `bootstrap.servers`
* `group.id`
* `interceptor.classes`
* `sasl.`
* `security.`
* `ssl.`

If the `config` property contains an option that cannot be changed, it is disregarded, and a warning message is logged to the Cluster Operator log file.
All other supported options are forwarded to MirrorMaker, including the following exceptions to the options configured by Strimzi:

* Any `ssl` configuration for xref:con-common-configuration-ssl-reference[supported TLS versions and cipher suites]

IMPORTANT: The Cluster Operator does not validate keys or values in the `config` object provided.
If an invalid configuration is provided, the MirrorMaker cluster might not start or might become unstable.
In this case, fix the configuration so that the Cluster Operator can roll out the new configuration to all MirrorMaker nodes.

[id='property-consumer-group-{context}']
= `groupId`

Use the `consumer.groupId` property to configure a consumer group identifier for the consumer.

Kafka MirrorMaker uses a Kafka consumer to consume messages, behaving like any other Kafka consumer client.
Messages consumed from the source Kafka cluster are mirrored to a target Kafka cluster.
A group identifier is required, as the consumer needs to be part of a consumer group for the assignment of partitions.
