Configures an external listener to expose Kafka using Kubernetes `Ingress` and the {NginxIngressController}.

A dedicated `Ingress` resource is created for every Kafka broker pod.
An additional `Ingress` resource is created to serve as a Kafka bootstrap address.
Kafka clients can use these `Ingress` resources to connect to Kafka on port 443.

.Example of an external listener of type `ingress`
[source,yaml,subs="attributes+"]
----
# ...
listeners:
  - name: external
    port: 9094
    type: ingress
    tls: true
    authentication:
      type: tls
    configuration:
      bootstrap:
        host: bootstrap.myingress.com
      brokers:
      - broker: 0
        host: broker-0.myingress.com
      - broker: 1
        host: broker-1.myingress.com
      - broker: 2
        host: broker-2.myingress.com
  # ...
----

NOTE: External listeners using `Ingress` have been currently tested only with the {NginxIngressController}.

[id='property-ingress-listener-tls-{context}']
.`tls`

By default, TLS encryption is not enabled.
To enable it, set the `tls` property to `true`.

.`configuration`

You must specify the hostnames used by the bootstrap and per-broker services using the xref:type-IngressListenerConfiguration-reference[`IngressListenerConfiguration` properties].

[id='property-ingress-listener-class-{context}']
.`class`

By default, the `Ingress` class is set to `nginx`.
You can change the `Ingress` class using the `class` property.

.Example of an external listener of type `ingress` using `Ingress` class `nginx-internal`
[source,yaml,subs="attributes+"]
----
# ...
listeners:
  - name: external
    port: 9094
    type: ingress
    tls: true
    authentication:
      type: tls
    class: nginx-internal
    # ...
# ...
----
