Configures a MirrorMaker producer.

[id='property-producer-abort-on-send-{context}']
= `abortOnSendFailure`

Use the `producer.abortOnSendFailure` property to configure how to handle message send failure from the producer.

By default, if an error occurs when sending a message from Kafka MirrorMaker to a Kafka cluster:

* The Kafka MirrorMaker container is terminated in Kubernetes.
* The container is then recreated.

If the `abortOnSendFailure` option is set to `false`, message sending errors are ignored.

[id='property-producer-config-{context}']
= `config`

Use the `producer.config` properties to configure Kafka options for the producer as keys.

The values can be one of the following JSON types:

* String
* Number
* Boolean

*Exceptions*

You can specify and configure the options listed in the {ApacheKafkaProducerConfig}.

However, Strimzi takes care of configuring and managing options related to the following, which cannot be changed:

* Kafka cluster bootstrap address
* Security (encryption, authentication, and authorization)
* Interceptors

Properties with the following prefixes cannot be set:

* `bootstrap.servers`
* `interceptor.classes`
* `sasl.`
* `security.`
* `ssl.`

If the `config` property contains an option that cannot be changed, it is disregarded, and a warning message is logged to the Cluster Operator log file.
All other supported options are forwarded to MirrorMaker, including the following exceptions to the options configured by Strimzi:

* Any `ssl` configuration for xref:con-common-configuration-ssl-reference[supported TLS versions and cipher suites]

IMPORTANT: The Cluster Operator does not validate keys or values in the `config` object provided.
If an invalid configuration is provided, the MirrorMaker cluster might not start or might become unstable.
In this case, fix the configuration so that the Cluster Operator can roll out the new configuration to all MirrorMaker nodes.
