To configure ServiceAccount OAuth client authentication, set the `type` property to `serviceaccount-oauth`.

ServiceAccount OAuth uses Kubernetes API server's JWKS endpoint to validate service account tokens.

.An example of ServiceAccount OAuth authentication on the listener
[source,yaml,subs=attributes+]
----
authentication:
  type: serviceaccount-oauth
  maxSecondsWithoutReauthentication: 3600
  customClaimCheck: "@.['kubernetes.io'] && @.['kubernetes.io'].['namespace'] in ['example']"
----

This is equivalent to:
[source,yaml,subs=attributes+]
----
authentication:
  type: oauth
  maxSecondsWithoutReauthentication: 3600
  customClaimCheck: "@.['kubernetes.io'] && @.['kubernetes.io'].['namespace'] in ['example']"
  jwksEnpointUri: https://kubernetes.default.svc.cluster.local/openid/v1/jwks
  validIssuerUri: https://kubernetes.default.svc.cluster.local
  serverBearerTokenLocation: /var/run/secrets/kubernetes.io/serviceaccount/token
  checkAccessTokenType: false
  includeAcceptHeader: false
  tlsTrustedCertificates:
    - secretName: oauth-server-cert
      certificate: ca.crt
----

Note that the `tlsTrustedCertificates` is configured to point to a manually created Secret that contains the Kubernetes API server public certificate, which is mounted to the running pods under `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`.
When using `type: serviceaccount-oauth` the trusted certificate to connect to Kubernetes OIDC server is configured automatically.

The configuration option `customClaimCheck` can be used to allow authentication on this listener to some clients only, based on the namespace where the client application is deployed or any other custom claim present in service account JWT token.
