// Module included in the following assemblies:
//
// assembly-mirrormaker.adoc

[id='proc-mirrormaker-replication-{context}']
= Synchronizing data between Kafka clusters using MirrorMaker 2.0

Use MirrorMaker 2.0 to synchronize data between Kafka clusters through configuration.

The configuration must specify:

* Each Kafka cluster
* Connection information for each cluster, including TLS authentication
* The replication flow and direction
** Cluster to cluster
** Topic to topic

Use the properties of the `KafkaMirrorMaker2` resource to configure your Kafka MirrorMaker 2.0 deployment.

NOTE: The previous version of MirrorMaker continues to be supported.
If you wish to use the resources configured for the previous version,
they must be updated to the format supported by MirrorMaker 2.0.

MirrorMaker 2.0 provides default configuration values for properties such as replication factors.
A minimal configuration, with defaults left unchanged, would be something like this example:

[source,yaml,subs="+quotes,attributes"]
----
apiVersion: {KafkaApiVersionPrev}
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker2
spec:
  version: {DefaultKafkaVersion}
  connectCluster: "my-cluster-target"
  clusters:
  - alias: "my-cluster-source"
    bootstrapServers: my-cluster-source-kafka-bootstrap:9092
  - alias: "my-cluster-target"
    bootstrapServers: my-cluster-target-kafka-bootstrap:9092
  mirrors:
  - sourceCluster: "my-cluster-source"
    targetCluster: "my-cluster-target"
    sourceConnector: {}
----

You can configure access control for source and target clusters using TLS or SASL authentication.
This procedure shows a configuration that uses TLS encryption and authentication for the source and target cluster.

.Prerequisites

* xref:cluster-operator-str[{ProductName} and Kafka is deployed]
* Source and target Kafka clusters are available

.Procedure

. Edit the `spec` properties for the `KafkaMirrorMaker2` resource.
+
The properties you can configure are shown in this example configuration:
+
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: {KafkaApiVersionPrev}
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker2
spec:
  version: {DefaultKafkaVersion} <1>
  replicas: 3 <2>
  connectCluster: "my-cluster-target" <3>
  clusters: <4>
  - alias: "my-cluster-source" <5>
    authentication: <6>
      certificateAndKey:
        certificate: source.crt
        key: source.key
        secretName: my-user-source
      type: tls
    bootstrapServers: my-cluster-source-kafka-bootstrap:9092 <7>
    tls: <8>
      trustedCertificates:
      - certificate: ca.crt
        secretName: my-cluster-source-cluster-ca-cert
  - alias: "my-cluster-target" <9>
    authentication: <10>
      certificateAndKey:
        certificate: target.crt
        key: target.key
        secretName: my-user-target
      type: tls
    bootstrapServers: my-cluster-target-kafka-bootstrap:9092 <11>
    config: <12>
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
      ssl.cipher.suites: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384" <13>
      ssl.enabled.protocols: "TLSv1.2"
      ssl.protocol: "TLSv1.2"
    tls: <14>
      trustedCertificates:
      - certificate: ca.crt
        secretName: my-cluster-target-cluster-ca-cert
  mirrors: <15>
  - sourceCluster: "my-cluster-source" <16>
    targetCluster: "my-cluster-target" <17>
    sourceConnector: <18>
      config:
        replication.factor: 1 <19>
        offset-syncs.topic.replication.factor: 1 <20>
        sync.topic.acls.enabled: "false" <21>
    heartbeatConnector: <22>
      config:
        heartbeats.topic.replication.factor: 1 <23>
    checkpointConnector: <24>
      config:
        checkpoints.topic.replication.factor: 1 <25>
    topicsPattern: ".*" <26>
    groupsPattern: "group1|group2|group3" <27>
  resources: <28>
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 2Gi
  logging: <29>
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
  readinessProbe: <30>
    initialDelaySeconds: 15
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
  jvmOptions: <31>
    "-Xmx": "1g"
    "-Xms": "1g"
  image: my-org/my-image:latest <32>
  template: <33>
    pod:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: application
                    operator: In
                    values:
                      - postgresql
                      - mongodb
              topologyKey: "kubernetes.io/hostname"
    connectContainer: <34>
      env:
        - name: JAEGER_SERVICE_NAME
          value: my-jaeger-service
        - name: JAEGER_AGENT_HOST
          value: jaeger-agent-name
        - name: JAEGER_AGENT_PORT
          value: "6831"
  tracing:
    type: jaeger <35>
  externalConfiguration: <36>
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-creds
            key: awsAccessKey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-creds
            key: awsSecretAccessKey
----
<1> The Kafka Connect version.
<2> The number of replica nodes.
<3> The cluster alias for Kafka Connect.
<4> Specification for the Kafka clusters being synchronized.
<5> The cluster alias for the source Kafka cluster.
<6> Authentication for the source cluster, using the xref:type-KafkaClientAuthenticationTls-reference[TLS mechanism], as shown here, using xref:type-KafkaClientAuthenticationOAuth-reference[OAuth bearer tokens], or a SASL-based xref:type-KafkaClientAuthenticationScramSha512-reference[SCRAM-SHA-512] or xref:type-KafkaClientAuthenticationPlain-reference[PLAIN] mechanism.
<7> Bootstrap server for connection to the source Kafka cluster.
<8> TLS encryption with key names under which TLS certificates are stored in X.509 format for the source Kafka cluster. For more details see xref:type-KafkaMirrorMaker2Tls-reference[`KafkaMirrorMaker2Tls` schema reference].
<9> The cluster alias for the target Kafka cluster.
<10> Authentication for the target Kafka cluster is configured in the same way as for the source Kafka cluster.
<11> Bootstrap server for connection to the target Kafka cluster.
<12> xref:assembly-kafka-connect-configuration-deployment-configuration-kafka-connect[Kafka Connect configuration].
Standard Apache Kafka configuration may be provided, restricted to those properties not managed directly by {ProductName}.
<13> xref:type-KafkaMirrorMaker2ClusterSpec-reference[SSL properties for external listeners to run with a specific _cipher suite_ for a TLS version].
<14> TLS encryption for the target Kafka cluster is configured in the same way as for the source Kafka cluster.
<15> MirrorMaker 2.0 connectors.
<16> The alias of the source cluster used by the MirrorMaker 2.0 connectors.
<17> The alias of the target cluster used by the MirrorMaker 2.0 connectors.
<18> The configuration for the `MirrorSourceConnector` that creates remote topics. The `config` overrides the default configuration options.
<19> The replication factor for mirrored topics created at the target cluster.
<20> The replication factor for the `MirrorSourceConnector` `offset-syncs` internal topic that maps the offsets of the source and target clusters.
<21> When enabled, ACLs are applied to synchronized topics. The default is `true`.
<22> The configuration for the `MirrorHeartbeatConnector` that performs connectivity checks. The `config` overrides the default configuration options.
<23> The replication factor for the heartbeat topic created at the target cluster.
<24> The configuration for the `MirrorCheckpointConnector` that tracks offsets. The `config` overrides the default configuration options.
<25> The replication factor for the checkpoints topic created at the target cluster.
<26> Topic replication from the source cluster defined as regular expression patterns. Here we request all topics.
<27> Consumer group replication from the source cluster defined as regular expression patterns. Here we request three consumer groups by name.
You can use comma-separated lists.
<28> Requests for reservation of supported resources, currently `cpu` and `memory`, and limits to specify the maximum resources that can be consumed.
<29> Specified loggers and log levels added directly (`inline`) or indirectly (`external`) through a ConfigMap. A custom ConfigMap must be placed under the `log4j.properties` or `log4j2.properties` key. Kafka Connect has a single logger called `connect.root.logger.level`. You can set the log level to INFO, ERROR, WARN, TRACE, DEBUG, FATAL or OFF.
<30> Healthchecks to know when to restart a container (liveness) and when a container can accept traffic (readiness).
<31> JVM configuration options to optimize performance for the Virtual Machine (VM) running Kafka MirrorMaker.
<32> ADVANCED OPTION: Container image configuration, which is xref:con-configuring-container-images-deployment-configuration-kafka-mirror-maker[recommended only in special situations].
<33> xref:assembly-customizing-deployments-str[Template customization]. Here a pod is scheduled based with anti-affinity, so the pod is not scheduled on nodes with the same hostname.
<34> Environment variables are also xref:ref-tracing-environment-variables-{context}[set for distributed tracing using Jaeger].
<35> xref:assembly-distributed-tracing-str[Distributed tracing is enabled for Jaeger].
<36> Kubernetes Secret mounted to Kafka MirroMaker as an environment variable.

. Create or update the resource:
+
[source,shell,subs=+quotes]
kubectl apply -f _<your-file>_
