PROJECT_NAME=base

include ../../Makefile.os
include ../../Makefile.docker

docker_push:
	# Do nothing

docker_amend_manifest:
	# Do nothing

docker_e2e:
	# Do nothing

docker_push_manifest:
	# Do nothing

docker_sign_manifest:
	# Do nothing

# TODO - remove gha prefix once migrated fully to gha
docker_gha_sign_manifest:
	# Do nothing

docker_sbom:
	# Do nothing

docker_push_sbom:
	# Do nothing

# TODO - remove gha prefix once migrated fully to gha
docker_gha_sbom:
	# Do nothing

# TODO - remove gha prefix once migrated fully to gha
docker_gha_push_sbom:
	# Do nothing

.PHONY: build clean release