name: "Install Docker"
description: "Install Docker"

runs:
  using: "composite"
  steps:
    - name: Debug
      shell: bash
      run: "docker --version"
#    - name: Set up Docker
#      uses: docker/setup-docker-action@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
