// This concept is included in the following assemblies:
//
// assembly-cruise-control-concepts.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='con-cruise-control-overview-{context}']
= Cruise Control overview

Brokers in a Kafka cluster can become unevenly loaded due to things like an uneven distribution of busy partitions.
Cruise Control is a tool for simplifying the monitoring and rebalancing of partitions across a Kafka cluster.
You deploy Cruise Control alongside a Kafka cluster to:

* Monitor the CPU, disk, and network load of Kafka brokers.
* Propose balanced partition assignments, known as partition rebalance proposals.
* Trigger partition reassignments based on those proposals.

The following sections explain how to xref:proc-deploying-cruise-control-{context}[deploy Cruise Control], xref:ref-cruise-control-configuration-{context}[set configuration options], xref:proc-interacting-with-cruise-control-api-{context}[use the Cruise Control API], and xref:proc-executing-cruise-control-rebalance-operations-{context}[execute a cluster rebalance operation].
