// Module included in the following assemblies:
//
// assembly-cruise-control-concepts.adoc

[id='con-optimization-proposals-{context}']

= Optimization proposals

An _optimization proposal_ is a summary of proposed changes that would produce a more balanced Kafka cluster, with partition workloads distributed more evenly across the brokers. 
Each optimization proposal is based on the set of xref:con-optimization-goals-{context}[optimization goals] that were used to generate it.

Optimization proposals always satisfy all the supplied hard goals, though not necessarily all the supplied soft goals. Hard goals are ignored if the `skip_hard_goal_check` option is specified for the rebalance operation.

An optimization proposal provides the following information in JSON:

* An optimal mapping of partitions to brokers, generated by the Analyzer component of Cruise Control

* Statistics on the cluster rebalance (before and after)

You can use the information to decide whether to implement the cluster rebalance, or change the optimization goals. 

All optimization proposals are dry runs: you cannot implement a cluster rebalance without first generating an optimization proposal. 
There is no limit to the number of optimization proposals that can be generated.

The following table explains the properties contained in an optimization proposal:

[cols="2*",options="header",stripes="none",separator=¦]
|===

m¦JSON property
¦Description

m¦numIntraBrokerReplicaMovements
¦Description

m¦excludedBrokersForLeadership
¦Description

m¦numReplicaMovements
¦Description

m¦onDemandBalancednessScoreAfter
¦Description

m¦onDemandBalancednessScoreBefore
¦Description

m¦intraBrokerDataToMoveMB
¦Description

m¦recentWindows
¦Description

m¦dataToMoveMB
¦Description

m¦monitoredPartitionsPercentage
¦Description

m¦excludedTopics
¦Description

m¦numLeaderMovements
¦Description

m¦excludedBrokersForReplicaMove
¦Description

|===

.Additional resources

* xref:proc-generating-rebalance-proposals-{context}[] 

* xref:proc-implementing-rebalance-proposal-{context}[] 