// This concept is included in the following assemblies:
//
// assembly-cruise-control-concepts.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='con-cruise-control-overview-{context}']
= Why use Cruise Control?

A typical Kafka cluster can become unevenly loaded over time.
Partitions that handle large amounts of message traffic might be unevenly distributed across the available brokers.
To rebalance the cluster, administrators must monitor the load on brokers and manually reassign busy partitions to brokers with spare capacity.

Cruise Control automates the monitoring and reassignment of partitions, reducing the time and effort involved in running an efficient, balanced Kafka cluster.
It constructs a model of resource utilization for the cluster--based on CPU, disk, and network load--and generates _optimization proposals_ for balanced partition assignments. A set of configurable _optimization goals_ is used to calculate these proposals.

You can choose to implement optimization proposals to achieve a more balanced Kafka cluster.  

.Additional resources

* link:https://github.com/linkedin/cruise-control/wiki[Cruise Control Wiki^]