// Module included in the following assemblies:
//
// assembly-cruise-control-concepts.adoc

[id='proc-fixing-problems-with-kafkarebalance-{context}']

= Fixing problems with a `KafkaRebalance` resource

If an issue occurs in the process of creating a `KafkaRebalance` resource, or when interacting with Cruise Control, the error is reported in the resource status, along with details of how to fix it. 
The resource also moves to the `NotReady` state.

To continue with the cluster rebalance operation, you must fix the problem in the `KafkaRebalance` resource itself. 
Problems can include the following:

* A misconfigured parameter.
* The Cruise Control server is not reachable. 

When you believe that you have fixed the issue, you need to add the `refresh` annotation to the resource.
During a “refresh”, a new optimization proposal is requested from the Cruise Control server.

.Prerequisites

* You have xref:proc-approving-optimization-proposal-{context}[approved an optimization proposal].

* The status of the `KafkaRebalance` custom resource for the rebalance operation is `NotReady`.

.Procedure

. Get information about the error from the `KafkaRebalance` status and resolve the issue if possible.

. Annotate the `KafkaRebalance` resource in Kubernetes:
+
[source,shell,subs="+quotes"]
----
kubectl annotate kafkarebalance _cluster-rebalance-name_ strimzi.io/rebalance=refresh
----

. Check the status of the `KafkaRebalance` resource:
+
[source,shell,subs="+quotes"]
----
kubectl describe kafkarebalance _rebalance-cr-name_
----

. Wait until the status changes to `PendingProposal`, or directly to `ProposalReady`.

.Additional resources

* xref:con-optimization-proposals-{context}[]
