// Module included in the following assemblies:
//
// assembly-cruise-control-concepts.adoc

[id='proc-implementing-rebalance-proposal-{context}']
= Implementing an optimization proposal

You can implement an optimization proposal with a status of `ProposalReady`.
Cruise Control will then reassign partitions to brokers as summarized in the optimization proposal.

WARNING: This is not a dry run. 
Review the optimization proposal before you implement it.

.Prerequisites

* You have xref:proc-generating-rebalance-proposals-{context}[generated an optimization proposal].

* The optimization proposal is ready to implement (the `KafkaRebalance` custom resource status is `ProposalReady`).

.Procedure

Perform these steps for the optimization proposal that you want to implement:

. If the `KafkaRebalance` status has been `ProposalReady` for some time, refresh the optimization proposal in case it has become out of date:

.. Annotate the `KafkaRebalance` resource in Kubernetes:
+
[source,shell,subs="+quotes"]
----
kubectl annotate kafkaclusterrebalance _cluster-name_-kafka strimzi.io/rebalance=refresh
----

.. Check the status of the `KafkaRebalance` resource:
+
[source,shell,subs="+quotes"]
----
kubectl get kafka kafkaclusterrebalance -o jsonpath='{.status}'
----

.. Wait until the status changes to `ProposalReady`.

. Approve the optimization proposal that you want to implement.
+
Annotate the `KafkaRebalance` resource in Kubernetes:
+
[source,shell,subs="+quotes"]
----
kubectl annotate kafkaclusterrebalance _cluster-name_-kafka strimzi.io/rebalance=approved
----

. The Cluster Operator detects the annotated resource and instructs Cruise Control to rebalance the Kafka cluster.

. Check the status of the `KafkaRebalance` resource:
+
[source,shell,subs="+quotes"]
----
kubectl get kafka kafkaclusterrebalance -o jsonpath='{.status}'
----

. Cruise Control returns one of three statuses:

** Rebalancing: The cluster rebalance operation is in progress. 

** Ready: The cluster rebalancing operation completed successfully.

** NotReady: An error occurred. 

//Is there a way to verify the rebalance?

.Additional resources

* xref:con-rebalance-goals-proposals-{context}[]
