// Module included in the following assemblies:
//
// assembly-cruise-control-concepts.adoc

[id='ref-cruise-control-configuration-{context}']
= Cruise Control configuration

The `config` property in `Kafka.spec.cruiseControl` contains configuration options as keys with values as one of the following JSON types:

* String
* Number
* Boolean

NOTE: Strings that look like JSON or YAML will need to be explicitly quoted.

You can specify and configure all the options listed in the "Configurations" section of the {CruiseControlConfigDocs}, apart from those managed directly by {ProductName}.
Specifically, you *cannot* modify configuration options with keys equal to or starting with one of the following strings:

* `bootstrap.servers`
* `zookeeper.`
* `ssl.`
* `security.`
* `failed.brokers.zk.path`
* `webserver.http.port`
* `webserver.http.address`
* `webserver.api.urlprefix`
* `metric.reporter.sampler.bootstrap.servers`
* `metric.reporter.topic`
* `metric.reporter.topic.pattern`
* `partition.metric.sample.store.topic`
* `broker.metric.sample.store.topic`
* `capacity.config.file`
* `skip.sample.store.topic.rack.awareness.check`
* `cruise.control.metrics.topic`
* `sasl.`

If restricted options are specified, they are ignored and a warning message is printed to the Cluster Operator log file.
All the supported options are passed to Cruise Control.

.An example Cruise Control configuration
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
metadata:
  name: my-cluster
spec:
  # ...
  cruiseControl:
    # ...
    config:
      default.goals: >
         com.linkedin.kafka.cruisecontrol.analyzer.goals.RackAwareGoal,
         com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal
      cpu.balance.threshold: 1.1
      metadata.max.age.ms: 300000
      send.buffer.bytes: 131072
    # ...
----

[#capacity-configuration]
[discrete]
== Capacity configuration

Cruise Control uses _capacity limits_ to determine if optimization goals for broker resources are being broken.
An optimization will fail if a hard goal is broken, preventing the optimization from being used to generate an optimization proposal.

You specify capacity limits for broker resources in the `brokerCapacity` property in `Kafka.spec.cruiseControl` .
Capacity limits can be set for the following broker resources in the described units:

* `disk`            - Disk storage in bytes
* `cpuUtilization`  - CPU utilization as a percent (0-100)
* `inboundNetwork`  - Inbound network throughput in bytes per second
* `outboundNetwork` - Outbound network throughput in bytes per second

Because {ProductName} Kafka brokers are homogeneous, Cruise Control applies the same capacity limits to every broker it is monitoring.

.An example Cruise Control brokerCapacity configuration
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
metadata:
  name: my-cluster
spec:
  # ...
  cruiseControl:
    # ...
    brokerCapacity:
      disk: 100G
      cpuUtilization: 100
      inboundNetwork: 10000KB/s
      outboundNetwork: 10000KB/s
    # ...
----

.Additional resources
For more information, refer to the xref:type-BrokerCapacity-reference[].

[#auto-created-topics-logs]
[discrete]
== Auto-created topics and log compaction

Cruise Control requires the following three topics in order to work:

* `strimzi.cruisecontrol.partitionmetricsamples`
* `strimzi.cruisecontrol.modeltrainingsamples`
* `strimzi.cruisecontrol.metrics`

These three topics are usually auto-created by {ProductName} and Cruise Control. First, the metric reporters create the `strimzi.cruisecontrol.metrics` topic. 
Then, Cruise Control creates the `strimzi.cruisecontrol.partitionmetricsamples` and `strimzi.cruisecontrol.modeltrainingsamples` topics.

However, if automatic topic creation is _disabled_ in Kafka (`auto.create.topics.enable: false` is configured in `spec.kafka.config` when starting a new Kafka cluster) the Cruise Control metric reporters are unable to create the `strimzi.cruisecontrol.metrics` topic.
In this situation, you need to manually create the `strimzi.cruisecontrol.metrics` topic before deploying Cruise Control. 
You can do this using the following command:

[source,shell,subs="attributes+"]
----
kubectl apply -f examples/cruise-control/cruise-control-topic.yaml
----

Log compaction might remove records that are needed by Cruise Control; therefore, all auto-created topics must be configured with `cleanup.policy=delete` to disable log compaction. 
Cruise Control will automatically disable log compaction for the `strimzi.cruisecontrol.partitionmetricsamples` and `strimzi.cruisecontrol.modeltrainingsamples` topics.
The Cruise Control metric reporters attempt to disable log compaction for the `strimzi.cruisecontrol.metrics` topic, but fail if they are started with a new Kafka cluster.
This is only a problem if log compaction is enabled in Kafka with the setting `log.cleanup.policy=compact` in `spec.kafka.config`. 
In this situation, log compaction will be enabled for the `strimzi.cruisecontrol.metrics` topic and will need to be overridden with `cleanup.policy=delete` in the `strimzi.cruisecontrol.metrics` topic.

Here is an example where log compaction is disabled in a topic that was auto-created by Cruise Control:

[source,yaml,subs="+quotes,attributes"]
----
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: strimzi.cruisecontrol.metrics
spec:
  partitions: 1
  replicas: 1
  config:
    cleanup.policy: delete
----

[#logging-configuration]
[discrete]
== Logging configuration

Cruise Control has its own configurable logger:

* `cruisecontrol.root.logger`

Cruise Control uses the Apache `log4j` logger implementation.

Use the `logging` property to configure loggers and logger levels.

You can set the log levels by specifying the logger and level directly (inline) or use a custom (external) ConfigMap.
If a ConfigMap is used, you set `logging.name` property to the name of the ConfigMap containing the external logging configuration. Inside the ConfigMap, the logging configuration is described using `log4j.properties`.

Here we see examples of `inline` and `external` logging.

.Inline logging
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
# ...
spec:
  cruiseControl:
    # ...
    logging:
      type: inline
      loggers:
        cruisecontrol.root.logger: "INFO"
    # ...
----

.External logging
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
# ...
spec:
  cruiseControl:
    # ...
    logging:
      type: external
      name: customConfigMap
    # ...
----
