#!/usr/bin/env bash

# Generates documentation/book/ref-kafka-versions.adoc
# according to the values in kafka-versions

FILE=$1
cat <<EOF
// This assembly is included in the following assemblies:
//
// assembly-upgrading-kafka-versions.adoc

// Generated by documentation/supported-version.sh during the build
// DO NOT EDIT BY HAND

[id='ref-kafka-versions-{context}']
= Kafka versions

[options="header"]
|=================
|Kafka version |interbroker.protocol.version |log.message.format.version
EOF


for x in $(grep -E '^[^#]' "$FILE" | sed -E 's/ +/|/g'); do
    i=0
    for y in $(echo $x | sed -E -e 's/[|][a-zA-Z0-9]+$'// -e 's/[|]/ /g' ); do
        if [ "$y" != 'default' ]; then
            echo -n "|$y "
        fi
    done
    echo
done
cat <<EOF
|=================

The default Kafka version is {DefaultKafkaVersion}.
EOF