#!/usr/bin/env bash

# Generates documentation/book/ref-kafka-versions.adoc
# according to the values in kafka-versions

. $(dirname $0)/../multi-platform-support.sh

FILE="$1"
cat <<EOF
// This assembly is included in the following assemblies:
//
// assembly-upgrading-kafka-versions.adoc
// Generated by documentation/supported-version.sh during the build
// DO NOT EDIT BY HAND
[options="header"]
|=================
|Kafka version |Interbroker protocol version |Log message format version| Zookeeper version
EOF

finished=0
counter=0
while [ $finished -lt 1 ] 
do
    version=$(yq read "$FILE" "[${counter}].version")

    if [ "$version" = "null" ]
    then
        finished=1
    else

        protocol=$(yq read "$FILE" "[${counter}].protocol")
        message_format=$(yq read "$FILE" "[${counter}].format")
    
        echo "| $version | $protocol | $message_format | 3.4.13"

        counter=$((counter + 1))
    fi
done

cat <<EOF
|=================
EOF
