#!/usr/bin/env bash

source $(dirname "${BASH_SOURCE[0]}")/../multi-platform-support.sh

FILE=$1

VERSIONSNL=$($SED -E -e '/^(#.*|[[:space:]]*)$/d' -e 's/^([0-9.]+)[[:space:]]+.*[[:space:]]+([[:alnum:]]+)$/\1/g' ${FILE})
DEFAULTVERSION=$($GREP -E '^([0-9.]+)[[:space:]]+default' ${FILE} | $SED -E 's/^([0-9.]+).*$/\1/g')
case $(echo "$VERSIONSNL" | $WC -l) in
  "1")
    VERSIONS="$VERSIONSNL"
    ;;
  "2")
    VERSIONS=$(echo -n "$VERSIONSNL" | tr '\n' ' ' | $SED -E -e 's/ / and /g')
    ;;
  "3")
    VERSIONS=$(echo -n "$VERSIONSNL" | tr '\n' ' ' | $SED -E -e 's/ ([0-9]+)/, \1/g' | $SED -E -e 's/, ([0-9.]+)$/, and \1/g')
    ;;
esac

cat <<EOF
// Generated by documentation/supported-version.sh during the build
// DO NOT EDIT BY HAND
:SupportedKafkaVersionList: ${VERSIONS}
:DefaultKafkaVersion: ${DEFAULTVERSION}
EOF
