#!/usr/bin/env bash

FILE=$1

VERSIONSNL=$(sed -E -e '/^(#.*|[[:space:]]*)$/d' -e 's/^([0-9.]+)[[:space:]]+.*[[:space:]]+([[:alnum:]]+)$/\1/g' ${FILE})
case $(echo "$VERSIONSNL" | wc -l) in
  "1")
    VERSIONS="$VERSIONSNL"
    ;;
  "2")
    VERSIONS=$(echo -n "$VERSIONSNL" | tr '\n' ' ' | sed -E -e 's/ / and /g')
  ;;
  "3")
    VERSIONS=$(echo -n "$VERSIONSNL" | tr '\n' ' ' | sed -E -e 's/ ([0-9]+)/, \1/g' | sed -E -e 's/, ([0-9.]+)$/, and \1/g')
  ;;
esac

cat <<EOF
// Generated by documentation/supported-version.sh during the build
// DO NOT EDIT BY HAND
:SupportedKafkaVersionList: ${VERSIONS}
:DefaultKafkaVersion: $(grep -E '^([0-9.]+)[[:space:]]+default' ${FILE} | sed -E 's/^([0-9.]+).*$/\1/g')
EOF