#!/usr/bin/env bash

# Generates documentation/book/common/version-dependent-attrs.adoc
# according to the values in kafka-versions

. $(dirname $0)/../multi-platform-support.sh

FILE=$1

finished=0
counter=0
while [ $finished -lt 1 ] 
do
    version=$(yq read "$FILE" "[${counter}].version")

    if [ "$version" = "null" ]
    then
        finished=1
    else
        if [ $(yq read "$FILE" "[${counter}].default") = "true" ]
        then
            default_version=$version
            finished=1
        fi
        counter=$((counter+1))
    fi
done

cat <<EOF
// Generated by documentation/version-dependent-attrs.sh during the build
// DO NOT EDIT BY HAND
:DefaultKafkaVersion: ${default_version}
EOF
