#!/usr/bin/env bash

source $(dirname $(realpath $0))/../tools/kafka-versions-tools.sh
source $(dirname $(realpath $0))/../tools/strimzi-oauth-version.sh

# Generates documentation/book/shared/version-dependent-attrs.adoc
# according to the values in kafka-versions

. $(dirname $0)/../tools/multi-platform-support.sh

get_default_kafka_version
get_strimzi_oauth_version

cat <<EOF
// Generated by documentation/version-dependent-attrs.sh during the build
// DO NOT EDIT BY HAND
:DefaultKafkaVersion: ${default_kafka_version}
:StrimziOauthVersion: ${strimzi_oauth_version}
EOF
