#!/usr/bin/env bash

source $(dirname $(realpath $0))/../tools/kafka-versions-tools.sh

# Generates documentation/book/shared/version-dependent-attrs.adoc
# according to the values in kafka-versions

source $(dirname $(realpath $0))/../tools/multi-platform-support.sh

get_default_kafka_version

cat <<EOF
// Generated by documentation/version-dependent-attrs.sh during the build
// DO NOT EDIT BY HAND
:DefaultKafkaVersion: ${default_kafka_version}
EOF
