name: Build

on:
  push:
    branches:
      - "main"
      - "release-*"
  pull_request:
    branches:
      - "*"

# Declare default permissions as read only
permissions:
  contents: read

# Cancel previous builds on the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build Strimzi Java code and does basic checks of the PR
  build-strimzi:
    name: Build Strimzi
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v6

      # Build workflow trigger via pull_request will have merge commit sha in github.sha
      - name: Store build commit sha
        run: |
          echo "${{ github.sha }}" > commit-sha.txt
          echo "Stored commit SHA: ${{ github.sha }}"

      - name: Upload build metadata
        uses: actions/upload-artifact@v5
        with:
          name: commit-sha.txt
          path: commit-sha.txt

      - name: Remove commit-sha.txt
        run: |
          rm -rf commit-sha.txt

      - name: Setup Java and Maven
        uses: strimzi/github-actions/.github/actions/dependencies/setup-java@main
        with:
          javaVersion: "21"

      - name: Install yq
        uses: strimzi/github-actions/.github/actions/dependencies/install-yq@main
        with:
          version: "v4.6.3"

      - name: Install Shellcheck
        uses: strimzi/github-actions/.github/actions/dependencies/install-shellcheck@main
        with:
          version: "0.11.0"

      - name: Install Helm
        uses: strimzi/github-actions/.github/actions/dependencies/install-helm@main
        with:
          helmVersion: "v3.16.0"

      - name: Build binaries using build-binaries action
        uses: strimzi/github-actions/.github/actions/build/build-binaries@main
        with:
          mainJavaBuild: "true"
          artifactSuffix: "operators"
          clusterOperatorBuild: "true"
        env:
          # Skip tests for both runs as we will run tests in parallel
          MVN_ARGS: "-B -DskipTests -Dmaven.javadoc.skip=true"

  # Runs Strimzi unit and integration tests
  test-strimzi:
    name: Strimzi Unit & IT tests
    needs:
      - build-strimzi
    runs-on: ubuntu-latest
    timeout-minutes: 80
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build/test-strimzi

  # Builds Strimzi docs
  build-docs:
    name: Build docs
    needs:
      - build-strimzi
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6

      - name: Install yq
        uses: strimzi/github-actions/.github/actions/dependencies/install-yq@main
        with:
          version: "v4.6.3"

      - name: Install AsciiDoctor
        uses: strimzi/github-actions/.github/actions/dependencies/install-ascii-doctor@main
        with:
          rubyVersion: "3.2"

      - uses: ./.github/actions/build/build-docs
        with:
          artifactName: "documentation.tar"

  # Builds Strimzi containers
  build-containers:
    name: Build Containers
    needs:
      - build-strimzi
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
          - s390x
          - ppc64le
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6

      - name: Install Docker
        uses: strimzi/github-actions/.github/actions/dependencies/install-docker@main

      - name: Install yq
        uses: strimzi/github-actions/.github/actions/dependencies/install-yq@main
        with:
          version: "v4.6.3"

      - name: Install Shellcheck
        uses: strimzi/github-actions/.github/actions/dependencies/install-shellcheck@main
        with:
          version: "0.11.0"

      - uses: strimzi/github-actions/.github/actions/build/build-containers@main
        with:
          architecture: ${{ matrix.architecture }}
          imagesDir: "./docker-images/container-archives"
          artifactSuffix: "operators"

  # Push Strimzi containers - run only on main branch
  push-containers:
    name: Push Containers
    needs:
      - build-strimzi
      - test-strimzi
      - build-containers
      - build-docs
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      # Required for keyless signing with GitHub OIDC
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - name: Install Docker
        uses: strimzi/github-actions/.github/actions/dependencies/install-docker@main

      - name: Install yq
        uses: strimzi/github-actions/.github/actions/dependencies/install-yq@main
        with:
          version: "v4.6.3"

      - name: Install Syft
        uses: strimzi/github-actions/.github/actions/dependencies/install-syft@main
        with:
          version: "v1.20.0"

      - name: Push containers using push-containers action
        uses: strimzi/github-actions/.github/actions/build/push-containers@main
        with:
          registryUser: ${{ secrets.QUAY_USER }}
          registryPassword: ${{ secrets.QUAY_PASS }}
          containerRegistry: "quay.io"
          containerOrg: "strimzi"
          containerTag: "latest"
          architectures: "amd64,arm64,ppc64le,s390x"
          artifactSuffix: "operators"

  # Publish Strimzi docs to the website - run only on main branch
  publish-docs:
    name: Publish Docs
    needs:
      - build-strimzi
      - test-strimzi
      - build-containers
      - build-docs
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build/publish-docs
        with:
          artifactName: "documentation.tar"
          websiteDeployKey: ${{ secrets.WEBSITE_DEPLOY_KEY }}

  # Deploy Strimzi Java artifacts - run only on main branch
  deploy-java:
    name: Deploy Java artifacts
    needs:
      - build-strimzi
      - test-strimzi
      - build-containers
      - build-docs
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java and Maven
        uses: strimzi/github-actions/.github/actions/dependencies/setup-java@main
        with:
          javaVersion: "21"

      - name: Install yq
        uses: strimzi/github-actions/.github/actions/dependencies/install-yq@main
        with:
          version: "v4.6.3"

      - name: Deploy to Maven Central
        uses: strimzi/github-actions/.github/actions/build/deploy-java@main
        with:
          modules: "./,crd-annotations,crd-generator,test,api,v1-api-conversion"
          gpgPassphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpgSigningKey: ${{ secrets.GPG_SIGNING_KEY }}
          centralUsername: ${{ secrets.CENTRAL_USERNAME }}
          centralPassword: ${{ secrets.CENTRAL_PASSWORD }}
