// This assembly is included in the following assemblies:
//
// deploying/master.adoc
// master.adoc

[id='assembly-upgrade-{context}']
= Upgrading Strimzi

Strimzi can be upgraded from a lower version to a higher version to take advantage of new features and enhancements, performance improvements, and security options.

As part of the upgrade, you upgrade Kafka to a higher supported version. 
Each Kafka release introduces new features, improvements, and bug fixes.

Strimzi can be xref:assembly-downgrade-{context}[downgraded] to the previous version if you encounter issues with a newer version.

.Upgrade paths

Two upgrade paths are possible:

Incremental:: 
Upgrading Strimzi from the current version to the next highest version.
+
For example, upgrading from Strimzi 0.20.1 to 0.21.0.

Multi-version::
Upgrading Strimzi from the current version to any higher version within a single upgrade (skipping one or more versions).
+
For example, upgrading from Strimzi 0.19.0 directly to Strimzi 0.21.0.

The link:https://strimzi.io/downloads/[Supported versions^] table lists every released version of Strimzi.

.Downtime and availability

If topics are configured for high availability, upgrading Strimzi should not cause any downtime for consumers and producers that publish and read data from those topics. 
Highly available topics have a replication factor of at least 3 and partitions distributed evenly among the brokers.

Upgrading Strimzi triggers rolling updates, where all brokers are restarted in turn, at different stages of the process. 
During rolling updates, not all brokers are online, so overall _cluster availability_ is temporarily reduced.  
A reduction in cluster availability increases the chance that a broker failure will result in lost messages.

.Kafka version compatibility

Each version of Strimzi supports one or more versions of Apache Kafka.
You can upgrade to a higher Kafka version as long as it is supported by your version of Strimzi.
In some cases, you can also downgrade to a lower supported Kafka version.

include::assembly-upgrade-kafka.adoc[leveloffset=+1]

include::assembly-upgrade-resources.adoc[leveloffset=+1]

//how to upgrade clients and kafka streams to use the incremental cooperative rebalance protocol
include::modules/proc-upgrading-consumers-streams-cooperative-rebalancing.adoc[leveloffset=+1]