// This assembly is included in the following assemblies:
//
// // assembly-upgrade.adoc

[id='assembly-upgrade-resources-{context}']
= Strimzi custom resource upgrades

[role="_abstract"]
After you have upgraded Strimzi to {ProductVersion}, you must ensure that your custom resources are using API version `{ApiVersion}`.

IMPORTANT: The upgrade of resources _must_ be performed after xref:assembly-upgrade-{context}[upgrading the Cluster Operator], so the Cluster Operator can understand the resources.

.CLI upgrades to custom resources

Strimzi provides am _API conversion tool_ with its release artifacts
From its CLI, you can use the tool to convert the format of your custom resources to `{ApiVersion}`:

* xref:proc-upgrade-cli-tool-files-{context}[]
* xref:proc-upgrade-cli-tool-direct-{context}[]

Following on from the conversion of your custom resources, you can also set `{ApiVersion}` as the _storage_ API version in your CRDs:

* xref:proc-upgrade-cli-tool-crds-{context}[]

.Manual upgrades to custom resources

As an alternative to using the API conversion tool, you can manually update each custom resource to use `{ApiVersion}`:

* xref:proc-upgrade-kafka-resources-{context}[]
* xref:proc-upgrade-kafka-connect-resources-{context}[]
* xref:proc-upgrade-kafka-connect-s2i-resources-{context}[]
* xref:proc-upgrade-kafka-mirror-maker-resources-{context}[]
* xref:proc-upgrade-kafka-topic-resources-{context}[]
* xref:proc-upgrade-kafka-user-resources-{context}[]

The manual procedures show the changes that are made to each custom resource.

.What if a resource upgrade does not take effect?
If an upgrade does not take effect, a warning is given in the logs on reconciliation to indicate that the resource cannot be updated until the `apiVersion` is updated.

To trigger the update, make a cosmetic change to the custom resource, such as adding an annotation.

Example annotation:

[source,shell,subs="+quotes,attributes"]
----
metadata:
  # ...
  annotations:
    upgrade: "Upgraded to {KafkaApiVersion}"
----

include::modules/con-upgrade-custom-resources.adoc[leveloffset=+1]
include::modules/proc-upgrade-cli-tool-files.adoc[leveloffset=+1]
include::modules/proc-upgrade-cli-tool-direct.adoc[leveloffset=+1]
include::modules/proc-upgrade-cli-tool-crds.adoc[leveloffset=+1]
include::modules/proc-upgrade-kafka-resources.adoc[leveloffset=+1]
include::modules/proc-upgrade-kafka-connect-resources.adoc[leveloffset=+1]
include::modules/proc-upgrade-kafka-connect-s2i-resources.adoc[leveloffset=+1]
include::modules/proc-upgrade-kafka-mirror-maker-resources.adoc[leveloffset=+1]
include::modules/proc-upgrade-kafka-topic-resources.adoc[leveloffset=+1]
include::modules/proc-upgrade-kafka-user-resources.adoc[leveloffset=+1]
