:_mod-docs-content-type: ASSEMBLY

[id='assembly-api-conversion-{context}']
= Converting Strimzi custom resources to the v1 API

[role="_abstract"]
This section describes how to prepare Strimzi custom resources and CRDs for the `v1` API before performing an upgrade.

Prepare Strimzi custom resources and CRDs for the `v1` API by using the Strimzi API conversion tool or by applying the required changes manually.  
The tool is provided with the release artifacts.  
To use the tool, extract it and run the conversion script from the `bin` directory.

The migration to the `v1` API has two stages.

* Version 0.49 introduces the `v1` API and deprecates the older `v1beta2` version.
* A later release (planned for 0.52.0 or 1.0.0) removes the `v1beta2` API and updates all components to use `v1`.

Complete the conversion of custom resources and CRDs after upgrading to version 0.49 or later, and before upgrading to the later release that removes the `v1beta2` API (Strimzi 0.52.0 / 1.0.0).  
Resources converted to `v1` are compatible with Strimzi versions 0.49 and later.

//tool commands
include::../../modules/upgrading/con-conversion-tool-commands.adoc[leveloffset=+1]
//prep for conversion
include::../../modules/upgrading/ref-preparing-for-conversion.adoc[leveloffset=+1]
//converting resources locally
include::../../modules/upgrading/proc-convert-custom-resource-yaml.adoc[leveloffset=+1]
//converting resources in a cluster
include::../../modules/upgrading/proc-convert-custom-resources-cluster.adoc[leveloffset=+1]
//converting resources as a job
include::../../modules/upgrading/proc-run-conversion-tool-job.adoc[leveloffset=+1]
//upgrading CRDs
include::../../modules/upgrading/proc-upgrade-crds.adoc[leveloffset=+1]
//resource updates
include::../../assemblies/upgrading/assembly-update-resources.adoc[leveloffset=+1]

