// This assembly is included in the following assemblies:
//
// deploying/master.adoc
// master.adoc

[id='assembly-upgrade-{context}']
= Upgrading Strimzi

Strimzi can be upgraded from a lower version to a higher version to take advantage of new features and enhancements, performance improvements, and security options.

As part of the upgrade, you upgrade Kafka to a higher supported version. 
Each Kafka release introduces new features, improvements, and bug fixes to your Strimzi deployment.

Strimzi can be xref:assembly-downgrade-{context}[downgraded] to the previous version if you encounter issues with a newer version.

.Upgrade paths

Two upgrade paths are possible:

Incremental:: 
Upgrading Strimzi from the current version to the next highest version.
+
For example, upgrading from Strimzi 0.20.1 to 0.21.0.

Multi-version::
Upgrading Strimzi from the current version to any higher version within a single upgrade (skipping one or more versions).
+
For example, upgrading from Strimzi 0.19.0 directly to Strimzi 0.21.0.

.Kafka version support

You can review supported Kafka versions in the link:https://strimzi.io/downloads/[Supported versions^] table.

* The *Operators* column lists all released Strimzi versions (the Strimzi version is often called the "Operator version"). 

* The *Kafka versions* column lists the set of Kafka versions that are supported by each Strimzi version. 

Additional steps are required when upgrading to an Operator version that drops support for the Kafka version you are upgrading from. 
In these situations, the upgraded Cluster Operator returns an error message, for example:

[source]
Version 2.4.0 is not supported. Supported versions are: 2.5.0, 2.5.1, 2.6.0, 2.7.0.

To continue with the upgrade, you would need to change the `spec.Kafka.version` in the Kafka custom resource to a Kafka version that is supported by the new Operator version.

.Downtime and availability

If topics are configured for high availability, upgrading Strimzi should not cause any downtime for consumers and producers that publish and read data from those topics. 
Highly available topics have a replication factor of at least 3 and partitions distributed evenly among the brokers.

Upgrading Strimzi triggers rolling updates, where all brokers are restarted in turn, at different stages of the process. 
During rolling updates, not all brokers are online, so overall _cluster availability_ is temporarily reduced.  
A reduction in cluster availability increases the chance that a broker failure will result in lost messages.

.Kafka version compatibility

You can upgrade to a higher Kafka version as long as it is supported by your version of Strimzi.
In some cases, you can also downgrade to a lower supported Kafka version.

include::assembly-upgrade-kafka.adoc[leveloffset=+1]

include::assembly-upgrade-resources.adoc[leveloffset=+1]

//how to upgrade clients and kafka streams to use the incremental cooperative rebalance protocol
include::modules/proc-upgrading-consumers-streams-cooperative-rebalancing.adoc[leveloffset=+1]