// This assembly is included in the following assemblies:
//
// deploying/deploying.adoc

[id='assembly-upgrade-{context}']
= Upgrading Strimzi

[role="_abstract"]
Upgrade your Strimzi installation to version {ProductVersion} and benefit from new features, performance improvements, and enhanced security options.
During the upgrade, Kafka is also be updated to the latest supported version, introducing additional features and bug fixes to your Strimzi deployment.

If you encounter any issues with the new version, Strimzi can be xref:assembly-downgrade-{context}[downgraded] to the previous version.

Released Strimzi versions can be found at {ReleaseDownload}.

.Upgrade without downtime

For topics configured with high availability (replication factor of at least 3 and evenly distributed partitions), the upgrade process should not cause any downtime for consumers and producers.

The upgrade triggers rolling updates, where brokers are restarted one by one at different stages of the process. 
During this time, overall cluster availability is temporarily reduced, which may increase the risk of message loss in the event of a broker failure.

include::../../modules/upgrading/con-upgrade-paths.adoc[leveloffset=+1]

include::../../modules/upgrading/con-upgrade-sequence.adoc[leveloffset=+1]

include::../../modules/upgrading/con-upgrade-cluster.adoc[leveloffset=+1]

include::assembly-upgrade-cluster-operator.adoc[leveloffset=+1]

include::assembly-upgrade-kafka-versions.adoc[leveloffset=+1]

include::../../modules/upgrading/proc-switching-to-FIPS-mode-when-upgrading-Strimzi.adoc[leveloffset=+1]
