// This assembly is included in the following assemblies:
//
// // assembly-upgrade.adoc

[id='assembly-upgrade-resources-{context}']
= Strimzi custom resource upgrades

[role="_abstract"]
After you have upgraded Strimzi to {ProductVersion}, you must ensure that your custom resources are using API version `{ApiVersion}`.
You can do this any time after moving to {ProductVersion}, but the upgrades must be completed before the next minor version update.

IMPORTANT: The upgrade of resources _must_ be performed after xref:assembly-upgrade-{context}[upgrading the Cluster Operator], so the Cluster Operator can understand the resources.

NOTE: Upgrade of the custom resources to `{ApiVersion}` prepares Strimzi for a move to Kubernetes CRD `v1`, 
which is required for Kubernetes 1.22.

.CLI upgrades to custom resources

Strimzi provides an _API conversion tool_ with its release artifacts.

ifdef::Downloading[]
You can download its ZIP or TAR.GZ file from {ReleaseDownload}.
endif::Downloading[]
ifndef::Downloading[]
You can download its ZIP or TAR.GZ from {ZipDownload}.
endif::Downloading[]
To use the tool, unpack it and use the scripts in the `bin` directory.

From its CLI, you can then use the tool to convert the format of your custom resources to `{ApiVersion}`:

* xref:proc-upgrade-cli-tool-files-{context}[]
* xref:proc-upgrade-cli-tool-direct-{context}[]

Following on from the conversion of your custom resources, you can also set `{ApiVersion}` as the _storage_ API version in your CRDs:

* xref:proc-upgrade-cli-tool-crds-{context}[]

.Manual upgrades to custom resources

As an alternative to using the API conversion tool, you can manually update each custom resource to use `{ApiVersion}`:

* xref:proc-upgrade-kafka-resources-{context}[]
* xref:proc-upgrade-kafka-connect-resources-{context}[]
* xref:proc-upgrade-kafka-connect-s2i-resources-{context}[]
* xref:proc-upgrade-kafka-mirror-maker-resources-{context}[]
* xref:proc-upgrade-kafka-topic-resources-{context}[]
* xref:proc-upgrade-kafka-user-resources-{context}[]

The manual procedures show the changes that are made to each custom resource.
After these changes, you must use the API conversion tool to upgrade your CRDs.

include::modules/con-upgrade-custom-resources.adoc[leveloffset=+1]
include::modules/proc-upgrade-cli-tool-files.adoc[leveloffset=+1]
include::modules/proc-upgrade-cli-tool-direct.adoc[leveloffset=+1]
include::modules/proc-upgrade-cli-tool-crds.adoc[leveloffset=+1]
include::modules/proc-upgrade-kafka-resources.adoc[leveloffset=+1]
include::modules/proc-upgrade-kafka-connect-resources.adoc[leveloffset=+1]
include::modules/proc-upgrade-kafka-connect-s2i-resources.adoc[leveloffset=+1]
include::modules/proc-upgrade-kafka-mirror-maker-resources.adoc[leveloffset=+1]
include::modules/proc-upgrade-kafka-topic-resources.adoc[leveloffset=+1]
include::modules/proc-upgrade-kafka-user-resources.adoc[leveloffset=+1]
